### ISSUE TITLE
Enable Epistemic scoring/strategy for monaibundle app

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1030]
Currently it's limited to run infer and train.

However for epistemic it can take existing network definition and add dropout and use the same for initializing/enabling epistemic scoring.   However the scoring can be disabled by default similar to other app (you can refer Radiology or Endoscopy app for further reference)

**Comment by tangy5** [comment]
Thanks for all the comments for this feat, as PR is merged, we might close this.
