### ISSUE TITLE
QuPath - Download Next Sample/WSI Image

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1076]
Currently the image has to be shared between MONAILabel and Client.
In some cases, all the WSI images can be part of MONAILabel and user should be able to fetch the next sample (similar to Radiology use-case)

It shall be slow to download the image from server to client.  It can be cached and checksum can be used to invalidate
But helpful in some cases where WSI are located with MONAILabel and user to have all flexibility to run QuPath from anywhere.

**Comment by SachidanandAlle** [comment]
Next Patch implementation is done.. Using random active learning strategy for testing/verifying
Need to work on Next Sample (download wsi image and load into QuPath)

![image](https://user-images.githubusercontent.com/7339051/199298859-37da7f16-6f0b-4ff3-a901-5ca112d6afb6.png)

**Comment by SachidanandAlle** [comment]
now user can download wsi image from remote

**Comment by diazandr3s** [comment]
> now user can download wsi image from remote

This is great!
