### ISSUE TITLE
CVAT project/task not created for endoscopy images

### ISSUE THREAD

**Issue by andrejadd** [Project-MONAI/MONAILabel#1088]
Hi All, 

I am trying to get CVAT tasks created with the endoscopy sample-app, but after adding files to the data store no task is created. The server detects the images and adds them to the local data store, but does not create the task. I've added the images by placing them into the `workspace/images` folder and by using a REST API call through the swagger web UI (in both cases the server processed the images but did not create a CVAT task).
 
Previously, I installed CVAT (version 2.3) and tested if the `monailabel` server can connect to it, which worked.

Is there anything that could prevent the CVAT task to be created and the images to be uploaded? I understood that the **scoring** classes will do this by calling `datastore.upload_to_cvat()` inside `CVATEpistomicScoring` or `CVATRandomScoring` class. 

Is it possible that it won't do it if the scoring is not setup properly? In this regard, how can I disable this (always upload images), or select the random scorer? I found the config parameter `skip_scoring` but it does nothing.

Here is what I've done:

- created new conda environment with Python 3.8
- installed `pip install monailabel -U`; versions are  `monai=1.0.0`, `monailabel=0.5.1`, `torch=1.12.1`
- installed cvat (version) and ran it with `docker-compose`
  - created a new user/password for monailabel
- created env vars:
  - `MONAI_LABEL_DATASTORE=cvat` 
  - `MONAI_LABEL_DATASTORE_URL=http://127.0.0.1:8080`
  - `MONAI_LABEL_DATASTORE_USERNAME=xxxxxxxx`
  - `MONAI_LABEL_DATASTORE_PASSWORD=xxxxxxxx`
- in the working directory, created subfolder `workspace/images` and copied `sample-apps/endoscopy` from this repo to `workspace/`
- started MONAILabel:
  - `monailabel start_server --app workspace/endoscopy --studies workspace/images`

It starts up without errors.
When I copy the following three images to folder `workspace/images` I get the following log:

```
2022-10-24 16:34:13,224] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:557) - Adding New Image: 000142 => 000142.jpg
[2022-10-24 16:34:13,225] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:557) - Adding New Image: 000144 => 000144.jpg
[2022-10-24 16:34:13,227] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:557) - Adding New Image: 000143 => 000143.jpg
[2022-10-24 16:34:13,243] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:540) - Invalidate count: 3
[2022-10-24 16:34:13,285] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:540) - Invalidate count: 0
[2022-10-24 16:34:13,298] [1292866] [Thread-1] [INFO] (monailabel.datastore.local:540) - Invalidate count: 0
```
Nothing else happens and there is no project or task in CVAT.

I also did these: 

- `--conf epistemic_enabled false` - hoped to disable the Epistemics scoring
- `--conf skip_scoring false`

Anyone has an idea what could prevent task creation in CVAT? I could also look deeper into the code, if you could point out the place that needs attention.

**Comment by tangy5** [comment]
Hi @andrejadd , thanks for the question.
If I understood your question correctly, you'd like to check if there is a way to upload endoscopy images to CVAT without scoring process or with random scorer. 

First of all:
If you would like to push and upload all images to CVAT for labeling no matter what scoring methods are used, you could set epistemic_top_k parameter equal to the number of images added.
```
monailabel start_server \
  --app workspace/endoscopy \
  --studies workspace/images \
  --conf epistemic_enabled true \
  --conf epistemic_top_k 3 \
  --conf auto_finetune_models tooltracking \
  --conf auto_finetune_check_interval 30
```

If you'd like to do random scoring with some modification of codes. For example, tooltracking model has the config script:

```
            methods[f"{self.name}_epistemic"] = CVATEpistemicScoring(
                top_k=int(self.conf.get("epistemic_top_k", "10")),
                infer_task=lib.infers.ToolTracking(
                    self.bundle_path,
                    self.conf,
                    dropout=0.2,
                    train_mode=True,
                    skip_writer=True,
                ),
                function="monailabel.endoscopy.tooltracking",
                max_samples=self.epistemic_max_samples,
                simulation_size=self.epistemic_simulation_size,
                use_variance=True,
            )
```
in https://github.com/Project-MONAI/MONAILabel/blob/739226b381caa1a6c4579633a06e19f9bdf04178/sample-apps/endoscopy/lib/configs/tooltracking.py#L67.
You could replace the EpistemicScoring with the RandomScoring
https://github.com/Project-MONAI/MONAILabel/blob/739226b381caa1a6c4579633a06e19f9bdf04178/sample-apps/endoscopy/lib/scoring/cvat.py#L81

Or you could customize scoring functionalities for each model in lib/configs scripts.


Thanks

**Comment by andrejadd** [comment]
Thanks for the quick response. I increased `epistemic_top_k` and actually something happened and images got processed with inference from the model. Then the epistemic scoring starts, but it fails because of another error (not related to this issue). 
FYI, its about the BasicUNet:
```
RuntimeError: Given groups=1, weight of size [32, 3, 3, 3], expected input[1, 682, 737, 481] to have 3 channels, but got 682 channels instead
BasicUNet features: (32, 64, 128, 256, 512, 32).
```
I'll close this issue for now.
