### ISSUE TITLE
Add command to stop running monailabel server

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAILabel#1099]
As monai label features is growing, I am running multiple servers from the same host, one for radiology, another for pathology, and a 3rd for videos. It would be nice If I can easily start them in the background and give each an alias 

Request: 
1- Please provide an option to start the server as background --> currently I use `&`  
2- Please provide a way to give monailabel server an alias, would make it easier to find the pid and stop it 
3- Provide a cli to stop the running server 

Suggestions /workarounds: I currently have scripts below to do the job. However if I launch multiple servers I am unable to differentiate 

```
#!/bin/bash
start_label(){
    cd $labelDataRoot 
    monailabel start_server \
        --app apps/radiology \
        --studies datasets/Task09_Spleen/imagesTr \
        --conf models deepedit,segmentation &
    echo just started monai label
}
stop_label(){
    pid=$(ps -ef | grep bash | grep monailabel | awk '{print $2}')
    if [ -z $pid ];then
        echo No pid to kill
    else
        echo killing pid= $pid
        pkill -9 -e -P $pid
    fi
}
```

**Comment by SachidanandAlle** [comment]
We suggest using docker containers per instance of monailabel server.  That's the best way to manage the life-cycle.
However I am keeping this issue on backlog.. If there are more users showing similar request, we can pick it up.

Otherwise, feel free to raise a PR and add your contributions.
https://github.com/Project-MONAI/MONAILabel/blob/main/CONTRIBUTING.md

**Comment by SachidanandAlle** [comment]
lets not push the process in background.. and allow user/docker etc.. to choose.
#1208 should help you to add run kill script/command better.

`kill -9 $(ps -ef | grep monailabel | grep start_server | grep -v grep | awk '{print $2}')`
