### ISSUE TITLE
Miscellaneous - Move some common utilties to MONAI repository

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#11]
Example: Transforms, Writer which are currently used in monailabel to complete e2e functionality

And anything else.. which makes sense to move it to MONAI

**Comment by diazandr3s** [comment]
- Moved the deepedit transforms (https://github.com/Project-MONAI/MONAI/tree/dev/monai/apps/deepedit)
- Once the unit test for deepedit interaction is working, I'll move it as well
- Need to discuss about the new tensorboard handler

**Comment by SachidanandAlle** [comment]
Lets close this for now.. revisit when it's needed
