### ISSUE TITLE
ITKWriter can write nrrd files

### ISSUE THREAD

**Issue by dyollb** [Project-MONAI/MONAILabel#1115]
Looking through some code I stumbled across this `write_seg_nrrd` function. 

https://github.com/Project-MONAI/MONAILabel/blob/91c48c453986831d3bf1d7bc0fddb1bd60595f0d/monailabel/transform/writer.py#L69

ITK has support for nrrd (reading/writing), so this code could probably use `SaveImaged(writer="ITKWriter", ...` instead

**Comment by jlvahldiek** [comment]
`ITKWriter` supports nrrd, that's correct. As far as I remember, at the time when we committed the `write_seg_nrrd` function, it was not possible to write multi-channel arrays with overlapping segments using `ITKWriter`. Is it now possible, @dyollb? @markus-hinsche, maybe you could also add a comment?

**Comment by dyollb** [comment]
I think so, but I can imagine there may be differences in how the image is written (3D vs 4D) and then interpreted by 3rd party libraries/tools.

For instance, when I write the "probability" channels before doing `argmax` using `SaveImaged`, I get two different behaviors
- ITKWriter: writes an image that is interpreted as 3D with N channels by e.g. SimpleITK
- NibabelWriter: is interpreted as 4D by SimpleITK

Btw. I don't the fact that segments are overlapping should be a problem with ITK, but obviously they need to be stored in separate channels.

**Comment by pieper** [comment]
You may want to look into [the SlicerIO[(https://pypi.org/project/slicerio/0.1.5/) package.
