### ISSUE TITLE
Spine Localisation Network Definition 

### ISSUE THREAD

**Issue by ericspod** [Project-MONAI/MONAILabel#1138]
**Describe the bug**
The network definition for spine localisation [here](https://github.com/Project-MONAI/MONAILabel/blob/434dfddd7727c61cfd663fc3430d7b493d436ba3/sample-apps/radiology/lib/configs/localization_spine.py#L77) appears to have channels for every vertebra, however this should be a binary segmentation task? The UNet definition for the per-vertebra labeling [here](https://github.com/Project-MONAI/MONAILabel/blob/434dfddd7727c61cfd663fc3430d7b493d436ba3/sample-apps/radiology/lib/configs/segmentation_vertebra.py#L76) appears to be binary so have these two been mixed up?

**Comment by diazandr3s** [comment]
Hi @ericspod,

Thanks for checking this. I know this seems a bit confusing.
The final output of the spine localisation model is binary. However, we trained the network with all vertebra labels and then binarised the output. This post-transform does that: https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/infers/localization_spine.py#L85

This way of training works better than binarising the vertebra labels first to train the network.

Regarding the third stage (segmentation vertebra), it is also binary and it only segments one vertebra at a time.

Hope this makes sense

**Comment by ericspod** [comment]
Ok that does make sense. Thanks!

**Comment by saileshsidhwani** [comment]
@diazandr3s, the motivation on why it is like this makes sense but leads to incorrect results when using this model for inference tasks inside annotation tools like Slicer3D.

This particular model gives the final output as binary "spine" but the slicer3D assigns it to the label C1 which is misleading. Any thoughts on this? I think this should be handled somewhere to avoid confusion. Should this be handled at the model level or should this be handled at the viewer?
