### ISSUE TITLE
segmentation network definition 

### ISSUE THREAD

**Issue by MichelaA** [Project-MONAI/MONAILabel#1139]
**Describe the bug**
The segmentation example [here](https://github.com/Project-MONAI/MONAILabel/blob/434dfddd7727c61cfd663fc3430d7b493d436ba3/sample-apps/radiology/lib/trainers/segmentation.py) is very oriented to CT images and it is not easy to understand what should be changed to adapt it to MRI. Maybe a comment on the specific transforms could help to understand what to change/remove

**Comment by SachidanandAlle** [comment]
Have you trained a model on MR dataset?

**Comment by tangy5** [comment]
Hi @MichelaA , for a quick answer. 
You might need to modify this transforms according to MRI images:

`            ScaleIntensityRanged(keys="image", a_min=-175, a_max=250, b_min=0.0, b_max=1.0, clip=True),
`
The normalization should be different, MRI should be more adaptive to zero-mean norm and scale.
Other transforms might also need to be changed correspond to different tasks. 
As @SachidanandAlle mentioned, the pre-trained model should be trained with CT images, and can't be used directly for MRI.
You might need to train your own MRI model. 

Thanks again, glad to see more applications with MONAI Label.

**Comment by SachidanandAlle** [comment]
I believe you are able to figure it out how and where you can add your network and related transforms to make other MRI usecase work.

https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/configs/segmentation_spleen.py#L61
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/infers/segmentation_spleen.py#L55
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/trainers/segmentation_spleen.py#L57
