### ISSUE TITLE
Save Label in NRRD format instead of NIFTI as an option 

### ISSUE THREAD

**Issue by bpataybac** [Project-MONAI/MONAILabel#1149]
MONAI Label accepts NRRD volumes for segmentation; however, it appears it saves segmentation label in NIFTI.  May we have an option in the command line to save in NRRD?

**Comment by SachidanandAlle** [comment]
Yes.. you can pass `{"result_extension": ".nrrd"}` in the params
![image](https://user-images.githubusercontent.com/7339051/202025179-8835fe17-9c52-487c-b2a8-9aab18d9ab77.png)


Example:
https://github.com/Project-MONAI/MONAILabel/blob/main/plugins/slicer/MONAILabel/MONAILabel.py#L2179

**Comment by bpataybac** [comment]
Thank you so much.
