### ISSUE TITLE
Unable to run inference or upload labels after failed sample fetch

### ISSUE THREAD

**Issue by bkonk** [Project-MONAI/MONAILabel#1151]
I'm trying to train a segmentation model on some test data (nifti format). I'm able to generate and submit labels, and train and run inference. However, I will occasionally hit "Failed to fetch Sample from MONAI Label Server" when I select "Next Sample". This could be a corrupted file or something (it's random test data so I'm not concerned and happy to skip over). If I hit "Next Sample" again after this error, it pulls up the next file successfully but "Submit Label" under Active Learning and "Run" under Auto Segmentation become greyed out afterwards. Is there a workaround to maintain label submission and inference options after this error?

I'm running Slicer 5.1.0-2022-06-22 r31055 / 34696fb w/ MONAILabel 29a2543 (2022-06-23).

**Comment by SachidanandAlle** [comment]
You can directly copy/place the labels into your studies/labels/final folder.. monailabel will auto detect them.. and you start training

**Comment by SachidanandAlle** [comment]
I believe you can run your training with existing labels etc.. 
Also to help to debug better.. please share the monailabel server logs..

**Comment by SachidanandAlle** [comment]
I believe you were able to use monailabel.. for basic use-case.  Closing this issue.  If anything not solved yet, feel free reopen the same.
