### ISSUE TITLE
Issue with pyproject.toml when installing monailabel through pip on windows

### ISSUE THREAD

**Issue by MLK97** [Project-MONAI/MONAILabel#1154]
**Describe the bug**
I am currently trying to install monailabel on a windows 11 machine through pip.
The installation fails during preparing the metadata from/in pyproject.toml.

**To Reproduce**
1. Go to [quickstart manual'](https://docs.monai.io/projects/label/en/latest/quickstart.html)
2. Install monailabel as described

**Expected behavior**
The installation finishes successful.

**Output**
```
Collecting numpymaxflow==0.0.2
  Using cached numpymaxflow-0.0.2.tar.gz (13 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [292 lines of output]
      Collecting setuptools
        Using cached setuptools-65.5.1-py3-none-any.whl (1.2 MB)
      Collecting numpy==1.19.2
        Using cached numpy-1.19.2.zip (7.3 MB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error
     
        Preparing metadata (pyproject.toml) did not run successfully.
        exit code: 1
```

**Additional context**
This might be more of an issue related to installing monailabel on windows but after some time searching online I am still not able to install monailabel. If there is any additional package required to install it might be good to add this to the quickstart guide!

**Comment by SachidanandAlle** [comment]
I believe using release candidate or main branch should have fixed this problem.  Closing for now.
