### ISSUE TITLE
Monailabel and OHIF

### ISSUE THREAD

**Issue by Coffee2000** [Project-MONAI/MONAILabel#1182]
Hi! I cloned the github repository  using : git clone https://github.com/Project-MONAI/MONAILabel   and then ran the command
pip install -r MONAILabel/requirements.txt in my linux terminal. According to #1106 ohif should now be pre- built. 

I have installed orthanc but when I run   monailabel start_server --app apps/radiology --studies http://127.0.0.1:8042/dicom-web
--conf models deepedit , the monai label API does show up on port 8000 but not dicom-web or ohif. I either get a refused to connect error or 'resource not found' error. 

Any help is appreciated!

**Comment by tangy5** [comment]
If monailabel is installed in full pack, after monailabel start server is up, you could check the page:
http://127.0.0.1:8000/ohif/ 
for OHIF access.
If monailabel is not installed in full pack, you could build OHIF following this page: https://github.com/tangy5/MONAILabel/tree/main/plugins/ohif

Hope this helps~

**Comment by diazandr3s** [comment]
> Hi! I cloned the github repository using : git clone https://github.com/Project-MONAI/MONAILabel and then ran the command pip install -r MONAILabel/requirements.txt in my linux terminal. According to #1106 ohif should now be pre- built.
> 
> I have installed orthanc but when I run monailabel start_server --app apps/radiology --studies http://127.0.0.1:8042/dicom-web --conf models deepedit , the monai label API does show up on port 8000 but not dicom-web or ohif. I either get a refused to connect error or 'resource not found' error.
> 
> Any help is appreciated!

If you're cloning the repo from GitHub, you should build OHIF as it is shown here: https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#development-setup

If you can't see the MONAI Label API on http://127.0.0.1:8000/ please share the logs. There should a different issue

**Comment by SachidanandAlle** [comment]
closing this issue.. as suggested, if you are looking for oHIF from github, you need to build yourself.. the note is already mentioned here: https://github.com/Project-MONAI/MONAILabel#git-checkout-developer-mode

**Comment by Coffee2000** [comment]
Hi! Sorry it took me a while to get back but it still doesn't work for me. I am new to this and trying to figure it out an ec2 instance. The monailabel API is showing up, orthanc is also on port 8042 but ohif is still not. These are the last few lines on my terminal that are showing up. 

[2022-12-23 02:53:59,051] [8348] [MainThread] [INFO] (uvicorn.error:59) - Application startup complete.
[2022-12-23 02:53:59,051] [8348] [MainThread] [INFO] (uvicorn.error:206) - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
[2022-12-23 02:54:26,712] [8348] [MainThread] [INFO] (monailabel.endpoints.ohif:38) - /home/ubuntu/environment/MONAILabel/monailabel/endpoints/static/ohif/index.html
[2022-12-23 02:54:30,545] [8348] [MainThread] [INFO] (monailabel.endpoints.ohif:38) - /home/ubuntu/environment/MONAILabel/monailabel/endpoints/static/ohif/index.html

I built ohif as shown in the documents but that didn't help. I just keep getting {"detail":"Resource NOT Found"}
