### ISSUE TITLE
Bad Monailabel annotations in DSA on EC2 Amazon Linux

### ISSUE THREAD

**Issue by orenlivne** [Project-MONAI/MONAILabel#1198]
**Describe the bug**
The annotations produced by the `segmentation_nuclei` model in the monailabel DSA plugin are nonsensical, on EC2 Amazon Linux.

**To Reproduce**
1. Create an EC2 GPU instance with Amazon Linux OS: `Linux ip-172-31-65-118.ec2.internal 5.10.147-133.644.amzn2.x86_64 #1 SMP Fri Oct 14 01:16:24 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux`.
3. Install DSA using docker-compose.
4. Build openslide from sources.
5. Install monailabel from github sources.
6. Install monailabel DSA plugin using the Slicer CLI Web plugin on the admin dashboard.
7. Open a test image.
8. Submit a monai annotation job.

**Screenshots**
<img width="1265" alt="Screen Shot 2022-12-09 at 12 42 01 PM" src="https://user-images.githubusercontent.com/2911829/206761790-ae06b1f9-cd37-4235-92bc-f49c5a7923a8.png">

Note that the same workflow works on MacOS. Annotations are good there.

**Comment by SachidanandAlle** [comment]
Thanks for reporting.. we will look into the issue.. and provide the fix asap..

@tangy5

**Comment by tangy5** [comment]
Pathology application recently has big changes, I guess we haven't test DSA much. Let me look into this. 
Thanks for reporting the issue.

**Comment by SachidanandAlle** [comment]
We will work on this and provide the solution asap (next couple of days).  It will be included in release candidate planned by end of the week.

Meanwhile you can try to use release version 0.5.2 if you are blocked on something.
