### ISSUE TITLE
GPU memory isn't cleared

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#123]
**Describe the bug**

GPU memory is not cleared after sending the "stop training" call to the server. After doing several start training/stop training calls, the system runs out of memory.

**To Reproduce**

  - Stopping the training
  r = requests.delete(url_server + 'train/')
  print(r.text)

  - Re-starting training
  r = requests.post(url_server + 'train/')
  print(r.text)

**Expected behavior**

GPU memory is cleared after a stop training call is made

**Screenshots**
![out_of_memory](https://user-images.githubusercontent.com/11991079/121440848-9e136480-c980-11eb-8d12-a723286a568d.png)

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

================================
Printing MONAI config...
================================
MONAI version: 0.5.2
Numpy version: 1.19.5
Pytorch version: 1.8.0.dev20210208+cu110
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: feb3a334b7bbf302b13a6da80e0b022a4cf75a4e

Optional dependencies:
Pytorch Ignite version: 0.4.4
Nibabel version: 3.2.1
scikit-image version: 0.17.2
Pillow version: 8.1.0
Tensorboard version: 2.4.1
gdown version: 3.12.2
TorchVision version: 0.9.0.dev20210211+cu110
ITK version: 5.1.2
tqdm version: 4.56.0
lmdb version: 1.2.1
psutil version: 5.8.0

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.2 LTS
Platform: Linux-5.4.0-74-generic-x86_64-with-debian-bullseye-sid
Processor: x86_64
Machine: x86_64
Python version: 3.6.12
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 16
Num logical CPUs: 32
Num usable CPUs: 32
CPU usage (%): [37.1, 29.0, 29.0, 25.8, 30.3, 30.0, 93.8, 28.1, 29.0, 28.1, 31.2, 28.1, 31.2, 25.8, 28.1, 25.0, 28.1, 29.0, 29.0, 29.0, 32.3, 93.5, 29.0, 32.3, 31.3, 33.3, 28.1, 34.4, 25.8, 100.0, 31.3, 29.0]
CPU freq. (MHz): 3892
Load avg. in last 1, 5, 15 mins (%): [23.6, 17.1, 17.2]
Disk usage (%): 90.4
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 125.8
Available memory (GB): 109.2
Used memory (GB): 15.3

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.0
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80']
GPU 0 Name: GeForce RTX 3090
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 82
GPU 0 Total memory (GB): 23.7
GPU 0 CUDA capability (maj.min): 8.6

**Additional context**

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/124/commits/65a36ccaad235007a389db8dbb63f50c838f1de7

lets c if this solves the problem... (clear cuda cache on stop tasks)

**Comment by diazandr3s** [comment]
I've tried **torch.cuda.empty_cache()** but it doesn't clear the GPU memory. So far the only way to clear memory is by restarting the server :/

**Comment by SachidanandAlle** [comment]
Training runs in a sub process.. for async.. lets try to make it demon.. it
should not hold gpu when its killed..

**Comment by SachidanandAlle** [comment]
Fixed https://github.com/Project-MONAI/MONAILabel/pull/126
