### ISSUE TITLE
Docs: Demo videos for 0.6 release features

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1256]
Demo videos for 0.6 release features (Pathology, QuPath, Experiment Management)

**Comment by SachidanandAlle** [comment]
Any updates on this?

**Comment by tangy5** [comment]
Working in progress. 

I'm thinking to make 2 video. 

We will need to add to this page right? 
 https://www.youtube.com/watch?v=KjwuFx0pTXU&list=PLtoSVSQ2XzyD4lc-lAacFBzOdv5Ou-9IA&index=2&t=90s

1. Pathology + Qupath: segmentation_nuclei, nuclick models. Qupath setup, segmentation inference/training
2. Experiment Management setup and usesage. 

If this makes sense

**Comment by tangy5** [comment]
Some progress for this:

Two video are recorded.

1. Pathology + QuPath setup and nuclei segmentation: https://drive.google.com/file/d/13hQUMVUDnsHcirLSbEW1umQMFPX1I4Wp/view?usp=share_link
2. MLflow experiment management with MONAI Label Radiology App Training:  https://drive.google.com/file/d/1uSa6Bpcqcvcxd3wAy52J-1ctcDFbFMpy/view?usp=share_link

I'm adding some audio to them. 
Hi @zephyrie , we may need  some nice MONAI templates and polish, any suggestions? Thank you! Then move to Youtube.

**Comment by zephyrie** [comment]
Hi @tangy5, let me set up a meeting with you to go over the content and audio.  I'm happy to help record audio/edit but we just need to make sure all the relevant information is available.  For Andres' videos, we trimmed together the content and made sure audio+video aligned correctly, plus added the music/intro/outro/labels for everything.

**Comment by tangy5** [comment]
Hi Michael, thanks.

**Comment by SachidanandAlle** [comment]
Is this done?  Can be closed?

**Comment by tangy5** [comment]
Yes, we can close this. The videos are there. There is one step to push to Youtube, working with Michael.
