### ISSUE TITLE
Docs: restructuring/refining/alignment etc.. wrt core

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1257]
Refine and Align with MONAI CORE docs

**Comment by tangy5** [comment]
Michael needs a final push for the doc restructuring after GTC, we have been synced with the changes. Will update us.

**Comment by SachidanandAlle** [comment]
I guess this is done?

**Comment by tangy5** [comment]
> I guess this is done?

Yup.
