### ISSUE TITLE
Plugin/Module to visualize MONAI Transforms

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1258]
Plugin/Module to visualize MONAI Transforms

**Comment by SachidanandAlle** [comment]
@lassoan can we run monai apis in python interpreter in 3D Slicer.  
There is some dependency issue when I tried to install MONAI (monai==1.1.0) in 3D slicer

Have anyone in the community tried to run monai inside 3D slicer locally?

```python
import pip
pip.main(['install', 'monai'])
```

**Comment by pieper** [comment]
This works for me in Slicer 5.2.1:

![image](https://user-images.githubusercontent.com/126077/214204414-a3db5053-d680-4312-8c7c-e64cf958459c.png)

Visualizing transforms sounds great - I'd like to see intermediate training results too.  Let me know if I can help.

**Comment by lassoan** [comment]
Yes, `pip_install('monai')` works well in Slicer's Python for me, too. Tested on Windows on a freshly installed Slicer-5.2.1:

```
pip_install('monai==1.1.0')
import monai
print(monai.__version__)
1.1.0
```

Usage of `pip.main` fails for me, too, but that's not surprising, as this calling convention got deprecated several years ago. The only allowed method to use pip is `python -m pip...` and that's what Slicer's `pip_install` convenience method uses internally. We recommend using `pip_install` within Slicer as it allows us to add/override some options to ensure better Slicer compatibility (but so far we haven't had to override anything, we just pass all the parameters unchanged).

**Comment by SachidanandAlle** [comment]
Thanks..  `pip_install` works great.. didn't know about this one.. I am outdated ;)

**Comment by SachidanandAlle** [comment]
> This works for me in Slicer 5.2.1:
> 
> ![image](https://user-images.githubusercontent.com/126077/214204414-a3db5053-d680-4312-8c7c-e64cf958459c.png)
> 
> Visualizing transforms sounds great - I'd like to see intermediate training results too. Let me know if I can help.

thank you.. i guess that's the plan.. at the end if user visualizes what data he is feeding into training engine, will help to debug/solve some simple mistakes during data preparation..

will start with some iteration/prototype and you can add/enhance it better :)

**Comment by pieper** [comment]
Looking forward to seeing what you put together @SachidanandAlle - I'm doing some training and would be very interested in better understanding that the pre and post transforms are doing.

**Comment by kbressem** [comment]
I don't know if this fits here, but I have been working on a iPython widget which can visualize 2d and 3d tensors inside notebooks, similar to how a radiologist would view the image. 
If this adds value, I am happy to contribute. 


## BasicViewer
The base class of all viewers. Can show a single image, optionally with mask overlay or label. Also allows to add a title to the image. 

![image](https://user-images.githubusercontent.com/37253540/212560078-f1fa9d52-9b6d-4626-baf5-3784998bdc19.png)


## ListViewer
As subclass of BasicViewer that allows to view multiple images at once. Useful to compare images or to be implemented in other functions. In [trainlib](https://github.com/kbressem/trainlib) I use it in `DataLoader.show_batch`, to inspect the batch before it is passed to the model. 

![image](https://user-images.githubusercontent.com/37253540/212560212-b19f0341-511d-4473-ab41-5a321ae578c9.png)

**Comment by SachidanandAlle** [comment]
We need something similar in 3D slicer show multiple tensors (each coming from a transform output) during the data-processing.

User should be able to pick/load any image/label and go through sequence of MONAI transforms and he/she should be able to visualize the output of each transform.  Output can be both binary and some dictionary attributes which get added/modified by current transform.  

In some cases it can be some signals too (e.g. click points in case of interaction models) and user should have an option to highlight (create ROI/Fluidical points etc..) for such information over image/masks.  Many times user doesn't generate/offset such information accordingly the input and ends up training on wrong signal information.

**Comment by lassoan** [comment]
These kind of features are available in Slicer, so it should not be too hard to set it up. Let us know if you need any help.

If all the data that you want to browse fits in memory and you need very quick browsing then you can use sequences infrastructure to browse multiple related nodes, such as 3D volume, segmentation, markups, text, table, ... with the sequence browser (to do that, you need to add each "data" node into a "sequence" node and add the sequence nodes to a "sequence browser" node).

If data is loaded from disk then probably the simplest is to add a slider to your module GUI and implement loading from disk/saving/unloading as the slider is moved.

**Comment by wyli** [comment]
many thanks @SachidanandAlle for initiating https://github.com/Project-MONAI/SlicerMONAIViz, for further contributions please use https://github.com/Project-MONAI/SlicerMONAIViz/issues
