### ISSUE TITLE
Changes related to User Login/Auth support for MONAILabel plugin in 3D Slicer

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1259]
Changes related to User Login/Auth support for MONAILabel plugin in 3D Slicer

**Comment by kbressem** [comment]
This feature would be so great. We want to host MONAILabel in our hospital, but need to make sure only people allowed to access the data can do so.

**Comment by SachidanandAlle** [comment]
This is feature is available for early access.
Please follow instructions as mentioned: https://github.com/Project-MONAI/MONAILabel/wiki/Integration-with-Keycloak
