### ISSUE TITLE
vertebrae_pipeline produces an error during inference 

### ISSUE THREAD

**Issue by deepakri201** [Project-MONAI/MONAILabel#1268]
**Describe the bug**

Hi, I am trying to run the 3 stage vertebrae_pipeline (inference using the provided pretrained model) through 3DSlicer. In particular I'm trying to run inference on a dataset from VERSE 2019 and 2020, which I believe was used was used for training. When running the pipeline, I get the error below about `RuntimeError: Expected 4D or 5D (batch mode) tensor with possibly 0 batch size and other non-zero dimensions for input, but got: [1, 1, 0, 0, 0]`

**Server logs**
If applicable attach 100+ lines of monailabel server logs which covers the error trace etc...
![segmentation_vertebrae_inference_error](https://user-images.githubusercontent.com/59979551/215518355-e4753684-07e2-4593-bec0-3b6cd574983a.JPG)

**To Reproduce**
I've sucessfully set up and installed MONAI and MONAI Label locally, and can start the server and run the label app through Slicer. I've confirmed this all works by trying out the spleen segmentation pretrained model, which yields reasonable results.
For the vertebrae_segmentation, I've downloaded nifti files from VERSE 2019 and 2020 training data (which is the training data for the vertebrae_pipeline I believe). Therefore I expect the 3 steps of the pipeline to perform well.

monailabel start_server --app apps/radiology --studies apps/datasets/VERSE --conf models "localization_spine,localization_vertebra,segmentation_vertebra"
Load the nifti data
Select the vertebrae_pipeline stage to run

**Expected behavior**
I expected the pipeline would run successfully and create individual vertebrae segmentations. 

**Environment**

Ensuring you use the relevant python executable, please paste the output of:

```
python -c 'import monai; monai.config.print_debug_info()'
```

python -c 'import monai; monai.config.print_debug_info()'
(monai) C:\Users\deepa>python -c "import monai; monai.config.print_debug_info()"
Printing MONAI config...
MONAI version: 1.1.0
Numpy version: 1.23.5
Pytorch version: 1.13.1
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: a2ec3752f54bfc3b40e7952234fbeb5452ed63e3
MONAI file: C:\Users\deepa\miniconda3\envs\monai\lib\site-packages\monai_init_.py

Optional dependencies:
Pytorch Ignite version: 0.4.10
Nibabel version: 5.0.0
scikit-image version: 0.19.3
Pillow version: 9.4.0
Tensorboard version: 2.11.2
gdown version: 4.6.0
TorchVision version: 0.14.1
tqdm version: 4.64.1
lmdb version: 1.4.0
psutil version: 5.9.4
pandas version: 1.5.3
einops version: 0.6.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.1.1
pynrrd version: 0.4.3

For details about installing the optional dependencies, please visit:
https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

Printing system config...

System: Windows
Win32 version: ('10', '10.0.19045', 'SP0', 'Multiprocessor Free')
Win32 edition: Core
Platform: Windows-10-10.0.19045-SP0
Processor: Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Machine: AMD64
Python version: 3.10.8
Process name: python.exe
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\Windows\System32\en-US\KernelBase.dll.mui', fd=-1), popenfile(path='C:\Windows\System32\en-US\kernel32.dll.mui', fd=-1), popenfile(path='C:\Windows\System32\en-US\tzres.dll.mui', fd=-1)]
Num physical CPUs: 4
Num logical CPUs: 8
Num usable CPUs: 8
CPU usage (%): [43.5, 25.6, 33.6, 23.1, 19.0, 14.0, 10.1, 14.3]
CPU freq. (MHz): 2803
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 63.7
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 15.8
Available memory (GB): 3.3
Used memory (GB): 12.5

Printing GPU config...

Num GPUs: 0
Has CUDA: False
cuDNN enabled: False

**Additional context**

**Comment by SachidanandAlle** [comment]
Have you tried samples from medical decathlon dataset?

**Comment by SachidanandAlle** [comment]
Also can you confirm if you have GPU enabled Pytorch?

**Comment by deepakri201** [comment]
> 

I unfortunately don't have a GPU and was using the CPU pytorch installation. Is this okay for inference?

**Comment by deepakri201** [comment]
> Also can you confirm if you have GPU enabled Pytorch?


I unfortunately don't have a GPU and was using the CPU pytorch installation. Is this okay for inference?

**Comment by SachidanandAlle** [comment]
CPU is not guaranteed to provide results for MONAILabel.. some of the networks/models won't run on CPU

**Comment by deepakri201** [comment]
> Have you tried samples from medical decathlon dataset?

I jus t tried an example from the spleen dataset, and it does produce some spine segmentations:

![example_localization_spine_on_spleen_dataset](https://user-images.githubusercontent.com/59979551/215542290-cc3c6503-e4ee-4498-8cc0-c16ce7ca71b0.JPG)

**Comment by deepakri201** [comment]
> 


> CPU is not guaranteed to provide results for MONAILabel.. some of the networks/models won't run on CPU

Ah okay thanks for letting us know.

**Comment by deepakri201** [comment]
> Have you tried samples from medical decathlon dataset?

I tried an example from the decathalon spleen dataset, and all three stages of vertebrae segmentation ran successfully:

![example_segmentation_vertebrae_on_spleen_dataset](https://user-images.githubusercontent.com/59979551/215549087-76b73e94-4c0a-46fa-a7b2-e6c7a2d76c49.JPG)

**Comment by SachidanandAlle** [comment]
No further updates/comments on this issue.  I believe things are resolved.  Closing it for now.
