### ISSUE TITLE
Push docs for monailabel to https://docs.monai.io/label/

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#130]
Lets discuss with @wyli on the possible options for the placeholder for monailable docs

**Comment by wyli** [comment]
@IsaacYangSLA has been helping set up the backend on readthedocs, could we ask him for help as well

**Comment by SachidanandAlle** [comment]
@IsaacYangSLA 

> From @pdogra89
can we do something like this.. as prerna mentioned?
For docs, following the pytorch example (https://pytorch.org/audio), I prefer  -  https://docs.monai.io/label
