### ISSUE TITLE
Push weekly package for monailabel to https://pypi.org/

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#131]

**Comment by SachidanandAlle** [comment]
First, lets start with weekly (development) package similar to monai
In the first week of july.. we can do a release version

@wyli do we have a common account for PyPi... which can be used to create/push packages for monailabel

**Comment by wyli** [comment]
there's a project-monai  account, so I can think of two approaches after having the pip wheels ready for uploading:
- I can help upload it via the pypi project-monai account
- upload via any pypi account and then add pypi project-monai to the owner/maintainer list
