### ISSUE TITLE
Blackduck reports NPM and GRADLE Failure

### ISSUE THREAD

**Issue by YanxuanLiu** [Project-MONAI/MONAILabel#1320]
**Describe the bug**
When we trigger blossom-ci, it will run vulnerability scan first.
It reports NPM and GRADLE failure.
https://github.com/Project-MONAI/MONAILabel/actions/runs/4230364922/jobs/7347611921#step:4:162

I suggest to skip npm and gradle detector to ensure the blossom-ci runs well.

**Comment by pxLi** [comment]
still require blossom team to help support exclude detectors/dirs

**Comment by SachidanandAlle** [comment]
please discard or exclude src/plugins folder from the scan

**Comment by pxLi** [comment]
this issue should be fixed, also cc @YanxuanLiu to double confirm
