### ISSUE TITLE
Unable to Submit label in Monai-label 

### ISSUE THREAD

**Issue by risheetreddy** [Project-MONAI/MONAILabel#1330]
When we are trying to submit label in Monai-label UI after annotation but its throwing an error. 

  **File "/root/MONAILabel/monailabel/endpoints/datastore.py", line 250, in api_save_label
    return save_label(background_tasks, image, params, tag, label, user.username)
  File "/root/MONAILabel/monailabel/endpoints/datastore.py", line 113, in save_label
    label_id = instance.datastore().save_label(image, label_file, tag, save_params)
  File "/root/MONAILabel/monailabel/datastore/dicom.py", line 208, in save_label
    label_id = super().save_label(image_id, label_filename, label_tag, label_info)
  File "/root/MONAILabel/monailabel/datastore/local.py", line 488, in save_label
    raise ImageNotFoundException(f"Image {image_id} not found")
monailabel.interfaces.exception.ImageNotFoundException: Image 1.3.6.1.4.1.11169.7318227128502.20150618080659.200.79830 not found**

**Note:** We are accessing the data from Health care API dicom store GCP 

Can anyone help us to solve this issue and save/submit the label in Monai-label UI

**Comment by tangy5** [comment]
I'm not very familiar with the GCP and Dicom datastore part, @diazandr3s , @SachidanandAlle , do you have any hints of this issue? It would be great that could take a look after you are back.
Looks like here that image is not in the datastore JSON. The datastore is either not initialized or not updated.. 

https://github.com/Project-MONAI/MONAILabel/blob/5d2ae1fbb770040ef1e428b8e7b0312c6bbead75/monailabel/datastore/local.py#L487

**Comment by diazandr3s** [comment]
Hi @risheetreddy,

Sorry, what do you mean by Monai-label UI? Are you using 3D Slicer? 
Can you provide more details about the workflow you're following?

**Comment by SachidanandAlle** [comment]
I guess you are using dicomweb here.. give use more details.. possibly 200 to 300 lines of logs..  to understand..

**Comment by SachidanandAlle** [comment]
I don't see further comments/logs shared.. are u still not able to save label?
