### ISSUE TITLE
How to do cascading infer with MonaiLabel

### ISSUE THREAD

**Issue by XU-Wenyi** [Project-MONAI/MONAILabel#1358]
We have a situation, firstly we segment a certain organ in the image, and then we segment a certain type of focus. 
How we run a cascade network inference by using MonaiLabel.

**Comment by Liucd0520** [comment]
@diazandr3s Thanks for your reply, I use the multiple stage vertebra segmentation model and success. 
Meanwhile, I realize that this tutorial is a 'tree-stage' task, and is not applicable at  'two-stage' task (1. Organ location； 2. Tumor ）.  I try to modify the configs and infers，But the vertebra_pipeline.py is difficult to read and adjust.

> Is there some more targeted recommendations and tutorials for me, Thanks

**Comment by SachidanandAlle** [comment]
you can implement directly InferTask and add any customized processing in __call__ method

Derive your InferTask from this:
https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/interfaces/tasks/infer_v2.py
