### ISSUE TITLE
Slicer segment editor list is too small

### ISSUE THREAD

**Issue by AHarouni** [Project-MONAI/MONAILabel#1384]
**Describe the bug**
Monai label borrows the segment editor in the monai plug in. This is great and very convenient to have everything in the same plugin. However, it only lists 9 labels although there is plenty of room left for at another 9 labels or more. This was ok before but now with total segmentator 104 labels it is very annoying 

![image](https://user-images.githubusercontent.com/61221417/230703546-9e1e39f0-2d62-409e-9bcd-3b4b397594d8.png)

unlike the normal view for the editor plugin that shows over 20 labels before scrolling 
![image](https://user-images.githubusercontent.com/61221417/230703592-db50a975-28ca-438a-9f36-a6a7e3e55c82.png)

**ASK**
increase the number of labels that appears before scrolling from 9 to 20

**Comment by lassoan** [comment]
You can grab the bottom of thr segment list to expand. To navigate a long list of segments you can enable filter and search by right-clicking on the segment list and checking the `Show filter bar` option.

**Comment by AHarouni** [comment]
Oh great! I didn't notice that small ... that you can pull to extend. Thanks
