### ISSUE TITLE
Radiology Spleen Segmentation with OHIF does not parse studies/images correctly within the viewer

### ISSUE THREAD

**Issue by armstrongsam25** [Project-MONAI/MONAILabel#1393]
**Description**
Following this tutorial (https://github.com/Project-MONAI/tutorials/blob/main/monailabel/monailabel_radiology_spleen_segmentation_OHIF.ipynb) connects with OHIF initially, however, once images are loaded in Orthanc a row appears (image: [ohif](https://user-images.githubusercontent.com/16158892/230920554-889ce5f6-a222-498f-a6b1-37382d59696b.png)) that is not parsed correctly. Once this row is clicked, "Sorry, this page does not exist." appears. 

**Steps to reproduce the behavior:**
- Required Files: [docker-compose.txt (change to .yml)](https://github.com/Project-MONAI/MONAI/files/11191149/docker-compose.txt), [orthanc.txt (change to .json)](https://github.com/Project-MONAI/MONAI/files/11191152/orthanc.txt)

1. Run docker-compose up -d
2. Run bash inside of monai container
3. Follow instructions of the tutorial.

**Expected behavior**
Uploaded dicom images to Orthanc should parse and be viewable inside monai-OHIF.

**Screenshots**
[ohif](https://user-images.githubusercontent.com/16158892/230920554-889ce5f6-a222-498f-a6b1-37382d59696b.png)

**Environment**
Docker environment, default python environment that comes with container. 

**Additional context**
In the page that says "Sorry, this page does not exist", the url seems to be wrong "http://127.0.0.1:8000/ohif/viewer/:studyInstanceUIDs"

**Comment by SachidanandAlle** [comment]
some screenshots will be helpful to understand

**Comment by SachidanandAlle** [comment]
in your screenshot.. i don't see any studies listed..

**Comment by SachidanandAlle** [comment]
I guess you don't have the patient start date correctly configured.. OHIF works or filters based on startdate and current/today's data..

**Comment by armstrongsam25** [comment]
@SachidanandAlle This data is directly downloaded from the tutorial in step 3 (https://github.com/Project-MONAI/tutorials/blob/main/monailabel/monailabel_radiology_spleen_segmentation_OHIF.ipynb). I've also tried this with other DICOM image sets and experienced the same issue.

**Comment by SachidanandAlle** [comment]
Delete old data from orthanc.. and try to convert some nifti files to dicom as mentioned here: https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#converting-nifti-images-to-dicom

and then upload them

also check on the browser.. console logs.. what it is complaining about

**Comment by armstrongsam25** [comment]
@SachidanandAlle I have deleted, converted, and re-uploaded. Here is output in the console:

image: ![console_output](https://user-images.githubusercontent.com/16158892/230966885-22e0b5a6-c571-4b57-b908-a172753322c5.png)

text: with cornerstone debug true: [console_output.txt](https://github.com/Project-MONAI/MONAILabel/files/11192868/console_output.txt)

**Comment by diazandr3s** [comment]
Hi @armstrongsam25,

Can you please try with the MONAI Label weekly version in a fresh env?

`pip install monailabel-weekly`

Please let us know

**Comment by armstrongsam25** [comment]
@diazandr3s @SachidanandAlle  reinstalled with weekly. Same issue as above. The list has a row entry, but no information and "Invalid Date" is diplayed. I've been running Monai and Orthan in a docker container, but the weekly release doesn't have a docker image, so I ran orthan in docker and monai on my host machine. I would imagine that the communication between orthan and monai isn't being translated correctly. I will try to set up orthan and monai outside docker and try the newest RC release and report back.

[monai_error.txt](https://github.com/Project-MONAI/MONAILabel/files/11211844/monai_error.txt)

**Comment by armstrongsam25** [comment]
Running Orthan and Monai on host machine outside docker yields same error result.

**Comment by diazandr3s** [comment]
This is strange. 
Could you please try installing OHIF again (https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#development-setup) and upload more cases?

**Comment by armstrongsam25** [comment]
@diazandr3s rebuilt ohif, running monai on host machine, running orthan on host machine using wsl ubuntu. Still same error.

Attached is the output from the monai terminal when starting:
[monai_log.txt](https://github.com/Project-MONAI/MONAILabel/files/11213709/monai_log.txt)

**Comment by armstrongsam25** [comment]
@SachidanandAlle I was using Firefox. Switched to chrome. I can access both URLs in your comment and it returns some json data in both.

**Comment by diazandr3s** [comment]
Hi @armstrongsam25,

I don't see any issue from the logs you've shared. This is strange. 
Did you follow these instructions to install Orthanc? https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif#installing-orthanc-dicomweb

**Comment by SachidanandAlle** [comment]
Another possibility is date difference between orthanc and monai server.. are they running on same or different node..?

Actually you can fetch the similar url which I shared to you (dicomweb) from your browser network logs..

**Comment by armstrongsam25** [comment]
Sorry for the delay.
@diazandr3s Yes, when I installed orthan on the host machine I followed those directions. Also, when using Docker I used the 'jodogne/orthanc-plugins:1.11.0' image.

@SachidanandAlle They are on the same machine.  I re-ran my docker-compose file with 'jodogne/orthanc:1.12.0' and 'projectmonai/monailabel:latest', then tried to access the 2 urls above. The url `http://127.0.0.1:8042/dicom-web/studies?limit=25&offset=0&fuzzymatching=true&includefield=00081030,00080060` returns `{
   "HttpError" : "Not Found",
   "HttpStatus" : 404,
   "Message" : "Unknown resource",
   "Method" : "GET",
   "OrthancError" : "Unknown resource",
   "OrthancStatus" : 17,
   "Uri" : "/dicom-web/studies"
}`

Maybe this is the problem?

**Comment by armstrongsam25** [comment]
I tried this again on another, less restricted machine. And this tutorial works as intended. Note: It does not work with Firefox as it blocks a worker request. However, Chrome works.

I believe the problem was a too restrictive security policy on my machine.

**Comment by diazandr3s** [comment]
Thanks for reporting this, @armstrongsam25
