### ISSUE TITLE
Monaibundle lung nodule model error

### ISSUE THREAD

**Issue by junxiant** [Project-MONAI/MONAILabel#1430]
**Describe the bug**
Following the tutorial at: https://github.com/Project-MONAI/tutorials/blob/main/monailabel/monailabel_monaibundle_3dslicer_lung_nodule_detection.ipynb

Got an error after running the script 
```
monailabel start_server --app apps/monaibundle --studies datasets/Task06_Lung/imagesTr --conf models lung_nodule_ct_detection
```
TypeError: __init__() got an unexpected keyword argument 'use_list_output'
![image](https://github.com/Project-MONAI/MONAILabel/assets/25401067/506bf83a-5cda-47fa-b70f-bd705b0c8c4f)

**Environment**
monai == 1.1.0
monailabel == 0.6.0

![image](https://github.com/Project-MONAI/MONAILabel/assets/25401067/1cf11c96-fd68-4a17-988c-fc7c377bcf40)

**Additional context**
It seems like monai's network does not have use_list_output? Should i be downgrading monailabel to an older version?

![image](https://github.com/Project-MONAI/MONAILabel/assets/25401067/af6b03ed-8881-4722-b36f-e810dfbfee11)
![image](https://github.com/Project-MONAI/MONAILabel/assets/25401067/639a9412-c56d-4ac7-9291-9ef7d460ed4c)

In retinanet_network.py at:
.../site-packages/monai/apps/detection/networks/retinanet_network.py

![image](https://github.com/Project-MONAI/MONAILabel/assets/25401067/45d70c08-eda8-486e-88ab-c4d7f6131b03)

I have attached the full trace for the error. 
[error.txt](https://github.com/Project-MONAI/MONAILabel/files/11450068/error.txt)

**Comment by SachidanandAlle** [comment]
Upgrade monailabel to latest RC version

**Comment by junxiant** [comment]
Yeah that seems to have fixed the issue
