### ISSUE TITLE
How do I correctly downgrade CUDA driver and toolkit versions for MONAI Label installation in Anaconda?

### ISSUE THREAD

**Issue by mahdiskj** [Project-MONAI/MONAILabel#1456]
I am trying to install MONAI Label. For that, I need to install Pytorch and activate GPU first. I follow the official instructions to install them but Cuda is still not enabled in the specific anaconda env for MONAI.

system: windows 11 GPU: Nvidia GeForce RTX 3070

Here is what I first did:

1. install GPU driver version==531.61
2. install the Cuda toolkit from the website, locally on Windows. version==12.1
3. install CuDNN based on instructions

Then I realized MONAI Label and PyTorch are compatible with a lower version of CUDA. So I uninstalled the GPU driver and CUDA Toolkit from the Windows apps. Then installed the compatible versions as in the instructions on the website. (also changed the PATH in system variables)

BUT, when I check the version using 'nvidia-smi' I still get that the CUDA version is 12.1 and the GPU driver is 531.61. and 'torch.cuda.is_available())' is False.

Any advice on what I can do to resolve this issue? respectively downgrading the diver and the toolkit.

I would appreciate any ideas. Thank you in advance.

**Comment by hubutui** [comment]
1. `nvidia-smi` shows the newest cuda version which the driver is compatible to, not the current cuda version. You just need to make sure the cuda version shown by `nvidia-smi` is newer then the cuda version you'd like to use.
2. You don't need to install cuda and cudnn from the [cuda website](https://developer.nvidia.com/cuda-downloads) if you use anaconda. cuda and cudnn are available from nvidia channel from anaconda repo. These packages are installed as depends when you install pytorch by `conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia`.
