### ISSUE TITLE
the first `/` is missing if we use `Utils.getFileName` on Linux system

### ISSUE THREAD

**Issue by hubutui** [Project-MONAI/MONAILabel#1480]
The URI in qupath looks like `file:/home/username/myimage.png` on Linux, and `file:/C:/Users/username/Desktop/myimage.png` on Windows.So `Utils.getFileName` works for Windows but not Linux. We would get `home/username/myimage.png`. This could leads to bugs when we use the result return fromt this method, eg: https://github.com/Project-MONAI/MONAILabel/blob/d95c8a2ea6c8b9dd0bc6d9a06cd3bd8767df3da0/plugins/qupath/src/main/java/qupath/lib/extension/monailabel/commands/RunInference.java#L207-L208
quick fix, insert these lines:
```java
if (System.getProperty("os.name").toLowerCase().contains("linux")) {
	file = "/" + file;
}
```
just before https://github.com/Project-MONAI/MONAILabel/blob/d95c8a2ea6c8b9dd0bc6d9a06cd3bd8767df3da0/plugins/qupath/src/main/java/qupath/lib/extension/monailabel/Utils.java#L34

Maybe we should also check for MacOS or other non-Windows systems? How about this:
```java
if (!System.getProperty("os.name").toLowerCase().contains("windows")) {
	file = "/" + file;
}
```

**Comment by SachidanandAlle** [comment]
on linux it should be file://home/username/myimage.png

**Comment by hubutui** [comment]
So, it might be qupath's bug?

**Comment by SachidanandAlle** [comment]
Are you using relative path? If not then.. file uri should always start with file://.. similar to http://

**Comment by hubutui** [comment]
I don't think `home/username/myimage.png` looks like a relative path. I just open qupath, create a project, and Add images -> choose files, and select files, and finally click import button.

**Comment by SachidanandAlle** [comment]
https://en.wikipedia.org/wiki/File_URI_scheme

looks like you are using KDE env.. and hence its file:/etc/fstab

so in that case, the correct fix will be little different..

**Comment by hubutui** [comment]
I'm using GNOME, not KDE. There might some software from the kde applications, I'm not sure.

**Comment by SachidanandAlle** [comment]
can you help to try and fix this over windows/linux/mac.. 
currently its working for windows and ubuntu (gnome)

**Comment by hubutui** [comment]
We don't need to write `Utils.getFileName` at all, we could use:

```java
import qupath.lib.common.GeneralTools;

String imageFile GeneralTools.toPath(viewer.getImageData().getServer().getURIs().iterator().next()).toString();
// and get the file extension by
String extension = String.valueOf(GeneralTools.getExtension(imageFile));
```

**Comment by SachidanandAlle** [comment]
Can you please create a Pull request?

**Comment by hubutui** [comment]
![image](https://github.com/Project-MONAI/MONAILabel/assets/2948593/3e9ee781-fff5-48f3-b17d-462fef8e98ad)
I just check Ubuntu 23.04, it's `file:/myfile.png`.
