### ISSUE TITLE
Why the image is transposed (`np.moveaxis(data, 0, 1)`) when read by `LoadImagePatchd`

### ISSUE THREAD

**Issue by hubutui** [Project-MONAI/MONAILabel#1518]
I notice that the image is transposed when read by `LoadImagePatchd` at https://github.com/Project-MONAI/MONAILabel/blob/1d034726c655102cf612053842b1c45727966612/sample-apps/pathology/lib/transforms.py#L79

By default, pytorch input data use `(N, C, H, W)`. But it seems that we using `(N, C, W, H)` here. 

And later in `FindContoursd`, we transpose the prediction mask back again. https://github.com/Project-MONAI/MONAILabel/blob/1d034726c655102cf612053842b1c45727966612/monailabel/transform/post.py#L227

**Comment by tangy5** [comment]
HI @hubutui , did you observe any abnormal views in any viewers e.g., QuPath, CVAT, DSA. This is intentionally added according to some viewers, it might be different to the prior monailabel versions. We saw the orientation issue before < 0.6.

**Comment by hubutui** [comment]
No, it works fine. It's weird. I thought qupath also use the same coordinate system, (0, 0) on the top-left, and x-axis grows to the right, y-axis grows down.
Now, I would like to add my custom hovernet model. Should I also follow this? transpose the input image before feeding it to the model, and tranpose the prediciton mask when getting the contours.

**Comment by hubutui** [comment]
the instance_info dict created by monailabel hovernet use:
```python
"contour": [[y1, x1], ...],
"centroid": [y, x],
"bounding_box": [x1, x2, y1, y2]
```
Correct me if I don't understand it right.

**Comment by hubutui** [comment]
ok, since the image is tranposed, when monailabel calculate the instance_info, the coordinate  x&y is also swapped.
