### ISSUE TITLE
compatibility with MONAI v0.6.0 (15/July)

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAILabel#152]
**Is your feature request related to a problem? Please describe.**
MONAI v0.6.0rc1 is available:
https://pypi.org/project/monai/0.6.0rc1/

this ticket tracks any issues with the new version of MONAI and verifies that the new features are usable:
- load MMAR pretrained https://github.com/Project-MONAI/MONAI/blob/0.6.0rc1/monai/apps/mmars/mmars.py#L204-L207
- dynamic datalist
there are breaking changes since 0.5.x, we'll release demos https://github.com/Project-MONAI/MONAI/issues/2402

cc @Nic-Ma @yiheng-wang-nv

**Comment by SachidanandAlle** [comment]
Lets verify all basic functionality using 0.6 version..
lets not implement anything for mmar apis (we continue using download apis from monai to download pretrained models)

we will revisit to use the new apis in next version of monailabel

**Comment by diazandr3s** [comment]
I found this error when using monai==0.6.0rc1

> GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
> The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70.
> If you want to use the GeForce RTX 3090 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

Apparently, it is something related to my GPU card (GeForce 3090). Solved this problem by running:

> conda install pytorch torchvision torchaudio cudatoolkit=11.0 -c pytorch  

Taken from https://github.com/pytorch/pytorch/issues/46794 


However, I still get the error when loading a pre-trained model:

> Traceback (most recent call last):
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/uvicorn/protocols/http/h11_impl.py", line 396, in run_asgi
>     result = await app(self.scope, self.receive, self.send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
>     return await self.app(scope, receive, send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/fastapi/applications.py", line 201, in __call__
>     await super().__call__(scope, receive, send)  # pragma: no cover
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/applications.py", line 112, in __call__
>     await self.middleware_stack(scope, receive, send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 181, in __call__
>     raise exc from None
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/middleware/errors.py", line 159, in __call__
>     await self.app(scope, receive, _send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/exceptions.py", line 82, in __call__
>     raise exc from None
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/exceptions.py", line 71, in __call__
>     await self.app(scope, receive, sender)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/routing.py", line 580, in __call__
>     await route.handle(scope, receive, send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/routing.py", line 241, in handle
>     await self.app(scope, receive, send)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/starlette/routing.py", line 52, in app
>     response = await func(request)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/fastapi/routing.py", line 215, in app
>     dependant=dependant, values=values, is_coroutine=is_coroutine
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
>     return await dependant.call(**values)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/endpoints/infer.py", line 129, in run_inference
>     result = instance.infer(request)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/app.py", line 124, in infer
>     result_file_name, result_json = task(request)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/infer.py", line 198, in __call__
>     data = self.run_inferer(data, device=device)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/infer.py", line 300, in run_inferer
>     network.load_state_dict(model_state_dict)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
>     self.__class__.__name__, "\n\t".join(error_msgs)))
> RuntimeError: Error(s) in loading state_dict for DynUNet:
> 	Unexpected key(s) in state_dict: "input_block.norm1.weight", "input_block.norm1.bias", "input_block.norm2.weight", "input_block.norm2.bias", "input_block.norm3.weight", "input_block.norm3.bias", "downsamples.0.norm1.weight", "downsamples.0.norm1.bias", "downsamples.0.norm2.weight", "downsamples.0.norm2.bias", "downsamples.0.norm3.weight", "downsamples.0.norm3.bias", "downsamples.1.norm1.weight", "downsamples.1.norm1.bias", "downsamples.1.norm2.weight", "downsamples.1.norm2.bias", "downsamples.1.norm3.weight", "downsamples.1.norm3.bias", "downsamples.2.norm1.weight", "downsamples.2.norm1.bias", "downsamples.2.norm2.weight", "downsamples.2.norm2.bias", "downsamples.2.norm3.weight", "downsamples.2.norm3.bias", "downsamples.3.norm1.weight", "downsamples.3.norm1.bias", "downsamples.3.norm2.weight", "downsamples.3.norm2.bias", "downsamples.3.norm3.weight", "downsamples.3.norm3.bias", "bottleneck.norm1.weight", "bottleneck.norm1.bias", "bottleneck.norm2.weight", "bottleneck.norm2.bias", "bottleneck.norm3.weight", "bottleneck.norm3.bias", "upsamples.0.conv_block.norm1.weight", "upsamples.0.conv_block.norm1.bias", "upsamples.0.conv_block.norm2.weight", "upsamples.0.conv_block.norm2.bias", "upsamples.1.conv_block.norm1.weight", "upsamples.1.conv_block.norm1.bias", "upsamples.1.conv_block.norm2.weight", "upsamples.1.conv_block.norm2.bias", "upsamples.2.conv_block.norm1.weight", "upsamples.2.conv_block.norm1.bias", "upsamples.2.conv_block.norm2.weight", "upsamples.2.conv_block.norm2.bias", "upsamples.3.conv_block.norm1.weight", "upsamples.3.conv_block.norm1.bias", "upsamples.3.conv_block.norm2.weight", "upsamples.3.conv_block.norm2.bias", "upsamples.4.conv_block.norm1.weight", "upsamples.4.conv_block.norm1.bias", "upsamples.4.conv_block.norm2.weight", "upsamples.4.conv_block.norm2.bias", "skip_layers.downsample.norm1.weight", "skip_layers.downsample.norm1.bias", "skip_layers.downsample.norm2.weight", "skip_layers.downsample.norm2.bias", "skip_layers.downsample.norm3.weight", "skip_layers.downsample.norm3.bias", "skip_layers.upsample.conv_block.norm1.weight", "skip_layers.upsample.conv_block.norm1.bias", "skip_layers.upsample.conv_block.norm2.weight", "skip_layers.upsample.conv_block.norm2.bias", "skip_layers.next_layer.downsample.norm1.weight", "skip_layers.next_layer.downsample.norm1.bias", "skip_layers.next_layer.downsample.norm2.weight", "skip_layers.next_layer.downsample.norm2.bias", "skip_layers.next_layer.downsample.norm3.weight", "skip_layers.next_layer.downsample.norm3.bias", "skip_layers.next_layer.upsample.conv_block.norm1.weight", "skip_layers.next_layer.upsample.conv_block.norm1.bias", "skip_layers.next_layer.upsample.conv_block.norm2.weight", "skip_layers.next_layer.upsample.conv_block.norm2.bias", "skip_layers.next_layer.next_layer.downsample.norm1.weight", "skip_layers.next_layer.next_layer.downsample.norm1.bias", "skip_layers.next_layer.next_layer.downsample.norm2.weight", "skip_layers.next_layer.next_layer.downsample.norm2.bias", "skip_layers.next_layer.next_layer.downsample.norm3.weight", "skip_layers.next_layer.next_layer.downsample.norm3.bias", "skip_layers.next_layer.next_layer.upsample.conv_block.norm1.weight", "skip_layers.next_layer.next_layer.upsample.conv_block.norm1.bias", "skip_layers.next_layer.next_layer.upsample.conv_block.norm2.weight", "skip_layers.next_layer.next_layer.upsample.conv_block.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.downsample.norm1.weight", "skip_layers.next_layer.next_layer.next_layer.downsample.norm1.bias", "skip_layers.next_layer.next_layer.next_layer.downsample.norm2.weight", "skip_layers.next_layer.next_layer.next_layer.downsample.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.downsample.norm3.weight", "skip_layers.next_layer.next_layer.next_layer.downsample.norm3.bias", "skip_layers.next_layer.next_layer.next_layer.upsample.conv_block.norm1.weight", "skip_layers.next_layer.next_layer.next_layer.upsample.conv_block.norm1.bias", "skip_layers.next_layer.next_layer.next_layer.upsample.conv_block.norm2.weight", "skip_layers.next_layer.next_layer.next_layer.upsample.conv_block.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm1.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm1.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm2.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm3.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.downsample.norm3.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.upsample.conv_block.norm1.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.upsample.conv_block.norm1.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.upsample.conv_block.norm2.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.upsample.conv_block.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm1.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm1.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm2.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm2.bias", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm3.weight", "skip_layers.next_layer.next_layer.next_layer.next_layer.next_layer.norm3.bias".


 @SachidanandAlle @wyli

**Comment by wyli** [comment]
@yiheng-wang-nv  any idea?

**Comment by Nic-Ma** [comment]
Hi @diazandr3s ,

Thanks for your issue report.
Are you using the **latest MONAI nightly docker**? Or just install MONAI 0.6RC in your env?

Thanks.

**Comment by diazandr3s** [comment]
Hi @Nic-Ma, thanks for your help with this. I installed monai==0.6.0rc1 in a new virtual env I created to test it.

**Comment by wyli** [comment]
perhaps it's the model you trained with v0.5.3 is not compatible with v0.6 because of this change https://github.com/Project-MONAI/MONAI/pull/2166, see also https://github.com/Project-MONAI/MONAI/issues/2158

**Comment by diazandr3s** [comment]
That might be the reason. I just tried other Apps that don't use the DynUnet and they seem to work. Is there a way to make those weights compatible with the new version? or should I just retrain the models that use DynUnet?

**Comment by wyli** [comment]
retraining would be the easiest... if you really couldn't retrain it, there is a `copy_model_state` function, to load previous checkpoint into a new network instance with an additional variable name mapping option:
https://github.com/Project-MONAI/MONAI/blob/42a11259aa8a24d5e83d3b1a493c5a6102282d1f/monai/networks/utils.py#L318-L325

**Comment by diazandr3s** [comment]
I tried to retrain one model and I've got this error

> Traceback (most recent call last):
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 89, in <module>
>     run_main()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 74, in run_main
>     result = a.train(request)
>   File "/home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_left_atrium/main.py", line 113, in train
>     return task()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 217, in __call__
>     self.trainer().run()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 209, in trainer
>     train_handlers=self.train_handlers(),
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/train/basic_train.py", line 170, in train_handlers
>     e = self.evaluator()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 192, in evaluator
>     event_names=self.event_names(),
> TypeError: __init__() got an unexpected keyword argument 'post_transform'

Will investigate more whether this is related to MONAI evaluator or MONAI Label endpoints.

**Comment by wyli** [comment]
@yiheng-wang-nv is working on the tutorials for the new API, perhaps this ongoing fix (acceleration/distributed_training/unet_evaluation_workflows.py) could be a reference: https://github.com/Project-MONAI/tutorials/pull/246/files#diff-dfe247875ecbd901b66011f0350feca21969f5fdca6eac28a8c2f91329b83b2b

**Comment by diazandr3s** [comment]
Superb! 
After testing the previous version of MONAI, I think the last error I've got is related to the MONAI version.

**Comment by SachidanandAlle** [comment]
> retraining would be the easiest... if you really couldn't retrain it, there is a `copy_model_state` function, to load previous checkpoint into a new network instance with an additional variable name mapping option:
> https://github.com/Project-MONAI/MONAI/blob/42a11259aa8a24d5e83d3b1a493c5a6102282d1f/monai/networks/utils.py#L318-L325

This utility is useful.. but this key issue is happening for all networks or only for DynamicUNET?
If it's only DynamicUNET, then can you guys help @diazandr3s to know the old set of keys to load and rename them as..?
Or it's just additional keyprefix is enough?

**Comment by diazandr3s** [comment]
@wyli Thanks for solving the incompatibility issue with DynUNet. Inference works as before!! :)
However, I've got another issue when starting the training process. 

> Traceback (most recent call last):
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 89, in <module>
>     run_main()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/others/app_utils.py", line 74, in run_main
>     result = a.train(request)
>   File "/home/adp20local/Downloads/MONAILabel/sample-apps/deepedit_spleen/main.py", line 112, in train
>     return task()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 217, in __call__
>     self.trainer().run()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 209, in trainer
>     train_handlers=self.train_handlers(),
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/utils/train/basic_train.py", line 170, in train_handlers
>     e = self.evaluator()
>   File "/home/adp20local/Downloads/MONAILabel/monailabel/interfaces/tasks/train.py", line 192, in evaluator
>     event_names=self.event_names(),
> TypeError: __init__() got an unexpected keyword argument 'post_transform'
> 

I think it is something related to the **SupervisedEvaluator**

**Comment by diazandr3s** [comment]
Yes, I think that's the issue. In the new version of MONAI, post_transforms is now called postprocessing. See here: https://github.com/Project-MONAI/MONAI/blob/dev/monai/engines/evaluator.py#L188

**Comment by diazandr3s** [comment]
I changed the argument and got the following error :/

>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/trainer.py", line 56, in run
>     super().run()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/workflow.py", line 242, in run
>     super().run(data=self.data_loader, max_epochs=self.state.max_epochs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 701, in run
>     return self._internal_run()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 774, in _internal_run
>     self._handle_exception(e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
>     self._fire_event(Events.EXCEPTION_RAISED, e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
>     func(*first, *(event_args + others), **kwargs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
>     raise e
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 744, in _internal_run
>     time_taken = self._run_once_on_dataset()
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 848, in _run_once_on_dataset
>     self._handle_exception(e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 467, in _handle_exception
>     self._fire_event(Events.EXCEPTION_RAISED, e)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
>     func(*first, *(event_args + others), **kwargs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/handlers/stats_handler.py", line 148, in exception_raised
>     raise e
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 834, in _run_once_on_dataset
>     self.state.output = self._process_function(self, self.state.batch)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/apps/deepgrow/interaction.py", line 79, in __call__
>     return engine._iteration(engine, batchdata)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/trainer.py", line 201, in _iteration
>     engine.fire_event(IterationEvents.MODEL_COMPLETED)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 448, in fire_event
>     return self._fire_event(event_name)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/ignite/engine/engine.py", line 424, in _fire_event
>     func(*first, *(event_args + others), **kwargs)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/engines/workflow.py", line 186, in _decollate_data
>     engine.state.batch = decollate_batch(rep_scalar_to_batch(engine.state.batch), detach=True)
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/data/utils.py", line 398, in rep_scalar_to_batch
>     if decollate_batch(v, detach=False) == v and not isinstance(v, list):
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/data/utils.py", line 369, in decollate_batch
>     return [list(item) for item in zip(*(decollate_batch(b, detach) for b in batch))]
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/data/utils.py", line 369, in <genexpr>
>     return [list(item) for item in zip(*(decollate_batch(b, detach) for b in batch))]
>   File "/home/adp20local/anaconda3/envs/monai06_env/lib/python3.6/site-packages/monai/data/utils.py", line 357, in decollate_batch
>     return [dict(zip(_dict_list, item)) for item in zip(*_dict_list.values())]
> TypeError: zip argument #2 must support iteration
> 

Not sure what could be the issue here.

**Comment by wyli** [comment]
will https://github.com/Project-MONAI/MONAI/pull/2530 address the above issue @Nic-Ma ?

**Comment by Nic-Ma** [comment]
Hi @wyli ,

Yes, I think so, @yiheng-wang-nv will also update DeepGrow tutorial based on the PR.
Thanks.

**Comment by wyli** [comment]
thanks all, looks like we've addressed this ticket. please help double-check, MONAI v0.6 is scheduled for release within this week. After that, any further changes will be in 0.6.x hotfixes.

**Comment by diazandr3s** [comment]
Many thanks to all!!
