### ISSUE TITLE
Multi-Label segmentation support

### ISSUE THREAD

**Issue by che85** [Project-MONAI/MONAILabel#153]
**Is your feature request related to a problem? Please describe.**
MONAILabel V1 only supports single-label segmentation. 

In our case, we need to be able to segment multiple structures at once. 

For example, the Tricuspid Valve consists of three leaflets (three segments) that restrict each other's boundaries.

A single label segmentation (all leaflets merged) would not be helpful since this can be achieved via simple thresholding without using any AI.

Our pre-trained model takes into consideration every leaflet's boundary which results in a 4 channel output (background, anterior, posterior, septal) without any overlapping structures.

**Additional context**
https://github.com/JolleyLabCHOP/DeepHeart/issues/1
https://github.com/JolleyLabCHOP/DeepHeart/issues/2

**Comment by SachidanandAlle** [comment]
I believe you can train a multi-label segmentation model.. there should not be a blocker for that..
Have added a sample liver+tumor app for reference..

https://github.com/Project-MONAI/MONAILabel/pull/157

**Comment by SachidanandAlle** [comment]
For now, I believe we can close this issue.  Feel free to reopen if needed.
