### ISSUE TITLE
OHIF V3 MONAI Plugin: Clear Point Fix

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAILabel#1554]
The button sometimes will crash OHIF V3 viewer.

let track using MONAI label Github

@sedghi @diazandr3s @SachidanandAlle

**Comment by sedghi** [comment]
This is fixed in master

**Comment by tangy5** [comment]
HI @sedghi , this is great, thanks for this and the action in such a short time! Can you help rebase feat/monai-label with Master branch, so that monai team can use this fix? Or what will be the best way to merge the fixes to feat/monai-label. 

Thanks so much !
