### ISSUE TITLE
OHIF V3 MONAI Plugin: Segmentation Panel | Add ToolBox and scroll bar

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAILabel#1555]
1. We can render ToolBox in the PanelSegmenttaion.tsx, currently it will not load. 
2. users may user more than 100 organs and targets, the segments table will overflow, and we can add a scroll bar to access all entries. 

@sedghi @diazandr3s @SachidanandAlle 

Screenshot of current segmentation panel:
![Screenshot from 2023-10-05 17-53-59](https://github.com/Project-MONAI/MONAILabel/assets/58751975/14dc2dfe-ced3-4a91-b2ac-de6151e0bd57)

**Comment by sedghi** [comment]
This is fixed in master

**Comment by tangy5** [comment]
Hi @sedghi , one question. How could we load the Toolbox (brush, erase) in the segmentation panel, I can't see where user can open this Toolbox for manual annotation. 
The scroll bar is working perfectly. Thanks!
