### ISSUE TITLE
MONAI v1.3 release preparation-- MONAILabel sync

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAILabel#1557]
- review deprecated API since 1.3 https://github.com/Project-MONAI/MONAI/issues/7018
- bundle starting from local directory https://github.com/Project-MONAI/MONAILabel/issues/1490
- support of multiple config https://github.com/Project-MONAI/MONAILabel/issues/1549
- caching github requests https://github.com/Project-MONAI/MONAI/issues/6833#issuecomment-1717626732
- (review segment template https://github.com/ericspod/model-zoo/tree/segment_template/models/segmentation_template)

**Comment by matt3o** [comment]
"[Deprecated] `AddChannel` and `AsChannelFirst` in favor of `EnsureChannelFirst`"  breaks the radiology sample-app as a lot of apps there are using both transforms.
I quickly tried fixing that locally by replacing everything with `EnsureChannelFirst` and `EnsureChannelFirstd`, however the test_epistemic.py unittest fails with "ValueError: Metadata not available and channel_dim=None, EnsureChannelFirst is not in use."
I tried to find another transform similar to AddChannel, like UnsqeezeDim but couldn't find any.

**Comment by wyli** [comment]
fyi the related tutorial updates show potential solutions: https://github.com/Project-MONAI/tutorials/pull/1527

**Comment by SachidanandAlle** [comment]
Some of the models used in examples for MONAI Label break due to required changes in the infer/train configs.. they are still using delete arguments/transforms

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/1560

**Comment by wyli** [comment]
thanks, v1.3 is now available, please create new ticket on further issues
