### ISSUE TITLE
Start populating Wiki page with project overview and basic use cases (9/July)

### ISSUE THREAD

**Issue by aihsani** [Project-MONAI/MONAILabel#16]
- Add project overview section: executive summary
- High-level description of use-cases
  - What is the flow from a server with no available models inference (e.g. static spleen segmentation) or annotation (e.g. deepedit)
  - What is the flow when inference models and annotation (deepedit) models are available

**Comment by SachidanandAlle** [comment]
We need to get it reviewed by Product (before we close this issue)

**Comment by SachidanandAlle** [comment]
If it's all done.. possibly @pdogra89  can review and close this issue

**Comment by SachidanandAlle** [comment]
Any updates on this?

**Comment by finalelement** [comment]
Created and updated a page for Deepgrow wiki. A Figure needs to be added for it. 
Same for Active Learning

**Comment by diazandr3s** [comment]
I added DeepEdit description, some FAQs, and also updated the validation plots for both the left atrium and spleen. Both reaching more than 0.90 in Dice score

**Comment by finalelement** [comment]
Added two posts. 

1.) How to create a fixed validation split?
2.) Tutorial: How to create your own sample Deep-grow App

**Comment by finalelement** [comment]
Figures added. Ready for review. Get someone to review @SachidanandAlle @aihsani

These 4 posts from my side were added to the wiki:
1.) DeepGrow Explanation with figure
2.) Active learning explanation with figure
3.) How to create a DeepGrow sample-app from scratch
4.) How to have a fixed validation split during experiments

**Comment by finalelement** [comment]
After discussion below is the updated checklist at my end:

- Redo Tutorial using experimental app, remove code line numbers.
- Edit FAQ
- Add Deepgrow Performance Numbers to Usecases page

**Comment by finalelement** [comment]
Above listed stuff is done.
