### ISSUE TITLE
Show 3D not available in MONAILabel Reviewer 

### ISSUE THREAD

**Issue by bkonkva** [Project-MONAI/MONAILabel#1624]
I'm running the monailabel slicer plugin on some segmented data. I open the plugin, switch to reviewer mode, provide a reviewer name and connect to the server. My first image loads up fine, the segmentation masks load as well (labels have changed from the names I provided to Segment_1, Segment_2,.... but that's a minor issue). They main issue I'm hitting is that "Show 3D" in the editor is greyed out. With "start label edit" most segment editor options appear, but the "Show 3D" remains greyed. A quick workaround I've discovered is that if I add and then immediately remove a label, "Show 3D" becomes clickable and works fine.

**Comment by rcremese** [comment]
This is indeed an annoying behaviour that I face.
I would be interested to work on it as I have a project that might use MONAILabel Reviewer, but I'm not sure if it's even possible to fix. To the best of my knowledge, the "show 3D" button is integrated to the "segment editor" window and the reason for it not to be accessible is that you don't want a reviewer to unexpectedly remove or add segments to your label map.
Moreover, I'm not sure MONAILabel Reviewer plugin is still maintained.

**Comment by diazandr3s** [comment]
Hi,

Is this issue still present in the latest Slicer version? Please provide a screenshot or MONAI Label server logs. Did you follow the instructions in the MONAILabelReviewer plugin documentation?

https://github.com/Project-MONAI/MONAILabel/tree/5d2ae1fbb770040ef1e428b8e7b0312c6bbead75/plugins/slicer/MONAILabelReviewer

**Comment by lassoan** [comment]
I was able to reproduce the issue. This is a small bug in Slicer that the state of the button is not updating do to some missing events. It would be easy to add a workaround for this in the Slicer MONAILabel plugin, but it would be nicer to fix this in Slicer core. I'll get it fixed soon in Slicer core.

I'll investigate this a bit more and report back here.

**Comment by lassoan** [comment]
I've submitted a [pull request](https://github.com/Slicer/Slicer/pull/7962) that fixes the issue in Slicer. The fix will be available in Slicer Preview Release in about 2 days.

**Comment by lassoan** [comment]
The pull request in Slicer got merged, so the Slicer Preview Release that you download tomorrow or later should work well.

**Comment by diazandr3s** [comment]
Amazing! Thanks for checking this out and solving it, @lassoan
