### ISSUE TITLE
Import Error while starting server /apps/radiology/lib/infers/deepgrow.py"

### ISSUE THREAD

**Issue by tarek212** [Project-MONAI/MONAILabel#1640]
**File "/home/tarek/apps/radiology/main.py", line 19, in <module>
    from lib.infers.deepgrow_pipeline import InferDeepgrowPipeline
  File "/home/tarek/apps/radiology/lib/infers/__init__.py", line 13, in <module>
    from .deepgrow import Deepgrow
  File "/home/tarek/apps/radiology/lib/infers/deepgrow.py", line 23, in <module>**  
    from monai.transforms import (
ImportError: cannot import name 'AddChanneld' from 'monai.transforms' (/home/tarek/.virtualenvs/brain/lib/python3.10/site-packages/monai/transforms/__init__.py)

[2024-02-27 17:19:10,637] [420288] [MainThread] [ERROR] (uvicorn.error:59) - Application startup failed. Exiting.

The import error not coming from anything but the radiology app when starting a server and i opened the deepgrow.py file that is downloaded on my computer i found that it wants to import AddChanneld and as far as i know this is deprecated in new versions

**Comment by diazandr3s** [comment]
Hi @tarek212,

Thanks for reporting this.

Are you using the latest MONAI Label version? Could you please share the version you used for this?
From the error logs, it seems an old MONAI Label version.

Let us know,

**Comment by tarek212** [comment]
thanks for the reply and sorry for late reply
this is the version of monialabel i have
MONAILabel version: 0.5.dev2340
Numpy version: 1.24.3
Pytorch version: 2.0.0+cu117

**Comment by diazandr3s** [comment]
Hi @tarek212,

Thanks for the update.
I recommend using the latest MONAI Label version (0.8.1).
Please let us know how that goes.

I'm closing the issue now.
