### ISSUE TITLE
vascular distortion Over compression

### ISSUE THREAD

**Issue by mengab1** [Project-MONAI/MONAILabel#1658]
vascular distortion
laber Over compression
<img width="870" alt="截屏2024-03-21 23 17 29" src="https://github.com/Project-MONAI/MONAILabel/assets/35659832/c1337ea2-0570-4cd3-90bb-86f2c008efdc">

**Comment by diazandr3s** [comment]
Hi @mengab1,

I'm not sure I'm understanding the issue here.
Could you please provide more details?

Closing issue. Feel free to open a discussion if needed.
