### ISSUE TITLE
http://127.0.0.1:8000/ohif，There is no model to choose 

### ISSUE THREAD

**Issue by 865979216** [Project-MONAI/MONAILabel#1676]
**Please use MONAILabel's Discussions tab**
For questions relating to MONAILabel usage, please do not create an issue.

Instead, use [MONAI's GitHub Discussions tab](https://github.com/Project-MONAI/MONAILabel/discussions). This can be found next to Issues and Pull Requests along the top of our repository.
![image](https://github.com/Project-MONAI/MONAILabel/assets/97671318/583002fa-a1d6-4a2f-807f-a52de8406696)
![image](https://github.com/Project-MONAI/MONAILabel/assets/97671318/02ddf7f8-acb7-4222-9900-3b2ef3832d7d)
monailabel start_server --app apps/radiology --studies http://127.0.0.1:8042/dicom-web --conf models segmentation
![image](https://github.com/Project-MONAI/MONAILabel/assets/97671318/328980fa-c547-491c-9a9d-89205c749a67)

**Comment by Aurora-God** [comment]
Fill in the real address of Monailabel in the input box of the server above, and then click on the right to refresh

**Comment by Aurora-God** [comment]
![image](https://github.com/Project-MONAI/MONAILabel/assets/112399428/6287fe26-9f42-494a-be16-7b921fb56a03)

**Comment by Aurora-God** [comment]
![image](https://github.com/Project-MONAI/MONAILabel/assets/112399428/03c9d0d9-d332-4fb1-94e4-92a1af19c6e8)

**Comment by 865979216** [comment]
> ![图像](https://private-user-images.githubusercontent.com/112399428/337073487-03c9d0d9-d332-4fb1-94e4-92a1af19c6e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM3MjAsIm5iZiI6MTcxODc4MzQyMCwicGF0aCI6Ii8xMTIzOTk0MjgvMzM3MDczNDg3LTAzYzlkMGQ5LWQzMzItNGZiMS05NGU0LTkyYTFhZjE5YzZlOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxOVQwNzUwMjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMjlkNjNmYjAwN2FkYzk2NTIyMjE2OGM3MzYwNjdhZjYzZmU5Y2U1NDUyOWE4MjFlZWEyNzMzOWM0YjRhYTg1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Pt3AFvBiX45tNrynHolMz6euzdSJ0YIJzYogrzuSbgI)

You are right，it is localhost:8042
