### ISSUE TITLE
Docker build fails

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#1710]
https://github.com/Project-MONAI/MONAILabel/actions/workflows/docker.yml

![image](https://github.com/Project-MONAI/MONAILabel/assets/7339051/2c756d51-5cca-4d77-a2ae-7e35f07c9ecb)

**Comment by diazandr3s** [comment]
Hi @YanxuanLiu,

I was wondering whether you could comment on this issue? Is that something you could help?

Thanks in advance,

**Comment by YanxuanLiu** [comment]
You can try following solutions:

1. Remove unnecessary dependencies during building docker image.
2. Clean up caches and intermediate product
3. If you cannot reduce space requirement after these efforts, move the pipeline to blossom

**Comment by SachidanandAlle** [comment]
Fixed it by switching to basic ubuntu docker for monailabel.
