### ISSUE TITLE
Run monai label in Ubuntu 22.04 but may using wrong PYTHONPATH

### ISSUE THREAD

**Issue by suzhou-gumi** [Project-MONAI/MONAILabel#1735]
Hello!

since i run monai label in Ubuntu 22.04, when run command 'monailabel --help', i see monailabel using **wrong PYTHONPATH**, so i echo the right PYTHONPATH in to _.bashrc_, after that , the PYTHONPATH has some prefix, it still wrong. 

![Screenshot from 2024-08-19 18-48-31](https://github.com/user-attachments/assets/92a6f178-e2e8-4582-8249-89414992ed95)
![Screenshot from 2024-08-19 18-30-50](https://github.com/user-attachments/assets/9330c799-bbc0-4278-b2aa-a44335446288)

================================
Printing MONAI config...
================================
MONAI version: 1.3.2
Numpy version: 1.26.4
Pytorch version: 2.4.0+cu121
MONAI flags: HAS_EXT = False, USE_COMPILED = False, USE_META_DICT = False
MONAI rev id: 59a7211070538586369afd4a01eca0a7fe2e742e
MONAI __file__: /home/<username>/.local/lib/python3.10/site-packages/monai/__init__.py

Optional dependencies:
Pytorch Ignite version: 0.4.11
ITK version: 5.4.0
Nibabel version: 5.2.1
scikit-image version: 0.24.0
scipy version: 1.14.0
Pillow version: 10.4.0
Tensorboard version: 2.17.1
gdown version: 5.2.0
TorchVision version: 0.19.0+cu121
tqdm version: 4.66.5
lmdb version: 1.5.1
psutil version: 6.0.0
pandas version: 2.2.2
einops version: 0.7.0
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: 2.15.1
pynrrd version: 1.0.0
clearml version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies

================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 22.04.4 LTS
Platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.35
Processor: x86_64
Machine: x86_64
Python version: 3.10.12
Process name: pt_main_thread
Command: ['python3', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [4.7, 4.4, 4.1, 3.8, 4.4, 3.5, 4.1, 3.8, 4.4, 3.8, 47.5, 50.2]
CPU freq. (MHz): 952
Load avg. in last 1, 5, 15 mins (%): [3.4, 2.7, 2.5]
Disk usage (%): 7.2
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 15.0
Available memory (GB): 10.5
Used memory (GB): 4.0

================================
Printing GPU config...
================================
Num GPUs: 0
Has CUDA: False
cuDNN enabled: True
NVIDIA_TF32_OVERRIDE: None
TORCH_ALLOW_TF32_CUBLAS_OVERRIDE: None
cuDNN version: 90100

help someone can help me, thank you very much!

**Comment by diazandr3s** [comment]
Hi @suzhou-gumi,

I highly recommend you creating a Python virtual enviroment and installing the MONAI Label package

 `pip install -U monailabel`

From the first print screen you've shared, I see you don't have a Python env activated.

Please follow these instructions: https://github.com/Project-MONAI/MONAILabel?tab=readme-ov-file#step-1-installation
