### ISSUE TITLE
CI/CD - Improve Code coverage

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#193]
- Code coverage to reach 80-90%
- Include everything.  Enable code coverage for template/sample apps

**Comment by aihsani** [comment]
Code coverage revised to 70% for v0.2.0, including GPU tests

**Comment by aihsani** [comment]
With GPU tests we're at 70%: https://dev.azure.com/projectmonai/monai-label/_build/results?buildId=413&view=logs&j=32b24e60-4a04-5732-fd3a-4264701b5b88&t=72400ca3-2eb1-50ce-a1cd-8b736d7dc380
