### ISSUE TITLE
AttributeError: module 'sip' has no attribute 'setapi'

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#199]
The following error message is encountered following monailabel installation on a windows machine: AttributeError: module 'sip' has no attribute 'setapi'

To reproduce: monailabel --help

Cause: incomptible matplotlib version loaded when running pip install -r requirement.txt

Fix: downgrading to matplotlib==3.2 (see https://stackoverflow.com/questions/64291087/matplotlib-module-sip-has-no-attribute-setapi)

**Comment by SachidanandAlle** [comment]
This is a general python env issue.  There can always be conflicting python package already installed by user.
The general recommendation is always to use virtual env.

https://docs.python.org/3/tutorial/venv.html

**Comment by pritesh-mehta** [comment]
I did use a virtual env. When I run the requirements file, I see that matplotlib==3.3.4 is installed due to some dependency, rather than matplotlib==3.4.2 which is the latest version on PyPI. This may be some specific problem that exists on my system only (even when I try pip install matplotlib==3.4.2, it says "could not find a version that satisfied the requirement"). It's possible that the issue I highlight above re sip module, does not occur if matplotlib==3.4.2 is successfully installed. If you do not experience the same issue, maybe this issue can be closed.
