### ISSUE TITLE
AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#200]
Error encountered when running monailabel inference on a windows machine: AssertionError: Torch not compiled with CUDA enabled

To reproduce: click button "Next Sample" in 3DSlicer

Cause: CPU version of PyTorch installed when running pip install -r requirements.txt

Fix: pip3 install torch==1.9.0+cu111 torchvision==0.10.0+cu111 torchaudio===0.9.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by SachidanandAlle** [comment]
For windows, the prerequisites are mentioned over here... please follow the same.
https://docs.monai.io/projects/label/en/latest/installation.html#prerequisites

Also have you tried to install monai on windows.  It should be same behavior for monai and monailabel.

**Comment by pritesh-mehta** [comment]
Thanks. I did not look at the link you provided before I installed. The link does indeed contain the information I needed. Can it be made clearer in the monailabel readme, that windows users should refer to the link for installation instructions. Currently it is not obvious:

![image](https://user-images.githubusercontent.com/33317215/125601173-f8593cf7-e617-4ffb-9de6-ebe92a72b6b3.png)
