### ISSUE TITLE
AttributeError: module 'os' has no attribute 'unsetenv'

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#201]
On exiting monailabel start_server on a Windows machine, get error: AttributeError: module 'os' has no attribute 'unsetenv'

To reproduce: monailabel start_server..., followed by ctrl + c 

Cause: monailabel/main.py, line 295

Fix: Unclear. Google search indicates that os module does not have a unsetenv attribute in Windows.

**Comment by SachidanandAlle** [comment]
You must have installed python from Windows play store which is different than regular python package from https://www.python.org/downloads/

https://docs.monai.io/projects/label/en/latest/installation.html#prerequisites
The instructions in above document mention to download/install python from https://www.python.org/downloads/

For example in my windows env:
![image](https://user-images.githubusercontent.com/7339051/125577415-804fc3f9-4507-4d1b-a4a3-095f746d07f1.png)

**Comment by pritesh-mehta** [comment]
Ok, so cause of issue seems to be python versions. I was using Python 3.6.4. The issue has been fixed in Python 3.9: https://bugs.python.org/issue39413.
