### ISSUE TITLE
Image without segmentation overlay in 3DSlicer interface

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#202]
It would be useful to see the image without a segmentation overlay in the 3DSlicer interface. Currently, it is difficult to determine whether a false-positive part of the segmentation is truly a false-positive, as the anatomy is hidden behind the segmentation overlay. 

Potential fix could be to replace the top-right window (3D rendering), with the image without segmentation overlay.

**Comment by SachidanandAlle** [comment]
can you provide snapshots and explain the exact issue.  this might be something related to settings in your Slicer view panel.

**Comment by pritesh-mehta** [comment]
Thanks. Currently, user sees this:

![image](https://user-images.githubusercontent.com/33317215/125612883-7e534bcc-b1aa-4dae-b52b-766027943a4a.png)

The underlying anatomy is hidden behind the red segmentation overlay, so it is difficult to place a background click in a false positive region. Using the information in the third link provided, a good solution is to allow the user to pick "segmentation outline only":

![image](https://user-images.githubusercontent.com/33317215/125613079-44fde285-353f-4cb4-895c-c588ed728838.png)

This gives:

![image](https://user-images.githubusercontent.com/33317215/125613160-f7271803-9824-4709-ae8b-6781c6988c4a.png)

Now I can see the anatomy, and place background clicks with more confidence.

The issue now is that I cannot save "segmentation outline only" as a default setting (to the best of my knowledge). As a result, when I click "Next Sample", I see the filled overlay again:

![image](https://user-images.githubusercontent.com/33317215/125613377-314740ef-50c1-4deb-992a-abb261725c42.png)

Having to choose "segmentation outline only" each time a new image is loaded will be frustrating for the user. Can "segmentation outline only" become the default through an adjustment of the monailabel code that manages the interaction with 3DSlicer? Alternatively, can a toggle option be provided somewhere here to switch between outline and fill with more ease: 

![image](https://user-images.githubusercontent.com/33317215/125614291-23045cbc-9e8b-4c05-8039-41331363ab49.png)

Just my suggestions. Better solutions may be possible.

**Comment by pritesh-mehta** [comment]
Apologies, possible my raised issue is a duplicate of #195.
