### ISSUE TITLE
filenotfounderror once Active Learning has reached 100%

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#205]
Once all images have been labelled i.e. all images have a corresponding label with prefix "label_final_", if "Next Sample" is clicked in 3DSlicer, a filenotfounderror is output to console, as there are no remaining images that need labelling.

This error should be handled?

**Comment by SachidanandAlle** [comment]
we can disable the next sample button when all samples are labeled.

**Comment by tvercaut** [comment]
In some scenario, allowing for multiple annotations per sample makes sense. It can indeed provide an idea of intra-rater variability. Also, if a pre-segmentation is already shown to the user, having repeated cases can provide insight into bias arising from the pre-segmentation.

As such, allowing to configure the sampling behaviour would be nice.

**Comment by SachidanandAlle** [comment]
> In some scenario, allowing for multiple annotations per sample makes sense. It can indeed provide an idea of intra-rater variability. Also, if a pre-segmentation is already shown to the user, having repeated cases can provide insight into bias arising from the pre-segmentation.
> 
> As such, allowing to configure the sampling behaviour would be nice.

datastore apis currently help developers to support
https://docs.monai.io/projects/label/en/latest/apis.html#monailabel.interfaces.datastore.Datastore.save_label

- pre-segmentation masks
- final segmentation masks (normally approved/submitted by end user)
- flexibility to save any kind of intermediate masks against a tag.. (e.g. batch processing wants to compute mask using Y model)
- these intermediate masks saved at different purpose will help for developer to score/compute bias etc.. in later stages.. hence its essential to have an refer it back for xyz reasons


yes, but in current version we are allowing user to submit only one final label (after manually annotation/corrections) per sample.... currently we don't have the support to fallback/repeat the same sample again.  we can think about the pros and cons of this config where user can fetch previously submitted image/labels?  is that one config you are looking for?

**Comment by tvercaut** [comment]
Yes, I was thinking that allowing to fetch previously submitted images + associated pre-segmentation (either from the network inference of from a previous manually approved version) would have some use cases.

**Comment by SachidanandAlle** [comment]
> Yes, I was thinking that allowing to fetch previously submitted images + associated pre-segmentation (either from the network inference of from a previous manually approved version) would have some use cases.

You can do it app code.. i mean using datastore api.. you can fetch all the versions of (tagged) label
https://docs.monai.io/projects/label/en/latest/apis.html#monailabel.interfaces.datastore.Datastore.get_label_by_image_id

(we might clean a little bit on the datastore interface to make it more simple, but currently it has the provision to load/save)

On the end point, you can fetch all the info
http://127.0.0.1:8000/datastore/?output=all

However we don't have an endpoint to download image/label through.. that can be added.. are u looking for that? so that slicer/ohif or someone else wants to download them on the remote box?

**Comment by SachidanandAlle** [comment]
Added the basic endpoints for viewers (slicer/ohif/etc..) to get the download image/label from remote

So now we have the support to get all version of label for APP developers and for PLUGIN developers

![image](https://user-images.githubusercontent.com/7339051/125588145-cd1a8566-feab-4fef-a211-4d09c83887fa.png)
