### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#206]
On clicking "Update Model", when folder Y (monailabel start_server --app X --studies Y) contains no labels with prefix "label_final_", an error is output to console: ValueError: num_samples should be a positive integer value, but got num_samples=0.

Error should be handled?

**Comment by SachidanandAlle** [comment]
are there any files in folder Y?

**Comment by SachidanandAlle** [comment]
Ok.. if i understand the issue, you are clicking the update model when there are no final labels submitted/available for training

The error/trace you server log is fine.. however it will be a good idea to disable the update model (button) when we know there are zero labels available to train/update a model
