### ISSUE TITLE
Submit Label button functionality

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#207]
Currently, clicking "Submit Label" in 3DSlicer interface will initiate model training. In my opinion, it would be better if "Submit Label" only saves the "label_final_". Model training should only occur if "Update Model" is clicked.

For example, if I receive 10 new unlabeled images, my preference would be to proceed as follows:

10 times (Next Sample + <click edits> + Submit Label)  + Update Model

rather than:

10 times (Next Sample + <click edits> + Submit Label + <model training>)

The latter would be frustrating as a process. 

If 100 new unlabeled images are received, user could choose to click "Update Model" at intervals of e.g. 5/10/20.

**Comment by SachidanandAlle** [comment]
have you checked the Edit => Application Settings => MONAILabel

Some users (radiologist don't care when the model should be updated) and some wants to control by themself as you mentioned above.

So there is a settings for the plugin to enable/disable some default behavior.

![image](https://user-images.githubusercontent.com/7339051/125578609-e276436b-6d45-4dba-95a3-4a6cc3d97875.png)
