### ISSUE TITLE
Miscellaneous - GPU memory used for the validation step isn't released

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#215]
**Describe the bug**
After hitting the Update Model button, MONAI Label nicely starts the training process (GPU memory usage ~ 6GB). However, when it is time to run validation, it occupies GPU memory that isn't released after the validation step ends (~ 10GB). The training process continues with the same GPU memory used for both training and validation (~10GB).

**To Reproduce**
- Start the training process. 
- Wait for the validation to occur while checking the GPU memory usage (watch -n 0.1 nvidia-smi)

**Expected behavior**
GPU memory is released after the validation step ends. Only the GPU memory used for training should be kept.

**Comment by SachidanandAlle** [comment]
can you check with monai experts?  Is this default behavior for the engine.  MONAILabel uses following engines for running training/validation.

> from monai.engines import SupervisedEvaluator, SupervisedTrainer

**Comment by diazandr3s** [comment]
@wyli is this something expected when using SupervisedEvaluator and SupervisedTrainer?

**Comment by wyli** [comment]
I don't think so, but sometimes we observe it takes a while to release the memory when the tensors are not in use.

**Comment by diazandr3s** [comment]
> I don't think so, but sometimes we observe it takes a while to release the memory when the tensors are not in use.

This also happens even when I stopped both the training and validation. Fifteen minutes have passed and the engines still kept the GPU memory

**Comment by SachidanandAlle** [comment]
Is this problem still exists?  @diazandr3s ??

**Comment by diazandr3s** [comment]
No, I stopped seeing it. I'll close the issue
