### ISSUE TITLE
Wrong Orientation/Origin for multichannel volumes (4D) using Slicer - Issue visualizing BRATS images on 3DSlicer

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#22]
> BRATS and prostate, which have more than one modality. It seems we're having the same problem I had before. Once Slicer loaded the volume, I didn't find a way to get back all the modalities
> 
> This was something I left in the to-solve list. As workaround solution, I get the modalities before I loaded in Slicer
> 
> In addition to the multimodality issue in Slicer, the BRATS data seems to have a problem with the orientation

 -  From @diazandr3s

**Comment by SachidanandAlle** [comment]
Moving to backlog.. not a priority for 0.2 version release

**Comment by lassoan** [comment]
> However, visualizing 4D images in 3D Slicer is not supported.

We can visualize 4D volumes, but loading of 4D Nifti files is currently not supported. You can load 4D NRRDs. We could add loading of 4D Nifiti images, which should not be a lot of work if ITK already supports it.

**Comment by diazandr3s** [comment]
> [image.nii.gz](https://github.com/Project-MONAI/MONAILabel/files/8681272/image.nii.gz)
> 
> qform code is set to NIFTI_XFORM_UNKNOWN.
> sform code is set to NIFTI_XFORM_ALIGNED_ANAT.
> 
> According to the [specification 1](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform.html): This method is not recommended, and is present mainly for compatibility with ANALYZE 7.5 files.
> 
> It might not be recommended because its interpretation is ambiguous.
> 
> Slicer relies on ITK to read this image and it ends up being interpreted as the image defined in the LPS coordinate system, that’s why the IJKtoRAS matrix is diag(-1,-1,1,1). Maybe this is not correct, but I’m not sure if there is anybody who can tell or if there is consensus on how to interpret this image.
> 
> [label.nii.gz](https://github.com/Project-MONAI/MONAILabel/files/8681274/label.nii.gz)
> 
> Both qform and sform code are set to NIFTI_XFORM_SCANNER_ANAT.
> 
> According to the [specification](https://nifti.nimh.nih.gov/nifti-1/documentation/nifti1fields/nifti1fields_pages/qsform_brief_usage/view), The sform code should be set to either NIFTI_XFORM_UNKNOWN, NIFTI_XFORM_ALIGNED_ANAT, NIFTI_XFORM_TALAIRACH or NIFTI_XFORM_MNI_152.. So having NIFTI_XFORM_SCANNER_ANAT as sform code may make the file invalid.
> 
> Slicer relies on ITK to read this image and it is interpreted as the image defined in the RAS coordinate system, that’s why the IJKtoRAS matrix is diag(1,1,1,1). This is most likely correct, as NIfti usually uses RAS.
> 
> In summary both files may contain unsupported/invalid coordinate system definition.
> 
> You may get information on the history of this data set and advice on how to interpret on ITK or other neuroimaging forums. However, there is a practically unlimited number of ways how Nifti files can be messed up, so even if you figure out a solution that works for this particular data set, you’ll still run into problems with other data sets.
> 
> What you could do is to copy the metadata from the input file to the output file more closely. It is not enough to just specify the same origin, spacing, and axis directions, but copy the all the sform and qform related fields. Even if the input data set was invalid and/or ambiguous, the output will be wrong the same way.

Many thanks, @lassoan

**Comment by SachidanandAlle** [comment]
Not sure if we need any fix here.  Closing the issue.  As suggested, please start using nrrd whenever it's possible.  MONAI and MONAILabel image loaders already support the same.

Also settings is available in Slicer Plugin to generate nrrd labels...

Otherwise 4D image depends on how UI supports/passes and Image Loader consumes.  MONAILabel should not be any blocker here.
