### ISSUE TITLE
XNAT Integration

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#223]
Integrate monai label server with XNAT

**Comment by hshuaib90** [comment]
I would be very keen to have this integration working. Do we know if there are particular hurdles or challenges with XNAT integration?

**Comment by SachidanandAlle** [comment]
We need some xnat community to help on developing this plugin.. otherwise MONAILabel server has all the rest apis (ingredients) to support any viewers.. we took an extra step of providing such 2 reference implementations (3Dslicer and vanilla OHIF) to showcase the same.. these python/js based examples should be enough for others to follow.

**Comment by diazandr3s** [comment]
> I would be very keen to have this integration working. Do we know if there are particular hurdles or challenges with XNAT integration?

This will be a great use case, @hshuaib90. MONAI Label + OHIF + XNAT
Happy to chat more about this. As @SachidanandAlle said, MONAI Label is ready to be integrated with XNAT. It has DICOMWeb support and there are several apps that can be used to facilitate medical image annotation. 
There is also interest in supporting the new OHIF v3. See here https://github.com/Project-MONAI/MONAILabel/issues/603

**Comment by hshuaib90** [comment]
We have XNAT server set up at my hospital and I'd be happy to support early testing. I'm afraid I don't know XNAT well enough to contribute to the development - at least not yet.

**Comment by pwrightkcl** [comment]
I have got MONAI label running at KCH, using the DGX as server and data store, and a standard NHS PC with Slicer as client. Long term, I expect we will want to use XNAT and OHIF too.

**Comment by SachidanandAlle** [comment]
> I have got MONAI label running at KCH, using the DGX as server and data store, and a standard NHS PC with Slicer as client. Long term, I expect we will want to use XNAT and OHIF too.

That's good.. lets c on XNAT+OHIF if something can happen in near future.. MONAILabel is an opensource project.. so lets hope to get some more developers from XNAT community pitching in to develop the required plugin at XNAT side to interact with MONAI Label server.

**Comment by pwrightkcl** [comment]
I understand the current implementation is to use DICOM web. How does that handle labels?
1. How do you feed it existing labels?
2. Where does it put labels that you submit?

**Comment by SachidanandAlle** [comment]
DICOM Seg is created and pushed via DICOM Web server (given all permissions are there to read/write for MONAILabel server)

**Comment by jamesobutler** [comment]
For some additional knowledge on this topic, 3D Slicer + XNAT has existed with https://github.com/NrgXnat/XNATSlicer however it had become unmaintained and was recently disabled from the Slicer extensions catalog. It could be enabled again if there are developers interested in supporting it again. See https://github.com/Slicer/ExtensionsIndex/blob/master/ARCHIVE/XNATSlicer.s4ext

**Comment by DrAkshaykumar** [comment]
Hi. 
We have xnat ml set up on aws. We were confused about deploying AIAA Or using monai label. Monai label looks more promising however needs more clarity about how data is trained which more straightforward in XNAT ML. We are more interested in inference tools. Can you please guide us how to deploy inference tool.

**Comment by DrAkshaykumar** [comment]
Currently we have xnat deployed on AWS. We don't have AIAA set up now.
That's why we were thinking how to go about which one to go with.

**Comment by amrshadid** [comment]
Any update ?

**Comment by DrAkshaykumar** [comment]
I would also like to know.

Regards

**Comment by SachidanandAlle** [comment]
Some of the development and integration is completed on XNAT side.  
And there must be an early version of the plugin available.
https://wiki.xnat.org/documentation/xnat-ohif-viewer/release-notes-126157097.html

Please follow more on the XNAT development forum.

**Comment by diazandr3s** [comment]
> Some of the development and integration is completed on XNAT side. And there must be an early version of the plugin available. https://wiki.xnat.org/documentation/xnat-ohif-viewer/release-notes-126157097.html
> 
> Please follow more on the XNAT development forum.

@danieltudosiu

**Comment by DrAkshaykumar** [comment]
Hi,
We are trying to integrate XNAT with monai label, so that the models can be trained and deployed in the same pipeline.
Can someone please prepare a detailed step by step guide to help us integrate it.
We have currently hosted XNAT on AWS. @diazandr3s please discuss in meeting next year.
Regards

**Comment by danieltudosiu** [comment]
Hi @DrAkshaykumar,

If it is ok with you I will join as well the meeting as I am working closely with @diazandr3s and MONAI Label's integration with XNAT is party of my PostDoc's JD. 

I think I will be one of the main points of contact on this issue in the next year.

Best regards,

Dan

**Comment by SachidanandAlle** [comment]
Adding @AHarouni who has helped and lead this xnat + monailabel integration in many ways

**Comment by AHarouni** [comment]
Hi All

Currently the xnat datastore in monai label along with xnat=ohif viewer V3.4 enables the user to run inference of images in the project very efficiently as monai label can directly access xnat data. 
I did send code to xnat-ohif developer to allowing saving of dicom seg back to xnat. once this code is merged you would be able to run batch inference from monai-label api to run inference on all patients in a project convert o dicom seg and push this segmentation to xnat so user can load this seg
Another addition that might be useful is using Rapid reader in xnat. This is unrelated to monai label but you can create a new worklist of all the patients which just finished batch infer for a quick way for radiologist to review and add comments to the quality of the AI. 

There is a minor issue of unifying the AI dicom seg name and who user can name the dicom seg they create so monai-label + xnat datastore can figure out what is unlabeled vs labeled by a radiologist vs labeled by the batch infer. One issue here is each series can have multiple annotations one for liver tumor, kidney tumor etc 

For end to end you should be able to use the xnat jupyter hub feature to launch monai jupyter container where you have access to the data of a given project. I successfully integrated this after modifying monai container and adhere to Xnat jupyter expectations 

**Open items I have on my list**:
- Moving series selector logic from monia deploy to either monai label or monai core. This will allow you to reject series that don't match your dicom tags criteria as running only on modality = CT etc 
- Utilize xnat-ohif new measurements feature by creating measurements on the center slice where the tumor / organ exist. This requires a new transformation to locate the organ / tumor central slice get teh UUID of that slice and create the measurements object expected by Xnat. 
- Creating a pdf report with findings and pushing it back to xnat ohif. This is a big item with multiple blocker. first xnat-ohif doesn't yet support showing encapsulated pdf. Need a new monai transform to calculate organ/ tumorsize and place them nicely in a report. Need to include key image of coronal/sagital /axial of the tumor.

Hope that helps clarifies current status and next steps.

**Comment by AHarouni** [comment]
Hi All

Currently the xnat datastore in monai label along with xnat=ohif viewer V3.4 enables the user to run inference of images in the project very efficiently as monai label can directly access xnat data. 
I did send code to xnat-ohif developer to allowing saving of dicom seg back to xnat. once this code is merged you would be able to run batch inference from monai-label api to run inference on all patients in a project convert o dicom seg and push this segmentation to xnat so user can load this seg
Another addition that might be useful is using Rapid reader in xnat. This is unrelated to monai label but you can create a new worklist of all the patients which just finished batch infer for a quick way for radiologist to review and add comments to the quality of the AI. 

There is a minor issue of unifying the AI dicom seg name and who user can name the dicom seg they create so monai-label + xnat datastore can figure out what is unlabeled vs labeled by a radiologist vs labeled by the batch infer. One issue here is each series can have multiple annotations one for liver tumor, kidney tumor etc 

For end to end you should be able to use the xnat jupyter hub feature to launch monai jupyter container where you have access to the data of a given project. I successfully integrated this after modifying monai container and adhere to Xnat jupyter expectations 

**Open items I have on my list**:
- Moving series selector logic from monia deploy to either monai label or monai core. This will allow you to reject series that don't match your dicom tags criteria as running only on modality = CT etc 
- Utilize xnat-ohif new measurements feature by creating measurements on the center slice where the tumor / organ exist. This requires a new transformation to locate the organ / tumor central slice get teh UUID of that slice and create the measurements object expected by Xnat. 
- Creating a pdf report with findings and pushing it back to xnat ohif. This is a big item with multiple blocker. first xnat-ohif doesn't yet support showing encapsulated pdf. Need a new monai transform to calculate organ/ tumorsize and place them nicely in a report. Need to include key image of coronal/sagital /axial of the tumor.

Hope that helps clarifies current status and next steps.

**Comment by mariamonzon** [comment]
is there any up to guide/tutorial/example on how to implement monai label with XNAT?

**Comment by AHarouni** [comment]
Hi @mariamonzon 
It seems like that part of the documentation was moved. I will try to help you out, please try to follow steps below 

1. Install xnat by following their documentation. You can simply use their docker compose to bring it up quickly 
    i . Verify you have oxnat ohif working by downloading jar file for ohif plugin for xnat and place it in the plugin folder. 
    ii. you need to restart xnat for changes to work
2. Verify that you monai label can start normally with local file system.
3. use below commands before starting monai label
```
export MONAI_LABEL_DATASTORE=xnat
export MONAI_LABEL_DATASTORE_USERNAME=admin  -->replace it if you changed the user 
export MONAI_LABEL_DATASTORE_PASSWORD=admin  -->replace it if you changed the default password 
export MONAI_LABEL_DATASTORE_ASSET_PATH=   --> place the path to the xnat data folder, so monai label can simply use that path to resolve images, other wise monai label will download data from xnat using http calls 
export MONAI_LABEL_DATASTORE_PROJECT=  --> if you want to restrict it to one folder 
export MONAI_LABEL_DATASTORE_CACHE_PATH=  --> assuming you are not sharing the same file system if you need to cache 
export MONAI_LABEL_DICOMWEB_CONVERT_TO_NIFTI=false
monailabel start_server --app apps/radiology --studies http://<xnat_ip>:80 --conf models segmentation_spleen
```
4. verify monai label starts and the logs show it logged into xnat correctly 
5. now you need to configure xnat ohif to see monai label 
```
USER_PASS="admin:admin"
AIAASERVERPORT="http://<monallabel_ip>:8000"
ROOTURL="xnat_ip:80"
!curl -u $USER_PASS -X PUT "$ROOTURL/xapi/ohifaiaa/servers" \
        -H "accept: */*" -H "Content-Type: application/json" \
        -d "[ \"$AIAASERVERPORT\"]"
```
6. configure ohif UI
    i . now go to a patient, open it in ohif, 
    ii. go to preference, experimental, check monai label. 
    iii. click masks from the tool bar, you should see a new icon called monai label
7. in ohif click the right panel "masks" you should see a panel form moanai label and your model should show up there 

Above steps enable the manual triggering of model inference, I have been working on automatically trigger inference once a new study is receiver by xnat. 

Hope that helps. 
let me know if you face issues

**Comment by mrjamesdickson** [comment]
@AHarouni 'I have been working on automatically trigger inference once a new study is receiver by xnat.' Did you ever get that piece working?

**Comment by AHarouni** [comment]
Hi @mrjamesdickson 
Yes I managed to get that workflow. Can you please open an issue for this and assign it to me so I can add this feature to monai label. This workflow required multiple changes:
1- Creating a command for xnat using the container service.
2- Modifying the batch infer code on monai label
3- Changing you app to use the new batch infer code 
4- Setting up Xnat to auto trigger the workflow.


1- Creating a command for xnat using the container service.
On the xnat side you need to have the container service working. You can then add a new command to use a basic curl command to monai label to run inference for the given image_id. This is the most tricky part. You can use the json file below as a starting point.
You must change the the host ip in the file below.

```
{
  "name": "curl4monailabel_study",
  "label": "curl4monailabel_study",
  "description": "Curl to monai label to run infer on full study",
  "version": "1.0",
  "schema-version": "1.0",
  "image": "curlimages/curl:latest",
  "type": "docker",
  "command-line": "curl -X 'POST' $monailabel_host':'$monailabel_port'/batch/infer/'[monailabel_model]'?scope=study&run_sync=true' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{\"image_ids\":[\"[PRJ_ID]/[SUBJ_ID]/[ACCS_ID]/[SCAN_ID]/[SESS_ID]\"] }' ",
  "override-entrypoint": true,
  "mounts": [],
  "environment-variables": {
    "monailabel_port": "8000",
    "monailabel_host": "http://<<your host ip >>"
  },
  "ports": {},
  "inputs": [
    {
      "name": "subject_id",
      "description": "The DICOM series to be sent for inference ",
      "type": "string",
      "required": true,
      "replacement-key": "[SUBJ_ID]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    },
    {
      "name": "project_id",
      "description": "The project id for the Dicom series.",
      "type": "string",
      "required": false,
      "replacement-key": "[PRJ_ID]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    },
    {
      "name": "session_id",
      "description": "The session id for the DICOM.",
      "type": "string",
      "required": false,
      "replacement-key": "[SESS_ID]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    },
    {
      "name": "accession_id",
      "description": "The accession id for the DICOM.",
      "type": "string",
      "required": false,
      "replacement-key": "[ACCS_ID]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    },
    {
      "name": "scan_id",
      "description": "Scan number for the dicom",
      "type": "string",
      "required": true,
      "replacement-key": "[SCAN_ID]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    },
    {
      "name": "monailabel_model",
      "description": "Model name for monai label to run",
      "type": "string",
      "required": true,
      "replacement-key": "[monailabel_model]",
      "command-line-flag": "",
      "command-line-separator": "",
      "select-values": []
    }
  ],
  "outputs": [],
  "xnat": [
    {
      "name": "curl4monailabel_study",
      "description": "Monai Label Study ",
      "contexts": [
        "xnat:imageScanData"
      ],
      "external-inputs": [
        {
          "name": "scan",
          "description": "Input scan",
          "type": "Scan",
          "required": true,
          "load-children": false
        }
      ],
      "derived-inputs": [
        {
          "name": "session",
          "type": "Session",
          "required": true,
          "load-children": true,
          "derived-from-wrapper-input": "scan",
          "multiple": false
        },
        {
          "name": "project-id",
          "type": "string",
          "required": true,
          "provides-value-for-command-input": "project_id",
          "user-settable": false,
          "load-children": true,
          "derived-from-wrapper-input": "session",
          "derived-from-xnat-object-property": "project-id",
          "multiple": false
        },
        {
          "name": "session-id",
          "type": "string",
          "required": true,
          "provides-value-for-command-input": "session_id",
          "user-settable": false,
          "load-children": true,
          "derived-from-wrapper-input": "session",
          "derived-from-xnat-object-property": "label",
          "multiple": false
        },
        {
          "name": "accession-id",
          "type": "string",
          "required": true,
          "provides-value-for-command-input": "accession_id",
          "user-settable": false,
          "load-children": true,
          "derived-from-wrapper-input": "session",
          "derived-from-xnat-object-property": "id",
          "multiple": false
        },
        {
          "name": "subject-id",
          "type": "string",
          "required": true,
          "provides-value-for-command-input": "subject_id",
          "user-settable": false,
          "load-children": true,
          "derived-from-wrapper-input": "session",
          "derived-from-xnat-object-property": "subject-id",
          "multiple": false
        },
        {
          "name": "scan-resource",
          "type": "Resource",
          "matcher": "@.label == 'DICOM'",
          "required": true,
          "provides-files-for-command-mount": "scan-in",
          "load-children": true,
          "derived-from-wrapper-input": "scan",
          "multiple": false
        },
        {
          "name": "scan-id",
          "type": "string",
          "required": true,
          "provides-value-for-command-input": "scan_id",
          "user-settable": false,
          "load-children": true,
          "derived-from-wrapper-input": "scan",
          "derived-from-xnat-object-property": "id",
          "multiple": false
        }
      ],
      "output-handlers": []
    }
  ],
  "reserve-memory": 1000,
  "container-labels": {},
  "generic-resources": {},
  "ulimits": {},
  "secrets": []
}
```
2- Modifying the batch infer code on monai label
I am using the batch infer end point so the dicom seg can be saved back to xnat. 
For this to work you need to modify the batch infer end point in your app or monai label itself as 
```
### create new file in your app folder as lib/tasks/batch_infer.py
class MyBatchInferTask(BatchInferTask):
    def __call__(self, request, datastore: Datastore, infer: Callable):
        image_ids = request.get("image_ids", "")
        if not image_ids: # normal as before 
            image_ids = sorted(self.get_images(request, datastore))
        else: ## image_ids is already sent from xnat 
            request["result_extension"] = ".nii.gz"
            request["multi_gpu"] = False
```
3- Changing you app to use the new batch infer code 
then use this new class as you batch infer, so you need to add these lines to your app main.py file 
```
    def init_batch_infer(self) -> Callable:
        from lib.tasks.batch_infer import MyBatchInferTask
        return MyBatchInferTask()
```
Once you do this then monai label would be getting the id of the image to run inference on. You can trigger the an inference from xnat using the new created command as below 

![Image](https://github.com/user-attachments/assets/dda898b8-e91d-4ceb-ba7f-7c22285883f1)

4- Setting up Xnat to auto trigger the workflow.
After you see this working you need to go to even service on xnat to add an event. on "scan created" for your project or all projects then set action to the command you just created above "curl for monai label dli" 

Hope this helps.
