### ISSUE TITLE
Scribbles - 3D Slicer client plugin support

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#228]
Changes in 3D Slicer plugin to support new interactions for running scribbles

**Comment by SachidanandAlle** [comment]
@masadcv can you think of refining it little more on the UI input.. buttons/interface/GUI/help text etc.. that can create simplified GUI interaction/actions

**Comment by masadcv** [comment]
@SachidanandAlle Sure, I will have a look into this later this week. From our end, the UI is already in a much simplified state, i.e. we only include the required features. I would be happy to take any advice/suggestions on this onboard, perhaps it might be a good topic to discuss in our sync meeting.
