### ISSUE TITLE
Active Learning - Batch Inferencing (callback/api)

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#229]
Support batch inferencing
 - Endpoint
 - API Callback

**Comment by SachidanandAlle** [comment]
I think this is done in 0.1 version but never used.  Adding this issue to track/support any changes needed when actually used in developing active learning strategies

**Comment by aihsani** [comment]
@SachidanandAlle shoudl we close this?

**Comment by SachidanandAlle** [comment]
linked the PR.. so it should get closed automatically when the PR is merged :)
