### ISSUE TITLE
CI/CD - Use Azure as backhand resources (ETA 8/20)

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#246]
Use Azure to run all CI/CD tasks (PRs, Release etc..)

**Comment by evberrypi** [comment]
The Azure account is being provisioned internally and should be completed by the end of the week.

**Comment by evberrypi** [comment]
Added release and build pipelines in #387
Added GPU tests in #414 

Closing this issue as the 0.2.0 release requirements are complete. Will open an issue to translate the Weekly build -> Azure Pipeline

**Comment by evberrypi** [comment]
Tracking weekly build pipeline conversion in #417
