### ISSUE TITLE
Scribbles - Fix installation requirements for scribbles app

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#262]
Currently it's complicated.. gpu vs no-gpu and use requirements.txt to add any app specific packages

**Comment by masadcv** [comment]
Thanks Sachi, regarding the requirements.txt, at the moment MONAI is installed with environment variable `BUILD_MONAI=1` for both GPU/Non-GPU CRF. E.g. https://docs.monai.io/en/latest/installation.html#from-github (`BUILD_MONAI=1 pip install git+https://github.com/Project-MONAI/MONAI#egg=monai`). Is there a straightforward way to include BUILD_MONAI=1 variable in requirements.txt?

**Comment by masadcv** [comment]
I raised this question with MONAI core team, hopefully we can sort out installation of CRF binaries through requirements.txt
The relevant discussion for this on MONAI core discussion is [here](https://github.com/Project-MONAI/MONAI/discussions/2732)
