### ISSUE TITLE
Slicer - Error loading client.py

### ISSUE THREAD

**Issue by RafaelPalomar** [Project-MONAI/MONAILabel#263]
**Describe the bug**
3D Slicer reports an error while trying to instantiate client.py as a scripted slicer module.

```RuntimeError: qSlicerScriptedLoadableModule::setPythonSource - Failed to load scripted loadable module: class client was not found in file /home/rafael/src/monailabel/build/lib/Slicer-4.13/qt-scripted-modules/client.py```

**To Reproduce**
Run 3D Slicer with the build tree of MONAILabel as path for loading the modules

**Expected behavior**
client.py is not a 3D Slicer scripted module and Slicer should not try to load it that way.

**Comment by lassoan** [comment]
The error message is harmless, as it just indicates that client.py is not a Slicer module. 

To avoid this error, the scripted loadable module folder must only contain module files, all other Python files must be in subfolders.
