### ISSUE TITLE
Scribbles - Saving history of scribbles interaction from a user session

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#273]
Within a typical scribbles based application, we want to save every scribbles volume sent to server for a given user session. 
This will be useful for our research work in future, where we can look at how different users interacted over the progress of a session and also understand in more detail the way these interactions happened (e.g. number of scribbles interactions before submitting refined label, style variation, approach to correct labels etc.). 

More specifically this will involve:
- A unique user id for the scribbles session (e.g. current date/time) to differentiate different scribbling sessions
- Saving each scribble volume through datastore. Note: there may be multiple scribbles interactions for same input volume as well as multiple sessions
- Keeping a record of the order of each scribbles interaction for a given volume in a session
- Making a datastructure (json, datastore?) so this data can be easily accessed/understood by future researchers

The above is what I understand this to look like, there may be more finer details once we get around to implementing this logic.

**Comment by SachidanandAlle** [comment]
when you fetch next sample, user session id can be created by monailabel server and client can pass it in all infer/train requests.

**Comment by SachidanandAlle** [comment]
This is available.  User can create sessions with image.  Adding anything else to session can be done through transforms.
With endpoints, anyone can create session (temporary cache) and work on it.

https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/endpoints/session.py
