### ISSUE TITLE
Save Training Runtime Stats

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#29]
After each training session output:
- Training stats in training task
  - We're not saving training related stats
  - Can MONAI provide handlers to save training stats to dump to model folder? (loss, metrics, samples, etc.)
- Validation stats
- Model [DONE]
  - If model folder is deleted we should re-create and re-initialize the weights (?)

**Comment by aihsani** [comment]
Action Items:
- Talk to Andres about: If model folder is deleted we should re-create and re-initialize the weights (?)

**Comment by diazandr3s** [comment]
I'd say, if model folder is deleted, we should re-create it when train starts. Can we can use Tensorboard to save the hyperparameters and training stats?

**Comment by SachidanandAlle** [comment]
done... if the model doesn't exists... it will create it back.
After training, the trained model and stats are saved in model/<output> folder
https://github.com/Project-MONAI/MONAILabel/commit/0f9ffc07e3b3a83fc7a00c8015ff4292cccc6cd5
