### ISSUE TITLE
Automate running the server

### ISSUE THREAD

**Issue by idhamari** [Project-MONAI/MONAILabel#298]
The interface could have a button: "Start Server" where the user selects the app and the studies from comboboxes. Then the argumemts passed to a system call e.g. os.system to   "monailabel start_server"+args

**Comment by SachidanandAlle** [comment]
This is another way to look at it.. but the scope here is not really UI driven installation/deployment of apps for now..
Possibly this can be in future..

**Comment by idhamari** [comment]
Thanks for the info.

**Comment by SachidanandAlle** [comment]
Currently not in scope for developing another UI to start the server.  Feel free to add such utilities if there is a stronger use-case and that can benefit others.  For now closing the issue.  But if there is a contribution on this feature, feel free to reopen the same.
