### ISSUE TITLE
DICOM - LoadImage fails to load files from dicom folder

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#304]
DICOM files fail to load in LoadImage for monai.  It currently throws some ITK exception

**Comment by aihsani** [comment]
Updating to `itk==5.2.1` seems to fix the single bit representation DICOMSEG loading issue.

**Comment by aihsani** [comment]
Will be raised with MONAI team, not part of the issues for MONAI Label.
