### ISSUE TITLE
nvidia-smi executable Windows error

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#306]
nvidia-smi is not on path for command line execution on my (all?) windows machine by default. As a result, the following line throws an error:
https://github.com/Project-MONAI/MONAILabel/blob/58cea3c98fb068758123433ada3499a4948b7ea0/monailabel/utils/others/planner.py#L35

The error thrown by subprocess.py is "FileNotFoundError: [WinError 2] The system cannot find the file specified". The error message does not make clear what the issue is, so took me a while to figure out that the fix was was to add nvidia-smi to path. 

Can/should anything be done to alert the user of the solution if they encounter this error?

**Comment by diazandr3s** [comment]
Thanks for raising the issue! In this PR I propose a solution for this https://github.com/Project-MONAI/MONAILabel/pull/322

**Comment by diazandr3s** [comment]
Closing this issue... Changes have been merged into the main branch
