### ISSUE TITLE
Create objects to represent requests for inference, train, next sample, strategy

### ISSUE THREAD

**Issue by aihsani** [Project-MONAI/MONAILabel#315]
**Is your feature request related to a problem? Please describe.**
Currently request structure for inference, train, etc is free-form dictionary. This was necessary so far to fast turn-around on unknown request items.

**Describe the solution you'd like**
Propose to formalize the request structure using object for easy manipulation an understandability from end-users.

**Comment by SachidanandAlle** [comment]
we shall be slowing moving to use monai bundles.. using bundles shall deprecate many of these things in monailabel in coming future.
