### ISSUE TITLE
Feature request - browser-based backend for specifying model/scribbles/etc options

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#330]
As we have discussed in the past, MONAILabel apps need to provide best options and the user is not required to select/change these when running a specific labelling task. 

In this regards, a nice-to-have feature could be to move all selectable "options" onto a FastAPI backend server page which a developer/researcher can access and modify underlying options as needed by the end-user. This way, we can make the actual UI shown to an end-user less cluttered, while still having the flexibility to switch underlying methods from backend. This may need more discussion/suggestions, which is why I have created this feature request issue.

cc: @tvercaut

**Comment by SachidanandAlle** [comment]
we can have developer mode option in the main settings for the plugin.. if someone wants to play around with the options they will become visible based on that...

**Comment by SachidanandAlle** [comment]
and there are definitely better opportunities to improve the UI.. but need some external contributors who are more expert in UI design + Slicer UI development..

For now, just adding one way not to show it to users by default.. only people like us.. who wants to see and modify some config.. they can do it..

**Comment by lassoan** [comment]
You could also move all the GUI elements that might not be useful for regular users into an "Advanced" collapsible section, collapsed by default. That would still not clutter the GUI too much and would be easier to discover and show/hide as needed.

**Comment by masadcv** [comment]
Thanks @SachidanandAlle, that sounds like a good solution for now. Maybe we can revisit this once we have an expert in UI design.
