### ISSUE TITLE
update the sphinx theme to be consistent with `project-monai/monai` 

### ISSUE THREAD

**Issue by wyli** [Project-MONAI/MONAILabel#344]
**Is your feature request related to a problem? Please describe.**
`project-monai/monai` adopted a new sphinx theme since https://github.com/Project-MONAI/MONAI/issues/2655,
would be great to update MONAILabel sphinx site for the same style.

**Describe the solution you'd like**
mainly following the updates here 
- conf.py https://github.com/Project-MONAI/MONAI/pull/2657/files#diff-008dcb3426febd767787b1521f1fe33086313b927ea37eaab86df5fa88a51698
- requirements.txt https://github.com/Project-MONAI/MONAI/pull/2657/files#diff-2c9c11d26b09b8afde329980309d967121543a456e4592c76886a20b5cf56c90

**Additional context**
the relevant pull request in monai https://github.com/Project-MONAI/MONAI/pull/2657
the current doc site is at https://docs.monai.io/projects/label/en/latest/

**Comment by wyli** [comment]
FYI @gigony thanks!

**Comment by SachidanandAlle** [comment]
can not browser version specific docs anymore?
