### ISSUE TITLE
[Slicer] ITK reader - orthonormal direction cosines

### ISSUE THREAD

**Issue by diazandr3s** [Project-MONAI/MONAILabel#35]
This occurs sometimes when clicking on Next image button

Traceback (most recent call last):
  File "/home/adp20local/Documents/MONAILabel/plugins/slicer/MONAILabel/MONAILabel.py", line 828, in onClickSegmentation
    self.updateSegmentationMask(result_file, self.models[model].get("labels"))
  File "/home/adp20local/Documents/MONAILabel/plugins/slicer/MONAILabel/MONAILabel.py", line 936, in updateSegmentationMask
    labelImage = sitk.ReadImage(in_file)
  File "/home/adp20local/Documents/viewers/Slicer-4.13.0-2021-04-26-linux-amd64/lib/Python/lib/python3.6/site-packages/SimpleITK-2.1.0.dev217-py3.6-linux-x86_64.egg/SimpleITK/extra.py", line 346, in ReadImage
    return reader.Execute()
  File "/home/adp20local/Documents/viewers/Slicer-4.13.0-2021-04-26-linux-amd64/lib/Python/lib/python3.6/site-packages/SimpleITK-2.1.0.dev217-py3.6-linux-x86_64.egg/SimpleITK/SimpleITK.py", line 7861, in Execute
    return _SimpleITK.ImageFileReader_Execute(self)
RuntimeError: Exception thrown in SimpleITK ImageFileReader_Execute: /work/Preview/Slicer-0-build/ITK/Modules/IO/NIFTI/src/itkNiftiImageIO.cxx:1980:
ITK ERROR: ITK only supports orthonormal direction cosines.  No orthonormal definition found!

**Comment by SachidanandAlle** [comment]
Can you note down the image which happened?  Is it after running auto-segmentation model?

**Comment by diazandr3s** [comment]
I just checked again and it happens for images spleen_1, spleen_37, and spleen_48. I'm not sure whether it happens before or after the auto-segmentation model.

![spleen_48](https://user-images.githubusercontent.com/11991079/117005338-08c8e480-acdf-11eb-8f83-4b54aee25aad.png)
![spleen_1](https://user-images.githubusercontent.com/11991079/117005340-09617b00-acdf-11eb-8dfc-69d6d1108d16.png)
![spleen_37](https://user-images.githubusercontent.com/11991079/117005343-09617b00-acdf-11eb-846c-211b13f0b058.png)

**Comment by SachidanandAlle** [comment]
You can disable auto segmentation in setting.. and fetch only those images.. 

however the message says, failed to run inference on pretrained model.. so you can run inference on those samples and see what kind of label mask it's producing.. there might be a difference in populating correct header or no output/label produced

**Comment by fepegar** [comment]
> I just checked again and it happens for images spleen_1, spleen_37, and spleen_48. I'm not sure whether it happens before or after the auto-segmentation model.

None of these are available on the Medical Decathlon website. Is that expected?

**Comment by fepegar** [comment]
For completion, these are the available images:

```
$ ls Task09_Spleen/imagesTr
spleen_10.nii.gz spleen_17.nii.gz spleen_21.nii.gz spleen_27.nii.gz spleen_32.nii.gz spleen_44.nii.gz spleen_52.nii.gz spleen_60.nii.gz spleen_9.nii.gz
spleen_12.nii.gz spleen_18.nii.gz spleen_22.nii.gz spleen_28.nii.gz spleen_33.nii.gz spleen_45.nii.gz spleen_53.nii.gz spleen_61.nii.gz
spleen_13.nii.gz spleen_19.nii.gz spleen_24.nii.gz spleen_29.nii.gz spleen_38.nii.gz spleen_46.nii.gz spleen_56.nii.gz spleen_62.nii.gz
spleen_14.nii.gz spleen_2.nii.gz  spleen_25.nii.gz spleen_3.nii.gz  spleen_40.nii.gz spleen_47.nii.gz spleen_59.nii.gz spleen_63.nii.gz
spleen_16.nii.gz spleen_20.nii.gz spleen_26.nii.gz spleen_31.nii.gz spleen_41.nii.gz spleen_49.nii.gz spleen_6.nii.gz  spleen_8.nii.gz

**Comment by diazandr3s** [comment]
> > I just checked again and it happens for images spleen_1, spleen_37, and spleen_48. I'm not sure whether it happens before or after the auto-segmentation model.
> 
> None of these are available on the Medical Decathlon website. Is that expected?

I used the test set

**Comment by diazandr3s** [comment]
> You can disable auto segmentation in setting.. and fetch only those images..
> 
> however the message says, failed to run inference on pretrained model.. so you can run inference on those samples and see what kind of label mask it's producing.. there might be a difference in populating correct header or no output/label produced

Yes, it seems the error is because the pretrained model doesn't compute a label

**Comment by SachidanandAlle** [comment]
fix the model to give some result.. when you have empty mask.. you get this error.
for spleen, have updated the model to use latest and greatest from clara/ngc

**Comment by diazandr3s** [comment]
> fix the model to give some result.. when you have empty mask.. you get this error.
> for spleen, have updated the model to use latest and greatest from clara/ngc

Superb!

**Comment by SachidanandAlle** [comment]
User ITK writer instaed of monai write_nifti: https://github.com/Project-MONAI/MONAILabel/commit/82ee95b90fc676826b9c4bfedf6acb1c7fcb81c5
