### ISSUE TITLE
CUDA out of memory

### ISSUE THREAD

**Issue by fengyuan1993012** [Project-MONAI/MONAILabel#373]
Hello, when I run the monailable as the instruction in 3D slicer.  The import file is " Task02_Heart/imagesTr". when I clicked the next sample button, the error "RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 4.00 GiB total capacity; 2.33 GiB already allocated; 457.80 MiB free; 2.36 GiB reserved in total by PyTorch)" occurred.  I think the cause is the dataset is big. So I use my own dataset including one .nii.gz 682*682*682. however, it still doesn't work. I don't know how to fix it. I know the monai label will load one neural network for quick annotation. However, I don't think the error "out of memory" is caused by the size of the network. I would appreciate it if you could help me out. Thanks a lot.

**Comment by masadcv** [comment]
Thanks for your query @fengyuan1993012 . Just curious what is the output of `nvidia-smi` before running this? Are there any existing processes taking up GPU memory? The dataset is not loaded directly into GPU memory so its unlikely the cause here. What might be happening is when you try to run inference on a single sample, it is running out of GPU memory, which may be caused by low available memory to load the model as well as data for input sample.

**Comment by aihsani** [comment]
@fengyuan1993012 could you please look at the following and report here:
- the size in GB of your GPU
- the type of the GPU (e.g. RTX2080)

It is possible that the network doesn't fit into your GPU.

Does the issue you posted occur during training or inference (e.g. when either running the segmentation model or clicking points using deepedit)?

**Comment by SachidanandAlle** [comment]
> Hello, when I run the monailable as the instruction in 3D slicer. The import file is " Task02_Heart/imagesTr". when I clicked the next sample button, the error "RuntimeError: CUDA out of memory. Tried to allocate 1024.00 MiB (GPU 0; 4.00 GiB total capacity; 2.33 GiB already allocated; 457.80 MiB free; 2.36 GiB reserved in total by PyTorch)" occurred. I think the cause is the dataset is big. So I use my own dataset including one .nii.gz 682_682_682. however, it still doesn't work. I don't know how to fix it. I know the monai label will load one neural network for quick annotation. However, I don't think the error "out of memory" is caused by the size of the network. I would appreciate it if you could help me out. Thanks a lot.

When you click next sample, server tried to run inference (segmentation).  In this case, you need to have enough GPU memory available for 
1. load the network
2. input image for inference (which gets pushed to CUDA).

The above message says, 2.3 GiB is already allocated and only less than 500 MiB is free.

You can disable the auto run feature for inference on next sample (3D slicer -> Edit -> Application Settings -> Monai Label -> Enable/Disable running pre-trained model)

To run 3D model, it's ideal if you have about 6 to 8 GB GPU memory.  Or you can try Deepgrow 2D model to run inference using very small GPU.

Also you can open logs in browser like http://127.0.0.1:8000/logs (which are also captured on terminal) and try to understand in which step it failed... pre-processing? infer? post-processing?  That will give you the exact hint, in which step it failed to allocate enough GPU memory.
