### ISSUE TITLE
CONTRIBUTE guidelines (follow monai)

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#38]

**Comment by tvercaut** [comment]
Would it be useful to already enable "GitHub discussions"? In particular for contribution-related topics that may be broader than typical "Issues"

**Comment by SachidanandAlle** [comment]
> Would it be useful to already enable "GitHub discussions"? In particular for contribution-related topics that may be broader than typical "Issues"

It's Enabled now.

**Comment by SachidanandAlle** [comment]
Added basic guidelines
