### ISSUE TITLE
Seamless User Experience Requirements for installation & demo apps

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#40]

**Comment by SachidanandAlle** [comment]
- monailabel datasets --command download --name Task02_Heart
- monailabel apps --command download --name deepedit_heart

user should be able to download standard datasets (MSD) and sample apps like above

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel#installation
