### ISSUE TITLE
User Experience Requirements for product installation & default apps config parameters.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#41]
Prerna to provide requirements for configurable parameters to be exposed through UI for Clinician persona to start using.

**Comment by SachidanandAlle** [comment]
the basic installation shall be..

1) pip install monailabel
2) monailabel datasets --command download --name Task02_Heart
3) monailabel apps --command download --name deepedit_heart
4) monailabel run --app deepedit_heart --studies Task02_Heart/imagesTr

5) Download 3D Slicer latest (pre-release version) and install/use MONAILabel plugin

Anything else?

**Comment by SachidanandAlle** [comment]
@pdogra89 - do you have anything else?

**Comment by SachidanandAlle** [comment]
beliving nothing more needed - closing this issue
