### ISSUE TITLE
CI/CD: Move Weekly Build GH Action to Azure Pipeline

### ISSUE THREAD

**Issue by evberrypi** [Project-MONAI/MONAILabel#417]
This was not required in the 0.2.0 release but still needs to be completed to transition all CI to Azure.

**Comment by SachidanandAlle** [comment]
@wyli need your help :)

**Comment by wyli** [comment]
Sure, please let me know, for gpu tests and blossom, we'll need Peixin's help. Cc @Nic-Ma

**Comment by SachidanandAlle** [comment]
Let's get started on this.. 
we want to run build task on blossom..

https://github.com/Project-MONAI/MONAILabel/blob/main/.github/workflows/pythonapp.yml

**Comment by YanxuanLiu** [comment]
Sure, I will migrate the tests to blossom

**Comment by YanxuanLiu** [comment]
@evberrypi  Do we need to run these CI tests weekly/nightly or pre-merge on blossom?

**Comment by SachidanandAlle** [comment]
need an option to run the test on demand basis (i guess that should be pre-merge) and admin can decide if we need to trigger or not while merging the PR

**Comment by YanxuanLiu** [comment]
Do the tests require GPU resource? generally we only run tests requiring GPU on blossom.

**Comment by SachidanandAlle** [comment]
@tangy5 can you help @YanxuanLiu on this..

**Comment by tangy5** [comment]
HI @YanxuanLiu , Yes, we have lots of unit tests and integration test that requires GPU. 
Let's catch more on this. 
Thank you so much.
