### ISSUE TITLE
Setting default window width (WW) and default window level (WL)

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#447]
We have had some feedback from clinical partners regarding setting of window for highlighting different organs.
The window/levels are defined typically by window width (WW) and window level (WL). This is then used in the following formula to set the min/max levels for CT images.
w_min = WL - WW/2
w_max = WL+WW/2

More info about this can be found here: https://radiopaedia.org/articles/windowing-ct?lang=gb

There are known WL/WW values for different organs/tissues (as listed in the above link). 

For example, a lung window is typically defined as WW=1500 and WL=-600. This has the following effect on visualizing the image volume:

Before applying lung window:
![image](https://user-images.githubusercontent.com/3410225/136550503-66fc1ba3-14f2-405a-8e06-afad4c3fc47f.png)

After applying lung window (WW=1500, WL=-600):
![image](https://user-images.githubusercontent.com/3410225/136550684-ba7a0ca4-9757-4de9-96c5-d132a8b30165.png)

You can notice that it highlights tissues/lesions inside lung better. The above is just one example, the values for WW/WL can vary for different organs and institute.

In 3D Slicer, the above can be achieved as:
```
WL=-600; WW=1500
volumeNode = slicer.mrmlScene.GetFirstNodeByClass("vtkMRMLScalarVolumeNode")
volumeNode.GetDisplayNode().SetAutoWindowLevel(False)
volumeNode.GetDisplayNode().SetWindowLevelMinMax(WL-WW/2, WL+WW/2)
```

Does this sound like something we can pass as argument from an app as default, given that we know the target organ/tissue and its WL/WW. In cases where these are not present, we can skip updating the above. In other cases where the user wants to change these, there is a window level button that can be used to adjust manually. 

cc: @tvercaut

**Comment by masadcv** [comment]
There is an open pull request for this: https://github.com/Project-MONAI/MONAILabel/pull/473
As discussed in our meetings, we need to think a bit more about such feature and where it goes for MONAI Label.

**Comment by masadcv** [comment]
Closing this and #473 for now. We can reopen if we see interest in getting this solved within monai label.

**Comment by rbumm** [comment]
\>> or add presets to the right-click menu in slice viewers.

For your information, this function is now available in SLicer 5

![](https://user-images.githubusercontent.com/18140094/174411706-d8250aad-cab9-441c-ab52-834c600df401.png)

**Comment by rbumm** [comment]
We are segmenting many CT datasets from various sources and quality with MONAILabel. 

It seems, as if segmentation results could be better standardized and more precise if the datasets could somehow be batch normalized in respect of HU range or histogram for certain organs like lung or airways, I face the same problem when I segment data from the lung06 dataset with 3D Slicer´s extension "Lung CT Segmenter".  

Any ideas on that?

**Comment by masadcv** [comment]
Hi @rbumm,

Many thanks for your question. Indeed, the HU intensity range is normalised for each volume in every MONAI Label app using [ScaleIntensityRanged](https://docs.monai.io/en/stable/transforms.html#scaleintensityranged) transform. However, the default setting for the included sample apps is targetting multiple organs in the abdomen. This default normalisation may not work well with CT Lung volume, as you rightly pointed out. 

You will need to override these in your app to target lungs in CT. For example, for radiology app if you are using Scribbles, you will need to change the following lines:
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/main.py#L118-L137

to

```
        infers.update(
            {
                "Histogram+GraphCut": HistogramBasedGraphCut(
                    intensity_range=(-1000, 400, 0.0, 1.0, True),
                    pix_dim=(2.5, 2.5, 5.0),
                    lamda=1.0,
                    sigma=0.1,
                    num_bins=64,
                    labels=task_config.labels,
                ),
                "GMM+GraphCut": GMMBasedGraphCut(
                    intensity_range=(-1000, 400, 0.0, 1.0, True),
                    pix_dim=(2.5, 2.5, 5.0),
                    lamda=5.0,
                    sigma=0.5,
                    num_mixtures=20,
                    labels=task_config.labels,
                ),
            }
        )
```

Here the `intensity_range` parameters provides `(input_min, input_max, output_min, output_max, apply_clipping)` where min max ranges for input and normalised output are specified along with whether to discard values outside these ranges with `apply_clipping`. You can change these ranges to a suitable range for your data. If you are using deepedit or other functionality, you will need to have the same changes for `ScaleIntensityRanged` in each app/module.

In addition, as you pointed out above, you will require appropriate windowing for displaying this data to radiologists/clinicians as the `ScaleIntensityRanged` is only used for the algorithmic part.

Hope this is clear, please let me know if you have any further questions regarding this, I may be able to help out as I have been involved in using MONAI Label in CT Lung volumes for our projects.

**Comment by rbumm** [comment]
Hi @masadcv , 

Thank you for the detailed answer.

My current approach is to load datasets in 3D Slicer within ML with the "Next sample" button, then label the CT lung dataset with my own extension (Lung CT Segmenter, a module of [Lung CT Analyzer](https://github.com/rbumm/SlicerLungCTAnalyzer)), and then "submit label" and train. Just to be able to create lung masks and airways with Monailabels autosegmentation.  

I get astonishingly stable results on a gaming PC already using the ML segmentation model

![](https://cdn.discordapp.com/attachments/985884941445386270/987287827442204692/unknown.png)

```
monailabel start_server --app ./apps/lung --studies ./datasets/Task06_Lung/imagesTr --conf models segmentation
```

and the Monailabel approach is fascinating. 

In this workflow, do you see the need to set lung or airway intensity ranges somewhere? Or is this only needed if we use the scribbles function?

**Comment by masadcv** [comment]
Hi @rbumm ,
This is quite interesting workflow. I believe, as you are doing all processing on Lung CT Segmenter, you only may need to normalise/clip intensity ranges in Lung CT Segmenter. 

The monai label intensity normalisation approach is only needed if you use one of the server apps (including deepedit, autoseg and scribbles etc) to perform the annotation. As you are not using them, you wont need to modify anything related to the intensity ranges in those apps. I believe it will be useful to set these ranges in Lung CT Segmenter (if not already done). 

That being said, I wonder if your approach can be implemented as a MONAI Label App to have the relevant algorithms working inside a server app (using scribbles or points). I will check out the code for Lung CT Segmenter to know more about the methods you use.

**Comment by masadcv** [comment]
Another aspect to mention in context of this discussion is that the Histogram and Gaussian Mixture Model that are currently implement in MONAI Label may be too simple models for capturing large variations in lung regions, especially when segmenting lesions. We have developed a more sophisticated approach to address such problems in lung CT by using a CNN instead of these simple models. The code for this is available at: https://github.com/masadcv/ECONet-MONAILabel

**Comment by rbumm** [comment]
This is a very good idea. Will try to normalize the intensities in Lung CT Segmenter and see how that goes. It is on the to-do list. 

It would be very interesting to enable MONALLabel to do segmentations within its own AI results: Example:  to find nodules in the right lung segment that it has auto segmented before.
