### ISSUE TITLE
Training Deepgrow on more CT organs

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#46]
To enable the clinician 201 workflow, improving the out of box experience for Deepgrow as default MONAILabel App.

**Comment by SachidanandAlle** [comment]
basic deepgrow app is added with both 2D and 3D training t.asks.
Also it includes deepgrow pipeline (combined infer task using both 2D and 3D models)

**Comment by SachidanandAlle** [comment]
we have the deepgrow app to work on CT(spleen)
