### ISSUE TITLE
DeepEdit development & evaluation for when a pre-trained version is available for defined task.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#48]
Aligned to 301 workflow.

**Comment by SachidanandAlle** [comment]
Now we have sample apps to download the pretrained models and available for both infer/training tasks...

**Comment by SachidanandAlle** [comment]
can you add the updates/details and close this issue if all done

**Comment by diazandr3s** [comment]
- Pretrained deepedit models for both Apps were updated and made available for developers to use
- Users can use pretrained models or do cold-start training on the available Apps
