### ISSUE TITLE
Ability to Train and infer multiple models at the same time for researchers evaluation.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#49]
For 201 workflow as we enable train & infer on different models. It is possible that a researcher may want to train 2 distinct models at same time with user created label (DeepGrow & UNet). If GPU resources are available researcher should be able to do so simultaneously.

**Comment by SachidanandAlle** [comment]
Fixed.

As part of current framework, when a new sample is saved, user can train any number of models if resources are available.
For example user is already running multiple infers + 1 training as part of sample apps.

It's always allowed to add another train task in the app.
Example implementation can be found at: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/deepgrow

**Comment by SachidanandAlle** [comment]
However default config is to run one-at-a-time... we need to add support in MONAILabel framework to configure N number of parallen tasks instead of using 1 as default

**Comment by SachidanandAlle** [comment]
marking this as done.
