### ISSUE TITLE
Replace DynUNetV1 (deprecated) by DynUNet

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#493]
- Lets not use deprecated network in 0.3 version
- Train a pretrained model and publish the same for deepedit app

**Comment by SachidanandAlle** [comment]
For reference: https://github.com/Project-MONAI/MONAILabel/issues/492

**Comment by diazandr3s** [comment]
Agree! Will change the network and re-train the DeepEdit for Spleen and left atrium.
