### ISSUE TITLE
can't see MONAILabel module in 3DSlicer preview release Windows

### ISSUE THREAD

**Issue by hw-ju** [Project-MONAI/MONAILabel#503]
I installed 3DSlicer, latest preview release for Windows, version 4.13.0. After I installed MONAILabel, and restarted 3DSlicer and my laptop, the MONAILabel still doesn't not appear within the Modules list.

**Comment by lassoan** [comment]
What operating system do you use and which exact Slicer version have you installed?

**Comment by hw-ju** [comment]
> What operating system do you use and which exact Slicer version have you installed?

I'm using Windows 10, 
3D Slicer version: preview release for windows
![image](https://user-images.githubusercontent.com/90806807/141040416-b2d2902d-e38b-4d45-9461-76515d5ea3ac.png)

**Comment by lassoan** [comment]
I've tested it now and it works well. The easiest way to find MONAILabel module is to click on the search icon and type its name:

![image](https://user-images.githubusercontent.com/307929/141041796-00046bb6-7bcb-4eb2-880c-f2e5818bef6e.png)

**Comment by hw-ju** [comment]
@lassoan Thanks for the help! I misunderstood "restart" after installation. I thought I need to restart Slicer, but it really is to click the button "restart" for the plugin within the extension manager. Now I find it within "Modules". Thank!

**Comment by lassoan** [comment]
Glad it works now.
