### ISSUE TITLE
can't start server within NGC PyTorch container on a remote Slurm cluster

### ISSUE THREAD

**Issue by hw-ju** [Project-MONAI/MONAILabel#507]
I installed monailabel within NGC PyTorch container on a remote Slurm cluster.
After I submitted batch file:
[start_server.txt](https://github.com/Project-MONAI/MONAILabel/files/7515094/start_server.txt)
the output is:
[output.txt](https://github.com/Project-MONAI/MONAILabel/files/7515101/output.txt)

I guess this output shows some errors. I can't open the default server address http://127.0.0.1:8000/ in my local browser or use it in the server address lane in my local 3DSlicer to connect successfully.

I downloaded the required app and dataset. What could be wrong?

**Comment by SachidanandAlle** [comment]
Have you checked the logs at server.. ? Server started with no error... if you are running docker.. u might want to enable port mapping correctly

**Comment by hw-ju** [comment]
@SachidanandAlle Thanks for your super fast response!
I'm using Singularity. On most university clusters, docker is not allowed.
How to check the logs at server?

**Comment by diazandr3s** [comment]
If MONAI Label was properly started, you should see a folder called logs inside the App folder. You can also see them at the browser 127.0.0.1:8000/logs 

Which MONAI Label App are you using (i.e. DeepEdit, DeepGrow)? and which dataset are you using?

**Comment by hw-ju** [comment]
@diazandr3s Thanks!
Here is the app.log file, could you take a look? 
[app.log](https://github.com/Project-MONAI/MONAILabel/files/7516366/app.log)

I'm using DeepEdit, Task09_Spleen.

**Comment by diazandr3s** [comment]
Thanks @hw-ju 
From what I can see the server started with no errors. Do you mind sharing a print screen of what you're seeing in the terminal/screen?
I think this is more related to port mapping. Have you tried that? If this is the issue, you need to find out what is the IP address of the singularity image and do the port mapping. I think you can check the IP address by running this command: netstat -a -n -o

**Comment by SachidanandAlle** [comment]
I believe it's more related to user env (singularity).. if you try it on direct node/laptop you should see the port up and in your local browser you can access http://127.0.0.1:8000/

Hence closing the issue, if still it's related to monailabel server, please feel free to reopen it with more details
