### ISSUE TITLE
Default Recipe/Configs included for MONAILabel Apps

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#51]
Clinician/Technically Novice user is abstracted from details of underlying logic of MONAILabel Apps that determines background actions like:
- When to start training
- When to stop training (acceptable Val score) 
- Some metrics to quantify and monitor that new derivative model for user data is getting better.

**Comment by SachidanandAlle** [comment]
as a default recipe, training is started on every label submitted..
if the training is running, we restart the training.. config is added in slicer to control this behavior

the metrics are shared with viewer, so slicer shows the current accuracy of model after it updates.
this will give handle to user to stop/annotating further..
