### ISSUE TITLE
Identify the datasets (CT & MR) for Spleen & Heart to evaluate for 101, 201 & 301 approaches.

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#52]

**Comment by mjorgecardoso** [comment]
The datasets should be the decathlon dataset. http://medicaldecathlon.com
It's already integrated into MONAI, which would make it even easier to use.

**Comment by SachidanandAlle** [comment]
Agreed.  We shall be using MSD Datasets for all the sample apps to showcase the workflow.

As part of MONAI, they are already part of aws to fetch it remotely.  The sample apps will have basic init/setup functionality to pull the datasets from https://github.com/Project-MONAI/MONAI/blob/dev/monai/apps/datasets.py#L213-L224

@pdogra89 if you are agreeing on this, we can close this issue

**Comment by SachidanandAlle** [comment]
I am closing this issue as I see no more updates or discussions
