### ISSUE TITLE
Capability for researchers to evaluate Active Learning Approaches (support batch_infer callback etc.)

### ISSUE THREAD

**Issue by pdogra89** [Project-MONAI/MONAILabel#53]
- Add batch infer to monai app base class
  - Implement in user app once above complete
- Design score output to datastore

**Comment by aihsani** [comment]
Use case: for active learning one must estimate an uncertainty coefficient/score on all unlabeled images on the current state of the model. This involved performing inference on each unlabeled image, getting a result, then comparing all results against each other using the desired uncertainty scoring algorithm and picking the image with highest uncertainty.

Solution: Provide binding on user app for user to easily implement any desired scoring strategies and store in the local datastore.

**Comment by SachidanandAlle** [comment]
Now we have batch infer.. similarly lets add batch scoring task..  leta have example basic scoring methods
1) sum: simply to compute np.sum for all the slices of original label.. just to showcase the example method 
2) dice: when we have truth set for certain images submittedby user.. we have dice score..

User can provide multiple of these methods.. for scoring

**Comment by SachidanandAlle** [comment]
we have both batch infer and scoring tasks...
https://github.com/Project-MONAI/MONAILabel/tree/main/monailabel/interfaces/tasks
