### ISSUE TITLE
Add additional info for each image/label pair

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#55]
Example.. when label is saved, we want to compute the mismatch between original model vs user submitted
Also option to save temp labels (generatd by auto-segmentation) in datastore (for unlabled images)

**Comment by aihsani** [comment]
Problem: We do not know when the model is good enough to stop training the DeepEdit/DeepGrow/etc model

Proposed solution: Compare the auto-segmentation presented to the user at the start of a specific image labeling task, call it L0, to the label the user submit for that same image at the end of the editing, call it L1, and derive an accuracy metric (e.g. Dice score). If the user-submitted label is above X on the accuracy metric (e.g. 0.9 Dice score) as pre-configured by the user app training is no longer "neccessary".

**Comment by SachidanandAlle** [comment]
Once we have the datastore support for storing corresponding label masks, and info..
We need a background task to compute the scores periodically
