### ISSUE TITLE
OHIF Viewer : Couldn't connect to Orthanc Server

### ISSUE THREAD

**Issue by Suchi97** [Project-MONAI/MONAILabel#550]
**Describe the bug**
I am trying to use OHIF viewer. When trying to run `monailabel start_server --app apps\deepedit --studies http://127.0.0.1:8042/dicom-web`  this URL , it pops up with a dialogbox to enter the username and password.

I tried some default username and password, but it doesn't signed into the Orthanc Server.

**To Reproduce**
For this, I followed the below steps which was mentioned in the [document](https://docs.monai.io/projects/label/en/latest/installation.html). 
  1. Installed Orthanc using apt-get install orthanc orthanc-dicomweb.
  1. Upgraded to latest version by following steps mentioned [here](https://book.orthanc-server.com/users/debian-packages.html#replacing-the-package-from-the-service-by-the-lsb-binaries)

Now the orthanc server setup is completed.

  1. Run the command `monailabel start_server --app apps\deepedit --studies http://127.0.0.1:8042/dicom-web`
  
**Expected behavior**

I expect that orthanc server should load without the authentication pop up. 

**Screenshots**

![orthancerror](https://user-images.githubusercontent.com/25792114/144841649-a74bcae7-915a-44b9-88e2-11ba22f92bba.png)

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0.9.dev2149
Numpy version: 1.21.4
Pytorch version: 1.9.0+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 1ad68787c35e259cb7704b56d679659104d2494c

Optional dependencies:
Pytorch Ignite version: 0.4.6
Nibabel version: 3.2.1
scikit-image version: 0.18.3
Pillow version: 8.4.0
Tensorboard version: 2.7.0
gdown version: 4.2.0
TorchVision version: 0.10.0+cu111
tqdm version: 4.62.3
lmdb version: 1.2.1
psutil version: 5.8.0
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Linux
Linux version: Ubuntu 20.04.3 LTS
Platform: Linux-4.15.0-136-generic-x86_64-with-glibc2.10
Processor: x86_64
Machine: x86_64
Python version: 3.8.10
Process name: python
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: []
Num physical CPUs: 20
Num logical CPUs: 40
Num usable CPUs: 40
CPU usage (%): [10.3, 11.3, 11.3, 11.9, 9.5, 11.8, 100.0, 9.4, 12.6, 8.9, 11.3, 10.7, 10.1, 13.3, 13.2, 10.2, 10.7, 16.9, 9.6, 9.5, 11.5, 10.1, 11.3, 9.5, 11.9, 8.9, 9.4, 10.1, 16.9, 11.9, 9.5, 10.1, 10.7, 10.1, 10.1, 10.1, 10.7, 10.1, 10.3, 14.6]
CPU freq. (MHz): 1461
Load avg. in last 1, 5, 15 mins (%): [1.7, 2.8, 4.1]
Disk usage (%): 73.7
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 251.8
Available memory (GB): 237.8
Used memory (GB): 12.8

================================
Printing GPU config...
================================
Num GPUs: 4
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'sm_80', 'sm_86']
GPU 0 Name: Tesla V100-DGXS-32GB
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 80
GPU 0 Total memory (GB): 31.7
GPU 0 CUDA capability (maj.min): 7.0
GPU 1 Name: Tesla V100-DGXS-32GB
GPU 1 Is integrated: False
GPU 1 Is multi GPU board: False
GPU 1 Multi processor count: 80
GPU 1 Total memory (GB): 31.7
GPU 1 CUDA capability (maj.min): 7.0
GPU 2 Name: Tesla V100-DGXS-32GB
GPU 2 Is integrated: False
GPU 2 Is multi GPU board: False
GPU 2 Multi processor count: 80
GPU 2 Total memory (GB): 31.7
GPU 2 CUDA capability (maj.min): 7.0
GPU 3 Name: Tesla V100-DGXS-32GB
GPU 3 Is integrated: False
GPU 3 Is multi GPU board: False
GPU 3 Multi processor count: 80
GPU 3 Total memory (GB): 31.7
GPU 3 CUDA capability (maj.min): 7.0
```

**Additional context**
I installed the orthanc in DGX docker container.

Any suggestion and help is appreciated. Thank you

**Comment by SachidanandAlle** [comment]
There are two ways to solve this..
1. Disable authentication on Orthanc
2. If you have enabled authentication..  then pass username and password through env.. when you start MONAILabel
```export MONAI_LABEL_DICOMWEB_USERNAME=xyz
export MONAI_LABEL_DICOMWEB_PASSWORD=abc

monailabel start...
```
https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/config.py#L24

**Comment by Suchi97** [comment]
@SachidanandAlle Thanks for your reply. 
I tried the above mentioned steps. Like, I disabled the authentication in Orthanc. I did this by setting `AuthenticationEnabled = false`. 
For the second solution, the authentication was enabled and then executed `export MONAI_LABEL_DICOMWEB_PASSWORD=abc` in the terminal. 

But the above solutions resulted in the same issue that I mentioned in the description

**Comment by SachidanandAlle** [comment]
https://book.orthanc-server.com/faq/authentication.html

The above link might help.  Possibly you need to enable remote access.

The user option helps only if you have configured to Orthanc Access via user
The best way you can verify if all is ok is by accessing dicom-web directly using some web browser...

**Comment by Suchi97** [comment]
@SachidanandAlle , I tried the above solution also. I could implement the Orthanc server using the updated configuration json file. 

To run the OHIF Viewer, I need to run the `sudo service orthanc restart` command as per the [document](https://book.orthanc-server.com/users/debian-packages.html#replacing-the-package-from-the-service-by-the-lsb-binaries)
But when executing the above command, it reads the default configuration where the `RemoteAccessAllowed = false`.

I tried to edit the orthanc.json located in `/etc/orthanc/`. I thought that file is the default configuration but, changing that json file didn't resolve the issue.

Also I executed the command `Orthanc ./config.json` where config.json is the custom configuration file and then I run the 

`monailabel start_server --app apps/deepedit --studies http://127.0.0.1:8042/dicom-web`

It results the below error : 

Using PYTHONPATH=/opt:
USING:: app = /workspace/Hands_on_labs/MONAI_Label/apps/deepedit
USING:: studies = http://127.0.0.1:8042/dicom-web
USING:: username = None
USING:: password = None
USING:: wado_prefix =
USING:: qido_prefix =
USING:: stow_prefix =
USING:: debug = False
USING:: conf = None
USING:: host = 0.0.0.0
USING:: port = 8000
USING:: log_config = None
USING:: dryrun = False
USING:: action = start_server


**********************************************************
                  ENV VARIABLES/SETTINGS
**********************************************************
export MONAI_LABEL_API_STR=
export MONAI_LABEL_PROJECT_NAME=MONAILabel
export MONAI_LABEL_APP_DIR=/workspace/Hands_on_labs/MONAI_Label/apps/deepedit
export MONAI_LABEL_STUDIES=http://127.0.0.1:8042/dicom-web
export MONAI_LABEL_APP_CONF={}
export MONAI_LABEL_DICOMWEB_USERNAME=None
export MONAI_LABEL_DICOMWEB_PASSWORD=None
export MONAI_LABEL_QIDO_PREFIX=
export MONAI_LABEL_WADO_PREFIX=
export MONAI_LABEL_STOW_PREFIX=
export MONAI_LABEL_DATASTORE_AUTO_RELOAD=True
export MONAI_LABEL_DATASTORE_FILE_EXT=["*.nii.gz", "*.nii"]
export MONAI_LABEL_SERVER_PORT=8000
export MONAI_LABEL_CORS_ORIGINS=[]
**********************************************************

[2021-12-08 19:14:58,219] [MainThread] [INFO] (uvicorn.error:64) - Started server process [17412]
[2021-12-08 19:14:58,219] [MainThread] [INFO] (uvicorn.error:26) - Waiting for application startup.
[2021-12-08 19:14:58,219] [MainThread] [INFO] (monailabel.interfaces.utils.app:38) - Initializing App from: /workspace/Hands_on_labs/MONAI_Label/apps/deepedit; studies: http://127.0.0.1:8042/dicom-web; conf: {}
[2021-12-08 19:14:58,224] [MainThread] [ERROR] (uvicorn.error:89) - Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 540, in lifespan
    async for item in self.lifespan_context(app):
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 481, in default_lifespan
    await self.startup()
  File "/opt/conda/lib/python3.8/site-packages/starlette/routing.py", line 516, in startup
    await handler()
  File "/opt/conda/lib/python3.8/site-packages/monailabel/main.py", line 89, in startup_event
    instance = app_instance()
  File "/opt/conda/lib/python3.8/site-packages/monailabel/interfaces/utils/app.py", line 44, in app_instance
    c = get_class_of_subclass_from_file("main", main_py, "MONAILabelApp")
  File "/opt/conda/lib/python3.8/site-packages/monailabel/utils/others/class_utils.py", line 40, in get_class_of_subclass_from_file
    return get_class_of_subclass(module_from_file(module_name, file_path), class_c)
  File "/opt/conda/lib/python3.8/site-packages/monailabel/utils/others/class_utils.py", line 22, in module_from_file
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/workspace/Hands_on_labs/MONAI_Label/apps/deepedit/main.py", line 17, in <module>
    from lib import DeepEdit, DeepEditSeg, MyStrategy, MyTrain
  File "/workspace/Hands_on_labs/MONAI_Label/apps/deepedit/lib/__init__.py", line 14, in <module>
    from .train import MyTrain
  File "/workspace/Hands_on_labs/MONAI_Label/apps/deepedit/lib/train.py", line 42, in <module>
    from monailabel.tasks.train.basic_train import BasicTrainTask, Context
ImportError: cannot import name 'Context' from 'monailabel.tasks.train.basic_train' (/opt/conda/lib/python3.8/site-packages/monailabel/tasks/train/basic_train.py)`

`[2021-12-08 19:14:58,224] [MainThread] [ERROR] (uvicorn.error:35) - Application startup failed. Exiting.`



Is there a way to use custom configuration.json to run the orthanc server.

Thanks in advance.

**Comment by SachidanandAlle** [comment]
@aihsani can help you on this..

**Comment by SachidanandAlle** [comment]
@Suchi97 were you able to resolve this issue?

**Comment by SachidanandAlle** [comment]
Another thing.. which version of monailabel you are trying..? I suspect you are using 0;2 version.. And was giving solution based on 0.3

Because these args doesn't exist in 0.3 and were part of 0.2
USING:: username = None
USING:: password = None
USING:: wado_prefix =
USING:: qido_prefix =
USING:: stow_prefix =

In that case, if you still want to user 0.2 version.. then the correct way to pass username and password is
`monailabel start_server --app apps/deepedit --studies http://127.0.0.1:8042/dicom-web --username orthanc --password orthanc`

**Comment by Suchi97** [comment]
> @Suchi97 were you able to resolve this issue?
> 
> The latest error says something different.. some PIP package/env issue.. earlier you were able to run everything but not able to use OHIF as it was requesting for auth.. but now some import error..
> 
> Just to isolate the env problem vs orthanc.. have you tried with few images in folder.. and used 3D slicer instead of OHIF.. to run e2e functionality

@SachidanandAlle  MONAI Label using with 3D Slicer works fine. In 3D Slicer, I could able to load and then annotate the images.

The issue with the OHIF viewer is not resolved.

**Comment by Suchi97** [comment]
> If you want to run orthanc.. with own config.. you can do so.. first you can stop the service.. and then run orthanc binary (Orthanc).. https://book.orthanc-server.com/users/configuration.html#configuration
> 
> But if you have already auth configured and you are not able to disable.. what is the username and password? I believe default is orthanc and orthanc
> 
> but what we have used day-in-day-out.. you can always configure username and password.. and send it to monailabel server..
> 
> ```
> export MONAI_LABEL_DICOMWEB_USERNAME=orthanc
> export MONAI_LABEL_DICOMWEB_PASSWORD=orthanc
> 
> monailabel start_server --app apps/deepedit --studies http://127.0.0.1:8042/dicom-web
> ```
> 
> In the start logs.. actually these flags are printed for debug reasons.. you should see them instead of `None` You should be able to use this username when you access http://<my_ip>:8042/app/explorer.html (instead of localhost)

I tried these steps, but this didn't resolve the issue.

**Comment by Suchi97** [comment]
> Another thing.. which version of monailabel you are trying..? I suspect you are using 0;2 version.. And was giving solution based on 0.3
> 
> Because these args doesn't exist in 0.3 and were part of 0.2 USING:: username = None USING:: password = None USING:: wado_prefix = USING:: qido_prefix = USING:: stow_prefix =
> 
> In that case, if you still want to user 0.2 version.. then the correct way to pass username and password is `monailabel start_server --app apps/deepedit --studies http://127.0.0.1:8042/dicom-web --username orthanc --password orthanc`

When I post this issue, I used the version 0.2.0.
I also tried to authenticate the orthanc server in version 0.3.0. But the issue exists in both cases.

**Comment by SachidanandAlle** [comment]
Either disable authentication in Orthanc or pass the correct username and password to monailabel while starting the server..

**Comment by SachidanandAlle** [comment]
@diazandr3s  see if you can help..

**Comment by Suchi97** [comment]
@SachidanandAlle Can you please help me to disable the authentication in Orthanc. Like, how can I disable the authentication in Orthanc.

**Comment by SachidanandAlle** [comment]
I am on vacation... so asking some one to help u.. remove currect Orthanc.. and try installing Orthanc from a docker or in another box.. not able to guess what is wrong with your Orthanc..

**Comment by Suchi97** [comment]
Thanks @SachidanandAlle for your suggestions.

**Comment by diazandr3s** [comment]
Hi @Suchi97, could you please re-install Orthanc following [these recommendations](https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif) and tell us how that goes?

**Comment by Suchi97** [comment]
Sure @diazandr3s. Let me try [this](https://github.com/Project-MONAI/MONAILabel/tree/main/plugins/ohif) and I will let u know

**Comment by aihsani** [comment]
You can also check whether things are working for you with dicomweb using
```
curl -X GET -H "accept: */*" -u orthanc:orthancpass http://localhost:8042/dicom-web/studies
```

**Comment by Suchi97** [comment]
@aihsani @SachidanandAlle @diazandr3s Thanks for your suggestions.
@aihsani Thanks for your detailed description.

I reinstalled the orthanc application and then edited the configuration files (`/etc/orthanc/orthanc.json and /etc/orthanc/dicomweb.json`) as @aihsani 's comment.

Now I am able to authenticate the orthanc server. Its working fine. 
Thanks again for your great help.

**Comment by SachidanandAlle** [comment]
Updated the docs to have details on how to set user credentials while starting orthanc/dicomweb
https://docs.monai.io/projects/label/en/latest/installation.html#ohif-plugin

**Comment by diazandr3s** [comment]
Hi @patricio-astudillo,

Here is a possible solution to the authentication issue in Orthanc. Please let us know what you get after following the instructions.

**Comment by patricio-astudillo** [comment]
Hi @diazandr3s,
the issue has been resolved thanks to the documentation which I found online.
Thanks
