### ISSUE TITLE
Add project citation instructions

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#559]
Does it make sense to add a "How to cite?" link in the readme?
Or perhaps we can use github's citation tools (https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files)

Or maybe the citation to project MONAI can be used here as well (https://github.com/Project-MONAI/MONAI/blob/dev/CITATION.cff), in which case we need to link it so it shows up in this github repo.

**Comment by SachidanandAlle** [comment]
Please add CITATION.cff file (same as monai and raise a PR).. lets get it added to monai label and keep it same as monai for now.. except repository
