### ISSUE TITLE
Documentation is misleading about OS Support

### ISSUE THREAD

**Issue by JHancox** [Project-MONAI/MONAILabel#562]
**Describe the bug**
The documentation implies that Windows is the only supported platform for MONAI Label. Under Prerequisites, it lists Windows and no other OS. Users have reported that they wished to have support for other OSs - at which point the issue became apparent.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to https://docs.monai.io/projects/label/en/latest/installation.html'
2. Note that, in the panel on the right, under Prerequisites, it just lists 'Windows'. It also says "MONAI Label supports following OS with GPU/CUDA enabled:" and then only Windows is mentioned.

**Expected behavior**
The documentation should be explicit about which OSs are supported and the installation steps that apply to each OS.

**Comment by SachidanandAlle** [comment]
@diazandr3s 

Can u please fix this line..
`MONAI Label supports following OS with GPU/CUDA enabled`

To 

MONAI Label supports both *Ubuntu and Windows OS* with GPU/CUDA enabled

**Comment by diazandr3s** [comment]
Thanks, @JHancox. 
I just updated that bit :)

**Comment by jamesobutler** [comment]
> MONAI Label supports both Ubuntu and Windows OS with GPU/CUDA enabled

Is Ubuntu the only Linux distro that is supported? Or is it that the MonaiLabel team officially supports "Windows", but that it may also work on other platforms with GPU/CUDA enabled where "Ubuntu" is just one of the many other platforms where it may work?

**Comment by diazandr3s** [comment]
Thanks for your question, @jamesobutler.
MONAI Label officially supports both Linux and Windows OS. This means researchers/clinicians can use MONAI Label on any Linux operating system or Windows with GPU/CUDA enabled.

Please don't hesitate to open/report any issue you may find using MONAI Label on any of these operating systems :)

**Comment by jamesobutler** [comment]
Ok clarification that it isn't just Ubuntu, but Linux in general would be appreciated.

**Comment by jamesobutler** [comment]
It is e114d49be556c452635a21c70ac4b0f3d1a28143 that is confusing in that is says specifically Ubuntu support rather than Linux in general.

**Comment by SachidanandAlle** [comment]
officially it's not tested or verified on other Unix versions... ideally it should work..

**Comment by SachidanandAlle** [comment]
Currently all the official releases are verified for ubuntu and Windows...

If you can verify on other Linux distributions.. we can add a note in the docs..

**Comment by jamesobutler** [comment]
Are there specific versions of Ubuntu and Windows that are supported? Is both Windows 11 and 10 supported? Or only Windows 10? Windows 8.1/7?

**Comment by SachidanandAlle** [comment]
Windows 10/11.. Ubuntu 20.x

**Comment by jamesobutler** [comment]
Good to know! Thanks!
