### ISSUE TITLE
Documentation of Slicer plugin is too sparse

### ISSUE THREAD

**Issue by SlicerMorph** [Project-MONAI/MONAILabel#564]
At this point, Slicer extension of MonaiLabel only explains how to install the extension and leaves there for the user to figure out how to use the tools. 

I would suggest explanation of the buttons, their functionality, and possibly a step-by-step tutorial with one of the toy datasets (e.g., spleen). 

Also, from the documentation it is not clear whether the same server can be used by the two different clients for the same segmentation tasks simultaneously. How does the server handle concurrency (of the tasks, and the apps).

**Comment by SachidanandAlle** [comment]
We have some limited document for user to explain slicer related activities.. 

MONAI Label Demo - https://youtu.be/o8HipCgSZIw?t=1319

https://docs.monai.io/projects/label/en/latest/quickstart.html#install-monai-label-plugin-in-3dslicer

**Comment by SachidanandAlle** [comment]
Please feel free to add more details that can help others to follow.. its an open source.. so your contributions will be helpful..

https://github.com/Project-MONAI/MONAILabel/blob/main/CONTRIBUTING.md

**Comment by SachidanandAlle** [comment]
More details on plugin are added
https://docs.monai.io/projects/label/en/latest/quickstart.html#install-monai-label-plugin-in-3d-slicer

You can also check for demo videos:
https://github.com/Project-MONAI/MONAILabel#sample-apps-in-monailabel
