### ISSUE TITLE
Azure pipeline is not stable

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#575]
Due to OS updates etc on the node... many times the job keep failing..

https://dev.azure.com/projectmonai/monai-label/_build?definitionId=10&_a=summary

It shall be better to run the builds on a docker instance.. (ubuntu 20x)

**Comment by aihsani** [comment]
@evberrypi let's talk about this since it seems `apt` faces issues when running on the VM when there updates... w should think about using a container. Perhaps we can use `project-monai/monai:latest`

**Comment by evberrypi** [comment]
Can't reproduce. 
Adjusted some settings on the Azure side to ensure that the VM gets destroyed and not ran on the next job, but was unable to trigger the apt error you saw.

**Comment by SachidanandAlle** [comment]
The current one is failed

**Comment by evberrypi** [comment]
Let's add a task for 0.4.0 to move the CI from Azure Devops to Blossom.
Reasoning:
- Monai Core has done it
- Blossom can handle it now
- We need to do the same thing with Label
Thoughts @SachidanandAlle, @aihsani

**Comment by SachidanandAlle** [comment]
Similar problems again:
https://dev.azure.com/projectmonai/monai-label/_build/results?buildId=879&view=results

https://dev.azure.com/projectmonai/monai-label/_build/results?buildId=880&view=logs&j=97ddd399-bfa5-5e5e-4b0a-84a6e98cad07

@evberrypi 
Time to move to Blossom?

**Comment by SachidanandAlle** [comment]
Manual Retry on failure works for now.. we can retry failed jobs (stuck due to resource scheduling) to unblock and finish the workflow/pipeline...
