### ISSUE TITLE
Pathology Annotation - Clients Evaluation

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#581]
Evaluate and do some feasibility study for possible Clients/Viewers to develop monai label plugin

- QuPath
- Opensea Dragon
- NuClick
- Others

**Comment by SachidanandAlle** [comment]
NuClick is an example implementation of one of interaction type segmentation https://arxiv.org/abs/2005.14511

https://github.com/navidstuv/NuClick
The implementation covers only to train and run basic inference.. and it uses keras

**Comment by SachidanandAlle** [comment]
Opensea Dragon is not much useful.  It is majorly view only.. based on JS.. not much support for manual annotation etc..
https://openseadragon.github.io/

The closest possibly toolbar for creating annotation is: https://github.com/Emigre/openseadragon-annotations

**Comment by SachidanandAlle** [comment]
QuPath looks more promising with functionalities.. It comes with basic AI support to run classification at cell/object level.  These models are predefined.  It has possible rich set of toolbar options for manual annotators...

I see currently QuPath has the best possible choice..  @pdogra89 please check with others and confirm if we are good to with QuPath as default choice for MONAI Label plugin to support annotations for pathology

**Comment by SachidanandAlle** [comment]
https://github.com/CSAILVision/LabelMeAnnotationTool  is another possible option..

**Comment by lassoan** [comment]
Check out napari (https://napari.org/).

**Comment by lassoan** [comment]
See also Slim (https://github.com/MGHComputationalPathology/slim). As I heard, it is kind of OHIF for pathology.

**Comment by SachidanandAlle** [comment]
https://computationalpathologygroup.github.io/ASAP/

**Comment by SachidanandAlle** [comment]
Digital Slide Archive:
=============
UI: https://github.com/DigitalSlideArchive/HistomicsUI
Plugin: https://github.com/DigitalSlideArchive/HistomicsTK
Example: [Nuclear segmentation using kofahi's method.](https://github.com/DigitalSlideArchive/HistomicsTK/blob/master/histomicstk/segmentation/nuclear/detect_nuclei_kofahi.py])

Demo: [Public Hosted](https://demo.kitware.com/histomicstk/histomicstk#?image=5bbdee4fe629140048d01adf&bounds=24890%2C19072%2C44467%2C29237%2C0)

Docker Compose: https://github.com/DigitalSlideArchive/digital_slide_archive/tree/master/devops/dsa
