### ISSUE TITLE
info.yaml returns a 404 from deepgrow sample app

### ISSUE THREAD

**Issue by srib** [Project-MONAI/MONAILabel#585]
Link referring to [info.yaml](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepgrow/info.yaml) in [README.md](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepgrow/README.md) for [deepgrow](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/deepgrow) sample app is missing.

**Comment by SachidanandAlle** [comment]
Readme needs some update.. there is no info.yaml... latest version of app consists all confois as part of app code rather than code and yaml..

**Comment by srib** [comment]
Thanks, @SachidanandAlle!

Happy to make a PR to fix it.

**Comment by SachidanandAlle** [comment]
> Thanks, @SachidanandAlle!
> 
> Happy to make a PR to fix it.

Awesome 👍
