### ISSUE TITLE
Usage of SmartEdit

### ISSUE THREAD

**Issue by j-sieger** [Project-MONAI/MONAILabel#590]
* I have labelled 6 images and trained model for 5 epochs. Then stopped training.
* Now ran inference on new image. It has wrongly segmented a lot.
* So now i want to correct those.

**Query::**
Whether i should use only SmartEdit/DeepGrow   -ve clicks or i can use scribbles and paint that part as background ?

**Because::**
As there is a lot of area to be corrected, if I use SmartEdit/DeepGrow   **-ve clicks**. It will take lot of time to correct.
Instead I can use **scribbles** and mark those extra parts as back ground.

_But i am not sure using **scribbles is right approach or not** ._ 

Please help with this query.

**Comment by diazandr3s** [comment]
Hi @j-sieger,

As you said, you could either use manual tools in Slicer to modify the predicted label or scribbles. 
Training only for 5 epochs on 6 labels might be little on your dataset. You could always leave the training for more epochs or discard the predicted label and create one from scratch using Scribbles. See this part of the video: https://youtu.be/o8HipCgSZIw?t=1331

Out of curiosity, which organ are you trying to segment? How many labels per image?

**Comment by diazandr3s** [comment]
Superb!! I'm closing this issue. 
Please feel free to open a [discussion](https://github.com/Project-MONAI/MONAILabel/discussions) if you need more help with this.
Thanks!!
