### ISSUE TITLE
Scribbles only contains foreground/background

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAILabel#607]
I'm working on multilabel segmentation. 

All of the labels are displayed in the deepgrow panel:

![image](https://user-images.githubusercontent.com/33289025/152505272-5052436c-29b0-44a6-a809-a96a86ce7757.png)

But only foreground and background are displayed in the Scribbles panel:

![image](https://user-images.githubusercontent.com/33289025/152504782-6722be28-508c-461d-b24d-960ee3d8e9b5.png)

Is there any way to do multilabel scribbles?

**Comment by SachidanandAlle** [comment]
@masadcv - Like SmartEdit, you can list the labels.. allow the single operation/scribbles at a time.. the result can be updated over selected label.. User can repeat the operation N times without changing the label selection.. this way user can annotate one label at a time.. without much code changes.. 

In later stages, you can allow to save the previous foreground/background when user selects a different label..

**Comment by masadcv** [comment]
@SachidanandAlle thanks for the input. I will look into this in coming days. One major difference of this from click-based methods is that you can have a full segmentation volume with multiple labels, which may be easier to do multilabel as you will just end up adding interactions to the segmentation volume.

On the server side, we need to update transforms to handle multilabel. Currently, employed Histogram+GraphCut may not be insufficient for multilabel problems - we may need to replace GraphCut with CRF.

**Comment by masadcv** [comment]
The latest version (current main) now contains a solution to multi-label scribbles.
See: #717 and related #731

@rijobro can you please test scribbles now with your use-case - let me know if you spot any issues with multilabel scribbles.

I am marking this as resolved for now

**Comment by rijobro** [comment]
@masadcv thanks for this! I can't test as I'm currently doing research that doesn't use MONAI Label, but will feedback if there are any issues when I'm next using it.
