### ISSUE TITLE
Training progress incorrect

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAILabel#611]
Training progress bar shows as 100%, Training: DONE

![image](https://user-images.githubusercontent.com/33289025/152562443-e716e062-ce7d-462a-93b9-76ae7e2fe39c.png)

Whilst the log accurately shows that it's on epoch 2/50:

![image](https://user-images.githubusercontent.com/33289025/152562585-9814c66b-b903-4963-923c-e36192114c0a.png)

Edit: Reloading the connection to the server seems to solve this, but resets the parameters (cf https://github.com/Project-MONAI/MONAILabel/issues/612).

**Comment by SachidanandAlle** [comment]
For 1st epoch complete there is a math error in the client side to determine epoch.  Kind of known bug which needs to be fixed.
However for 2nd epoch complete (auto refresh happens every 10 sec at the client side.. if i remember).. the status bar gets corrected.. during the 10 sec refresh gap anything happens at the server are not reflected in the client.. or if you are using multiple clients this kind of sync issue also might exists..

agreed.. this issue can be fixed and things can look better at the slicer client..

**Comment by SachidanandAlle** [comment]
please try the latest version.  it comes with bunch of ui fixes.. please feel free to reopen the issue if problem persists
