### ISSUE TITLE
Documentation of `--conf`

### ISSUE THREAD

**Issue by rijobro** [Project-MONAI/MONAILabel#613]
Documentation detailing the possible choices of `--conf` would be useful. I'd like to set the default to be `PersistentDataset`, which I tried with `-c dataset PersistentDataset` and `-c dataset_type PersistentDataset`. Neither are used, but neither throw an error, so it's hard to know what the correct parameters to be used are.

**Comment by SachidanandAlle** [comment]
--conf is designed to have any user options to pass it to their app.. 

In your example when  `-c dataset_type XYZ` is passed, you should be able to access it through in 2 ways.

1. In your app main.py  `conf` argument to your App init method (for example: https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepedit/main.py#L41)
2. During app life-cycle if you want to access, you can always get `app.conf` https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/interfaces/app.py#L61


Any user who wants to create their app might need some command line args to control their app behavior.  In such case, user can use --conf option.  So these are mostly meant for user to control their app features/behavior etc..

Another example can be.. user might be supporting multiple models for the same training definition.. and he wants to start his app for one of them without code changes.. like `monailabel start_server -a myapp -s xyz -c mymodel UNET`

Agreed.  Documentation should highlight this and show some example.

**Comment by rijobro** [comment]
I understand, thanks for the explanation!

**Comment by SachidanandAlle** [comment]
you might be looking for this: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/radiology#list-of-pretrained-models

In case of scribbles.. it's always enabled.. you can go to 3D Slicer and under scribbles section you should see only one option so far..

**Comment by diazandr3s** [comment]
Hi @themantalope,

Thanks for commenting on this. You're right, there is a gap in the documentation for this.

We're working on first "standardizing" this flag for the coming MONAI Label functionalities and then creating a short video showing the different options.

In the meantime, I'd recommend you to check what @SachidanandAlle pointed out and also these lines: https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/main.py#L38-L84

Thanks again!

**Comment by themantalope** [comment]
> you might be looking for this: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/radiology#list-of-pretrained-models
> 
> In case of scribbles.. it's always enabled.. you can go to 3D Slicer and under scribbles section you should see only one option so far..

This was very helpful!

**Comment by SachidanandAlle** [comment]
Documentation is updated/added for each of the app where it defines certain `--conf` options
For example: https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/radiology#deepedit
