### ISSUE TITLE
README.md in sample-apps has a broken link

### ISSUE THREAD

**Issue by srib** [Project-MONAI/MONAILabel#622]
Link for [deepgrow for left atrium segmentation](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepgrow_left_atrium) returns a 404 from this [section](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps#deepgrow). 

It should point to [this](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/segmentation_left_atrium).

**Comment by SachidanandAlle** [comment]
that's right.. It's not more available... 
only these apps are supported..

https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps

**Comment by srib** [comment]
Thanks, @diazandr3s! Trying to play around with this excellent tool and reporting issues as I discover them. :)

**Comment by diazandr3s** [comment]
Superb! Please let us know anything you find :)
Closing this issue with PR https://github.com/Project-MONAI/MONAILabel/pull/624
