### ISSUE TITLE
`generic_deepgrow` does not exist from `README.md` in `sample-apps` directory

### ISSUE THREAD

**Issue by srib** [Project-MONAI/MONAILabel#623]
`monailabel apps --name generic_deepgrow --download --output myapp` returns a message on the terminal saying the following:

```bash
Using PYTHONPATH=/opt:
App generic_deepgrow => /opt/conda/monailabel/sample-apps/generic_deepgrow not exists
```

Should it be the following?

`monailabel apps --name deepgrow --download --output myapp`

**Comment by diazandr3s** [comment]
Thanks, @srib. You're right, it should be `deepgrow` only. 

BTW, where did you find the command `monailabel apps --name generic_deepgrow --download --output myapp`?

**Comment by srib** [comment]
@diazandr3s In `README.md` from [here](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/deepgrow/README.md).

**Comment by diazandr3s** [comment]
Thanks again, @srib :)

Just created a PR https://github.com/Project-MONAI/MONAILabel/pull/627 for this. Closing this issue.
