### ISSUE TITLE
Is active learning working in MONAILabel?

### ISSUE THREAD

**Issue by patricio-astudillo** [Project-MONAI/MONAILabel#636]
**Describe the bug**
I have detected an unwanted behaviour on monailabel (and monailabel-weekly). I'm using the deepedit app connected to an orthanc server where there are a number of patients with (18) and without (3) segmentation. Whenever I would like to select a 'next sample', the following screen appears:

![image](https://user-images.githubusercontent.com/7931855/154290569-d1879657-1bc1-4004-9c7e-30240df7ba89.png)

I can not edit any field and whenever I click on 'ok', a crash occurs and an error message is shown:

![image](https://user-images.githubusercontent.com/7931855/154290789-928640b1-3c21-4e71-a9b5-ef93b6975688.png)

I have already established the bug with @diazandr3s and he advised me to report this in a bug report.

**Comment by SachidanandAlle** [comment]
It looks like it couldn't fetch any meta/info for all the images/studies which were not annotated.

The best way to check is use http://127.0.0.1:8000/dataset?output=all  (you can use http://127.0.0.1:8000/  (and in dataset try option)

Is all the 18 images/series listed here?  or is there some mandatory field missing.. like study id etc..?

**Comment by SachidanandAlle** [comment]
any updates?

**Comment by patricio-astudillo** [comment]
Yes, I checked this with @diazandr3s and we came to the conclusion that the dataset did not contain any series without labels. So if there are no 'empty' series initially (or anymore (but this needs to be checked)), the error occurs.

**Comment by SachidanandAlle** [comment]
possibly some check can be added in ohif

**Comment by SachidanandAlle** [comment]
please try the latest version.  it comes with bunch of ui fixes.. please feel free to reopen the issue if problem persists
