### ISSUE TITLE
Using DICOM images with MONAI

### ISSUE THREAD

**Issue by j-sieger** [Project-MONAI/MONAILabel#638]
Hi team,

Is there any way to load DICOM images with MONAI server and use it for labelling?

Generally the nifti images which i have in the ec2 server. i will load them using MONAI while starting the server using below command 
`monailabel start_server --app apps/deepedit --studies datasets/Task02_Heart/imagesTr --conf epistemic_enabled true`

But similar approach is not working for DICOM images. When i click on fetch next image in the 3d slicer. It raising exception as no images found.

from the logs i could see that it is expecting images of only these formats `['*.nii.gz', '*.nii', '*.nrrd']`

**Please let me know is there any way to use my DICOM images.**

Thanks&Regards,
Jani Basha S.

**Comment by j-sieger** [comment]
I have converted dicom to nifti to resolve my issue

**Comment by SachidanandAlle** [comment]
For DICOM u need Orthanc kind of DICOM Web server.. please check the ohif related section in the docs

**Comment by diazandr3s** [comment]
Thanks for sharing this @j-sieger. Please don't hesitate to ask for help if needed :)

**Comment by GhTara** [comment]
> I have converted dicom to nifti to resolve my issue

Hello @j-sieger, I face this issue too.
Excuse me how do you convert DICOM to NIFTI? I am new to this. I have a dataset containing DICOM files that every file devoted to a patient.

**Comment by diazandr3s** [comment]
Hi @GhTara,

You may find this useful:

- https://github.com/icometrix/dicom2nifti
- If it is a small number of images:
Load the image in [3D Slicer](https://download.slicer.org/) and then save it in NIFTI OR https://www.onlineconverter.com/dicom-to-nifti

**Comment by j-sieger** [comment]
Hi @GhTara ,
For converting dicom to nifti u can follow the links provided by @diazandr3s .
But i had 60 to 80 slices of dicom files for each patient. But in your case u have only 1 file per patient. Not sure how will it look like in 3d space with single slice

**Comment by GhTara** [comment]
> Hi @GhTara,
> 
> You may find this useful:
> 
> * https://github.com/icometrix/dicom2nifti
> * If it is a small number of images:
>   Load the image in [3D Slicer](https://download.slicer.org/) and then save it in NIFTI OR https://www.onlineconverter.com/dicom-to-nifti

Many Thanks, @diazandr3s . by the first link, I did it.
