### ISSUE TITLE
Using DICOM images with MONAILabel

### ISSUE THREAD

**Issue by j-sieger** [Project-MONAI/MONAILabel#639]
Hi team,

Is there any way to load DICOM images with MONAI server and use it for labelling?

Generally the nifti images which i have in the ec2 server. i will load them using MONAI while starting the server using below command 
`monailabel start_server --app apps/deepedit --studies datasets/Task02_Heart/imagesTr --conf epistemic_enabled true`

But similar approach is not working for DICOM images. When i click on fetch next image in the 3d slicer. It raising exception as no images found.

from the logs i could see that it is expecting images of only these formats `['*.nii.gz', '*.nii', '*.nrrd']`

**Please let me know is there any way to use my DICOM images.**
 Thanks

**Comment by diazandr3s** [comment]
Same issue as this https://github.com/Project-MONAI/MONAILabel/issues/638
Closing issue
