### ISSUE TITLE
Slicer plugin: app name should be static text, not dropdown.

### ISSUE THREAD

**Issue by pwrightkcl** [Project-MONAI/MONAILabel#655]
Like the title said. Since the app is set when starting the server, and multiple apps are not supported, the Slicer plugin should not show a dropdown for the model name, but just fixed text.

(Omitting usual details as this is UI feedback, not a crash report).

**Comment by SachidanandAlle** [comment]
initial plan was to support multiple apps per server.. so u see only one item in the combo box.. the currently we are not thinking of deploying multiple apps per server.. may be a future item..

**Comment by SachidanandAlle** [comment]
if you are looking model name (under smartedit/autosegmentation.. they can be as many.. so it is a dropdown for user to select)

**Comment by pwrightkcl** [comment]
I was talking specifically about model name. It's just a bit confusing to the user to see a drop down when there will only be a single option. Perhaps make it static until you add support for multiple apps to the server, then change the plugin UI back to a drop down? Maybe that's too much hassle. I just wanted to log an issue to it could be decided in the proper place.

**Comment by SachidanandAlle** [comment]
please try the new plugin version.  it comes with bunch of ui fixes and improvements.
feel free to raise or re/open an issue for further comments
