### ISSUE TITLE
Using napari for GUI ?

### ISSUE THREAD

**Issue by vfdev-5** [Project-MONAI/MONAILabel#67]
I was wondering if it was already considered to using napari tools for UI in the plugins ?

For example, https://github.com/napari/magicgui looks interesting to create widgets from functions...

**Comment by SachidanandAlle** [comment]
Thanks for sharing about napari.  Currently have limited scope for client sided integrations.

We picked 3D Slicer (which is quite famous tool with large set of features, plugins and open-source community) as an example to demonstrate e2e functionality for MONAI Label.  Actually this time we took one step ahead and doing the reference implementation for client-sided plugin.

In later stages, we would like to showcase this as reference to bring in other open source viewers/developers to integrate with MONAILabel.  Please note, MONAILabel doesn't have any UI of it's own.  It provides endpoints for client sided UI applications to integrate along with their existing features/functionalities to make use of AI features provided through MONAILabel.  In future if we are need to create UI widgets as part of MONAILabel, we can definitely evaluate magicgui option (which is abstracted over QT).

Adding @pdogra89
