### ISSUE TITLE
3D Slicer doesn't support downloading https uri

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#692]
https://github.com/Slicer/Slicer/blob/master/Modules/Scripted/SampleData/SampleData.py#L854

It doesn't handle https resources

**Comment by SachidanandAlle** [comment]
@jamesobutler do you have any better approaches to fix this issue.. ?

**Comment by jamesobutler** [comment]
@SachidanandAlle Can you provide a small code example to run in the latest Slicer Preview build that produces the error that you’re interested in? An issue with the Slicer SampleData module not able to download volumes with an https url?

**Comment by SachidanandAlle** [comment]
That's correct.. just sampledata module.. 
not able to download from https uri.. you can give quick try in python interpreter.. using the sampledata-> downloadfromurl api

**Comment by jamesobutler** [comment]
Using the SampleData module's `downloadFile` method appears to work for https downloads
```
Python 3.9.10 (main, Apr 17 2022, 23:27:33) [MSC v.1930 64 bit (AMD64)] on win32
>>> import SampleData
>>> filepath=SampleData.SampleDataLogic().downloadFile("https://github.com/Slicer/SlicerTestingData/releases/download/SHA256/cc211f0dfd9a05ca3841ce1141b292898b2dd2d3f08286affadf823a7e58df93", "C:/Users/JamesButler/Downloads", "MR-Head.nrrd", checksum="SHA256:cc211f0dfd9a05ca3841ce1141b292898b2dd2d3f08286affadf823a7e58df93")
>>> import os
>>> os.path.exists(filepath)
True
>>> 
```

**Comment by SachidanandAlle** [comment]
Try when the cert is not verified (kind of localhost ssl)

**Comment by lassoan** [comment]
SSL certificates are complicated and solutions may be OS (and even flavor and configuration) dependent.

What operating system do you have problem on? Can you give a minimal example to reproduce?

**Comment by SachidanandAlle** [comment]
It works... I can confirm by running monailabel server in https mode..
`SampleDataLogic().downloadFile` is all ok.. the problem is in client for POST request to negotiate handshake..

```
Check if file exists/shared locally: /localhome/sachi/Datasets/Radiology/image.nii.gz => False
https://10.117.16.216:8000/datastore/image?image=image
Time consumed by next_sample: 4.7
```
