### ISSUE TITLE
MONAILabel extension is not found in Qupath application.

### ISSUE THREAD

**Issue by j-sieger** [Project-MONAI/MONAILabel#710]
Dear MONAI label team,

I have installed the QuPath software but there is no 'MONAI Label' extension in the software.

Please let me know steps to add it. or any other version of the software needs to be installed.

<img width="650" alt="image" src="https://user-images.githubusercontent.com/9985334/160828252-665152dd-7a21-4444-8a29-0f98a1efa37b.png">

Thanks,
Jani Basha S.

**Comment by diazandr3s** [comment]
Hi @j-sieger,

Thanks for opening this issue.
Prototype QuPath for MONAI Label should be installed from https://github.com/SachidanandAlle/qupath
Once installed, build and run QuPath. Then follow the next steps:

1. Open sample wsi image from sample_wsi (shared with MONAILabel)
2. Ctrl + CLick on some area of Image to add MONAI specific ROI
3. Resize ROI if needed
4. Menu -> MONAILabel -> Run


More information can be found [here](https://github.com/Project-MONAI/MONAILabel/tree/main/sample-apps/pathology)

Please let us know how that goes.

**Comment by SachidanandAlle** [comment]
Pathology app is underway.. and qupath is not in the roadmap.. as its opensource we r looking for contributions from community to get it done.. 

https://github.com/Project-MONAI/MONAILabel/discussions/599

**Comment by j-sieger** [comment]
Thanks @SachidanandAlle 
I will work on it.

**Comment by j-sieger** [comment]
Building from source is failing with below error.

```
> Task :qupath-extension-monailabel:compileJava FAILED
C:\Users\Sunkara Jani Basha\Quantiphi\QuPath_build\qupath\qupath-extension-monailabel\src\main\java\qupath\lib\extension\monailabel\Command.java:147: error: package com.google.common.io does not exist
                        String image = com.google.common.io.Files.getNameWithoutExtension(imageData.getServerPath());
                                                           ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':qupath-extension-monailabel:compileJava'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 21s
26 actionable tasks: 13 executed, 13 up-to-date
```

**Comment by SachidanandAlle** [comment]
i guess some latest java version directly provide guava library..
For example, when I use I don't see need to add extra dependency

```
java --version
openjdk 17.0.1 2021-10-19
OpenJDK Runtime Environment Temurin-17.0.1+12 (build 17.0.1+12)
OpenJDK 64-Bit Server VM Temurin-17.0.1+12 (build 17.0.1+12, mixed mode, sharing)
```

Either you can install the needed jar/library and add into your jre/java path or simply use openjdk that comes with guava library
https://mvnrepository.com/artifact/com.google.guava/guava

**Comment by j-sieger** [comment]
I have installed latest version of java 

```
openjdk 17.0.2 +8             64 bit
```

**Comment by SachidanandAlle** [comment]
![image](https://user-images.githubusercontent.com/7339051/161724902-4ef83b2b-1eec-4213-8b21-833442215988.png)

**Comment by SachidanandAlle** [comment]
I see it's coming from project external dependency..

![image](https://user-images.githubusercontent.com/7339051/161725803-364bbb36-52d9-418f-9f8d-8d6fdd0b5386.png)
