### ISSUE TITLE
Feature proposal: MONAILabelReviewer

### ISSUE THREAD

**Issue by DaoMaoDuc** [Project-MONAI/MONAILabel#722]
In our Berlin working group we have now been able to create some valuable data sets with MONAILabel. All in all it was a very good experience to switch to MONAILabel.

As we work with radiologists of different levels of experience, we saw the need to develop a review tool for MONAILabel that allows for easy visualization, assessment and quality assurance of the acquired datasets.

@jlvahldiek and I developed MONAILabelReviewer, a 3D slicer extension based on MONAILabel. It is a tool that allows for quality control, scoring and easy browsing of annotated datasets and easy search for specific cases. The goal of MONAILabelReviewer is to become a comprehensive review tool that helps in the creation of very high-quality datasets through MONAILabel.

We would like to introduce this tool to the MONAI community and ask if there is a general interest in this tool. Is there interest in further developing this tool together and possibly integrating it into MONAILabel?

I would like to attach the following two images, which illustrate the functionality of the reviewing tool:

![distributedWork_v2](https://user-images.githubusercontent.com/30056369/161481057-f34feb60-0daf-4f49-a02f-c479f3099f2d.png)

![UiReviewerMode_without_image](https://user-images.githubusercontent.com/30056369/161481095-794171b1-a4f7-4558-b206-9e40b9ac11fe.png)

**Comment by SachidanandAlle** [comment]
This is really we wanted to happen when we started this open source project.. better ideas and more contributions 😀

Lets have a discussion on possibly you guys can give a small presentation/demo which can help to understand more about reviewer.. lets include couple of more stakeholders so that we can shape it to next possible deliverables 

@pdong (pm for monailabel)

**Comment by diazandr3s** [comment]
This is great, @DaoMaoDuc @jlvahldiek :)
As @SachidanandAlle suggested, let's meet and talk more about this. 

CC @pdogra89

**Comment by SachidanandAlle** [comment]
@diazandr3s is trying to reach out to setup a meeting..

**Comment by lassoan** [comment]
I world be interested in the demo, too. If you send me the meeting time and link then I'll try to join. Thank you!

**Comment by dtruhn** [comment]
Great work, thank you very much! This is really what is missing - at our hospital, labelling is often done by students, but you need some kind of quality control by experienced physicians. MONAILabelReviewer would make that possible - very important contribution!

**Comment by LilianaCaldeira** [comment]
Dear all, 

We (Radiology UK Köln) are also very interested in this! In our department, we would like to do reviewing of cases by more experiences colleagues. My team and I would be interested in a demo too.

Thank you in advance,
Liliana Caldeira

**Comment by DaoMaoDuc** [comment]
Hi, everyone.
Sorry for the delay in submitting the MONAILabelReviewer extension.
I'm still working on the unit sets to achieve high test coverage on the code.
