### ISSUE TITLE
SimpleCRF license issues

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#726]
We just noticed that SimpleCRF depends on Yuri Boykov's implementation of maxflow for graphcuts (see: https://github.com/HiLab-git/SimpleCRF/tree/master/dependency/maxflow-v3.0) which is coming from here: https://pub.ist.ac.at/~vnk/software.html

This dependency has a GPL license which may be incompatible with MONAI's licenses and hence it maybe a good idea to remove any dependencies on SimpleCRF for the time being. 

cc: @tvercaut

**Comment by SachidanandAlle** [comment]
we should stop using SimpleCRF if it has license issue..

**Comment by SachidanandAlle** [comment]
@andreped ^^

**Comment by SachidanandAlle** [comment]
@masadcv can you please make the changes and exclude only the logic/methods that need simplecrf for now.. and exclude it from sample apps (as we might not have any methods available for scribbles)

**Comment by andreped** [comment]
Oh boy... That's annoying. Shouldn't that mean that SimpleCRF also has to have a GPL license? The virus license strikes again...

But yeah, then my PRs and fixes are not really that helpful (at least for now)...

Rather impressed really that you discovered this breach. There is nothing said about this in the SimpleCRF repo, only on the website here:

> We just noticed that SimpleCRF depends on Yuri Boykov's implementation of maxflow for graphcuts (see: https://github.com/HiLab-git/SimpleCRF/tree/master/dependency/maxflow-v3.0) which is coming from here: https://pub.ist.ac.at/~vnk/software.html

But if you just want to use maxflow, I guess you could use @masadcv's repo [torchmaxflow](https://pypi.org/project/torchmaxflow/0.0.2/) as a starting point. Perhaps make a torchCRF project to replace SimpleCRF?

**Comment by masadcv** [comment]
Many thanks @lassoan I will have a look into grow-cut methods.
Is there any link to graphcut implementation that you have been using in Slicer?

**Comment by masadcv** [comment]
> But if you just want to use maxflow, I guess you could use @masadcv's repo [torchmaxflow](https://pypi.org/project/torchmaxflow/0.0.2/) as a starting point. Perhaps make a torchCRF project to replace SimpleCRF?

Unfortunately the code for that also comes from same source and have same issues with license - so we cant use it here either. I am looking into replacing it with a friendlier license - but it may take some time...

**Comment by masadcv** [comment]
@andrepred can you please send me a message on slack? I am on the MONAI group...

**Comment by andreped** [comment]
> @andreped can you please send me a message on slack? I am on the MONAI group...

I am not a member of that slack team (yet). I have sent a request to join. Will send you a message when I am added to the group.

**Comment by lassoan** [comment]
The graphcut Slicer segmentation module is available here: https://github.com/Slicer/SlicerGraphCutSegment/

The algorithm classes are here: https://github.com/Slicer/SlicerGraphCutSegment/tree/master/GraphCutInteractiveSegmenter/Logic/TumorSegm

It uses Yuri Boykov's maxflow implementation. It probably would not have been a big deal reimplementing that maxflow algorithm, we just did not bother because growcut worked so much better.

**Comment by jamesobutler** [comment]
@masadcv Shall this issue be closed since d1f4b546553e8ffd1336ae70099f9d353fac523c removed SimpleCRF support and a replacement was introduced in fe3751105e905babf69693fee8009c28ef421a24?

**Comment by masadcv** [comment]
Yes, lets close this! Many thanks!
