### ISSUE TITLE
Windows installation issues

### ISSUE THREAD

**Issue by pritesh-mehta** [Project-MONAI/MONAILabel#75]
The following issues were experienced when installing MONAILabel using the installation instructions in the readme on a Windows machine:

1. pip install requirements.txt: installation of monai-weekly[all] was not possible as the cucim package could not be found. Workaround was to install monai instead.
2. Several dependencies had to be installed manually: scikit-image, matplotlib==3.3.0 (3.3.4 caused issues), pytorch-ignite, tensorboard, nibabel. These are potentially available in monai-weekly[all].
3. Running app: native windows filepaths throw escape character error due to use of backslash. Workaround was to type filepaths in using forward slash.
4. monailabel/main: in lines 75 and 76, os.path.realpath converts filepaths entered with forward slash back into native windows filepaths with backslash, subsequently throwing errors related to escape characters. Workaround was to comment out lines 75 and 76.

**Comment by SachidanandAlle** [comment]
You must be right.  So far we have not tried anythong other than Ubunutu.
Near future, we will make the current one compatible to windows (similar to monai)
