### ISSUE TITLE
Cannot download app on Windows

### ISSUE THREAD

**Issue by wanting0wang** [Project-MONAI/MONAILabel#750]
**Describe the bug**
os: windows 10

After installing monailabel on my windows machine, I tried to follow the tutorial. The step to download app `radiology` failed with error 
```
App ... not exist
```
![image](https://user-images.githubusercontent.com/25274600/163848614-eacc4694-a8e8-41e8-a7f3-0cacc4344d26.png)

It seems like instead of _downloading_ the app, it tries to _load/locate_ the app locally?

**To Reproduce**
1. Install monailabel on a windows 10 machine: `pip install monailabel`
2. Run command `monailabel apps --download --name radiology --output apps`

**Expected behavior**
The app should be downloaded.

**Screenshots**
Ended with error. See above for screenshot. 

**Environment**

```
================================
Printing MONAI config...
================================
MONAI version: 0.8.1
Numpy version: 1.21.6
Pytorch version: 1.9.0+cu111
MONAI flags: HAS_EXT = False, USE_COMPILED = False
MONAI rev id: 71ff399a3ea07aef667b23653620a290364095b1

Optional dependencies:
Pytorch Ignite version: 0.4.8
Nibabel version: 3.2.2
scikit-image version: 0.19.2
Pillow version: 9.1.0
Tensorboard version: 2.8.0
gdown version: 4.4.0
TorchVision version: 0.10.0+cu111
tqdm version: 4.64.0
lmdb version: 1.3.0
psutil version: 5.9.0
pandas version: NOT INSTALLED or UNKNOWN VERSION.
einops version: NOT INSTALLED or UNKNOWN VERSION.
transformers version: NOT INSTALLED or UNKNOWN VERSION.
mlflow version: NOT INSTALLED or UNKNOWN VERSION.

For details about installing the optional dependencies, please visit:
    https://docs.monai.io/en/latest/installation.html#installing-the-recommended-dependencies


================================
Printing system config...
================================
System: Windows
Win32 version: ('10', '10.0.19041', 'SP0', 'Multiprocessor Free')
Platform: Windows-10-10.0.19041-SP0
Processor: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
Machine: AMD64
Python version: 3.7.13
Process name: python.exe
Command: ['python', '-c', 'import monai; monai.config.print_debug_info()']
Open files: [popenfile(path='C:\\WINDOWS\\System32\\en-US\\KernelBase.dll.mui', fd=-1), popenfile(path='C:\\WINDOWS\\System32\\en-US\\kernel32.dll.mui', fd=-1), popenfile(path='C:\\Users\\user\\.anaconda\\navigator\\scripts\\anaconda-navigator-app-out-1.txt', fd=-1), popenfile(path='C:\\Users\\user\\.anaconda\\navigator\\scripts\\anaconda-navigator-app-err-1.txt', fd=-1)]
Num physical CPUs: 6
Num logical CPUs: 12
Num usable CPUs: 12
CPU usage (%): [15.7, 10.1, 5.6, 16.9, 34.8, 12.4, 9.0, 0.0, 6.7, 4.5, 0.0, 73.0]
CPU freq. (MHz): 2592
Load avg. in last 1, 5, 15 mins (%): [0.0, 0.0, 0.0]
Disk usage (%): 68.3
Avg. sensor temp. (Celsius): UNKNOWN for given OS
Total physical memory (GB): 15.8
Available memory (GB): 7.8
Used memory (GB): 8.0

================================
Printing GPU config...
================================
Num GPUs: 1
Has CUDA: True
CUDA version: 11.1
cuDNN enabled: True
cuDNN version: 8005
Current device: 0
Library compiled for CUDA architectures: ['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'sm_86', 'compute_37']
GPU 0 Name: NVIDIA GeForce RTX 2070 Super
GPU 0 Is integrated: False
GPU 0 Is multi GPU board: False
GPU 0 Multi processor count: 40
GPU 0 Total memory (GB): 8.0
GPU 0 CUDA capability (maj.min): 7.5
```

**Additional context**

**Comment by jamesobutler** [comment]
`pip install monailabel` will currently get version 0.3.2 which is the latest regular release (https://pypi.org/project/monailabel/0.3.2/#history).  It appears running `monailabel apps --download --name radiology --output apps` is a specific to the latest development release which would require `pip install monailabel>=0.4*`. Otherwise if you are using version 0.3.2, you need to follow instructions at https://github.com/Project-MONAI/MONAILabel#current-release-03x which does not have a radiology app option.

**Comment by wanting0wang** [comment]
@jamesobutler thank you! that's good to know

I followed the instructions on this page (https://docs.monai.io/projects/label/en/latest/installation.html). It doesn't say the example is only for the dev release so I didn't know. Maybe it needs to be updated? And thank you, I will try the dev release :)

**Comment by jamesobutler** [comment]
@wanting0wang I believe you have just missed the documentation version selected. 

The "latest" version of the documentation (https://docs.monai.io/projects/label/en/latest/installation.html#downloading-sample-apps-or-datasets) corresponds to the "latest" code which is https://github.com/Project-MONAI/MONAILabel/tree/main.
![image](https://user-images.githubusercontent.com/15837524/163894338-27c49a46-b018-4896-bf35-8cf843e63b02.png)


The "stable" version of the documentation is referring to released version 0.3.2.
https://docs.monai.io/projects/label/en/stable/installation.html#downloading-sample-apps-or-datasets
![image](https://user-images.githubusercontent.com/15837524/163894216-206062df-089e-445c-add7-810c11c75d4d.png)


MonaiLabel developers @SachidanandAlle and @diazandr3s it is confusing that there is a section to install the "latest" version of MonaiLabel from the "stable" documentation. See for example https://docs.monai.io/projects/label/en/stable/installation.html#from-github or https://docs.monai.io/projects/label/en/0.3.1/installation.html#from-github.

**Comment by wanting0wang** [comment]
@jamesobutler Honestly by "latest" I thought it's the "latest stable version".. now I know it's the dev version! I will add that if it's the dev version, then you may want to remove `pip install monailabel` in this doc page for clarity. Thank you very much for the explanation!

**Comment by SachidanandAlle** [comment]
i believe the docs are updated on.. for stable version.. specially the readme section: https://github.com/Project-MONAI/MONAILabel#currentstable-version-03x

**Comment by jamesobutler** [comment]
@SachidanandAlle Do you know if ReadTheDocs supports specifying a branch for the "Stable" release documentation? Is it possible to backport documentation updates for a stable release? Or is https://docs.monai.io/projects/label/en/stable/ tied to a GitHub tag?

**Comment by SachidanandAlle** [comment]
frankly speaking, we want users to start using the latest version.. stable version is outdated based on the restructure after we add pathology usecase.. we are encouraging people to use latest version (either install through github or latest release candidates or weekly package or docker) so that we can actively support related to user queries related to radiology/pathology usecases..

But otherwise if someone is really looking for stable version install.. we have mentioned the explicit version in readdocs to follow stable release..
