### ISSUE TITLE
UpdateSegmentationMask fails to correctly read .seg.nrrd in Slicer extension after InferTask

### ISSUE THREAD

**Issue by jlvahldiek** [Project-MONAI/MONAILabel#766]
We are using .seg.nrrd format in one of our MONAILabel apps in order to store overlapping segmentations. In a simple `InferTask` a .seg.nrrd gets written correctly to the 'original' folder on the MONAILabel server. When this file is then automatically read and pushed into Slicer in `UpdateSegmentationMask()` the pixel data of the various segments gets flattened to one layer and incorrectly read into Slicer.

In my opinion, these lines probably cause this error and may be have to be adjusted to work with .seg.nrrds: https://github.com/Project-MONAI/MONAILabel/blob/ea1a1feefcc02be37bd123d5be894d4559b5760c/plugins/slicer/MONAILabel/MONAILabel.py#L1586

When I load one of the generated .seg.nrrd files with `slicer.util.loadSegmentation()` in Slicer's Python interactor everything is displayed as expected and I don't think that the these files are corrupted.

I am not sure what is the best implementation to import .seg.nrrds back into Slicer after an `InferTask` but if you like I could propose a first PR.

**Comment by diazandr3s** [comment]
Hi @jlvahldiek,

Yes, please propose the PR. 
In case you'd like to use a MONAI Label App for overlapping segments, remember that the sample apps, by default, have softmax and then one-hot outputs https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/infers/deepedit.py#L111

This is something that should be changed when thinking about an app that works on overlapping segments

**Comment by jlvahldiek** [comment]
Thank you, @diazandr3s. 
You are right, in fact in our subclass of InferTask we had to modify the write method/writer class accordingly so that a multi-channel segmentation is saved in .seg.nrrd format. This works fine so far.

The problem then is the re-import of the .seg.nrrd file generated by InferTask back into Slicer. This re-import does not work with the current implementation of UpdateSegmentationMask().

Currently we are using an ugly workaround. I will tweak the code and submit a PR.
