### ISSUE TITLE
MONAILabel plugins command-line list/download path broken

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#795]
MONAILabel command line for installing plugins from pip package seems to have a broken path.

What I tried?
In a new virtualenv, I installed monailabel==0.4.0rc3 and tried accesing plugins through commandline
```
$ pip install monailabel==0.4.0rc3
$ monailabel plugins
```

What I got?
I got error the following error message:
```
Using PYTHONPATH=/mypath:
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mypath/venv/lib/python3.8/site-packages/monailabel/main.py", line 352, in <module>
    Main().run()
  File "/mypath/venv/lib/python3.8/site-packages/monailabel/main.py", line 124, in run
    self.action_plugins(args)
  File "/mypath/venv/lib/python3.8/site-packages/monailabel/main.py", line 212, in action_plugins
    plugins = os.listdir(plugins_dir)
FileNotFoundError: [Errno 2] No such file or directory: '/mypath/venv/scripts/monailabel/plugins'
```

If I look through the folders, the plugins folder exist under `/mypath/venv/monailabel/plugins`

Expected output:
It should list all available plugins

Platform:
Ubuntu 20

**Comment by SachidanandAlle** [comment]
If monailabel install path is not automatically determined, then you can provide explicit install path as: monailabel apps --prefix ~/.local

I guess it's not working for apps either..

**Comment by masadcv** [comment]
Install path seems to exist and taken properly - but it is looking for the plugins under:
`./venv/scripts/monailabel` 

where the path where this exists on disk is:
`./venv/monailabel` 

Apps seem to be fine. 

I believe the culprit could be this line:
https://github.com/Project-MONAI/MONAILabel/blob/58dc813db3f50d838a81804ee0a9635055802b92/monailabel/main.py#L210

**Comment by pieper** [comment]
User experience and workaround reported here: https://discourse.slicer.org/t/how-to-start-with-monailabel-for-new-models/21063/31
