### ISSUE TITLE
Provide example implementations for some standard active learning strategies

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#8]
Implement DeepGrow inference by implementing the `MONAILabelApp` API
Present proposal tomorrow:
- Training is continuous - async
- Batch inference is required for image selection (TTA, Loss Prediction) - async
- Labels generated when trained model is available

**Comment by diazandr3s** [comment]
Let's start by using simple random sampling as an active learning technique

**Comment by SachidanandAlle** [comment]
Closing this.. as we are only using random as standard strategy
