### ISSUE TITLE
Multi-GPU on DeepEdit UNETR network

### ISSUE THREAD

**Issue by guanjiahui** [Project-MONAI/MONAILabel#827]
The Multi-GPU stops working for DeepEdit on UNETR network. Errors below

/opt/conda/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 2 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
[2022-05-13 15:51:37,994] [33828] [ThreadPoolExecutor-1_0] [INFO] (monailabel.utils.async_tasks.utils:76) - Return code: -7

If we turn off multi-GPU (uncheck the multi-gpu on 3D slicer GUI), it works well on a single GPU. 
If we use another model on DeepEdit with multi-GPU, it also works.

**Comment by SachidanandAlle** [comment]
which version of monailabel r u using? this problem is solved only in current main branch/latest release candidate version (0.4.x)

**Comment by guanjiahui** [comment]
DynUNET works fine on both single and multi-GPU. 
UNETR works fine on single GPU, but no multi-GPU. 
Please let us know if multi-gpu on UNETR is solved/supported in the latest version

**Comment by diazandr3s** [comment]
@guanjiahui could you please share the full log you get when running UNETR on multi GPU set-up?
I just rechecked and it works fine on my 2 GPU set-up. Attached 2-minutes video showing this.

**Comment by guanjiahui** [comment]
Please find the full log attached.
[UNETR_multiGPU_full-error.txt](https://github.com/Project-MONAI/MONAILabel/files/8961103/UNETR_multiGPU_full-error.txt)

**Comment by SachidanandAlle** [comment]
are you still facing this problem.. i guess this is more of env issue.. as multiple users can run the training on multi-gpu
closing this issue for now.. feel free to reopen if the issue persists by providing more details/logs etc..
