### ISSUE TITLE
cv2 import error in docker image projectmonai/monailabel:0.4.0

### ISSUE THREAD

**Issue by nvahmadi** [Project-MONAI/MONAILabel#837]
**Describe the bug**
MONAI-Label Server cannot be executed in the current version of the monailabel docker container, because of an `opencv` import error. 

**To Reproduce**
1. Run docker container, tag 0.4.0, e.g. via: `docker run -it --gpus all  --network=host projectmonai/monailabel:0.4.0 bash`
2. Run: `python -c "import cv2"`

**Error message**
This throws the following error message:
```
root@workstation:/opt/monai# python -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/opt/conda/lib/python3.8/site-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/conda/lib/python3.8/site-packages/cv2/mat_wrapper/__init__.py", line 33, in <module>
    cv._registerMatType(Mat)
AttributeError: partially initialized module 'cv2' has no attribute '_registerMatType' (most likely due to a circular import)
```
**Environment**
As described above, I am using OOTB docker container `projectmonai/monailabel:0.4.0`.

**Additional information**
For context, this error does not occur in the current monai-core docker image: `projectmonai/monai:0.9.0`.

**Comment by SachidanandAlle** [comment]
let me see why it's complaining `partially initialized module 'cv2'.. 
meanwhile have you tried with `monailabel:latest` (both should be same.. just built at different time)

**Comment by nvahmadi** [comment]
Good idea, I tried, and the same error occurs with `monailabel:latest`. Thanks for looking into this!

**Comment by SachidanandAlle** [comment]
```
docker run --gpus all --rm -ti --ipc=host --net=host -v ~:/workspace projectmonai/monai:latest bash
python -c "import cv2" # OK

pip install opencv-python-headless
python -c "import cv2" # NOT OK
```

**Comment by nvahmadi** [comment]
One more note - I was using the monailabel container tagged as `0.4.0rc3` for a while and I had not problems with cv2 in there. Hope this helps in tracking down the breaking changes.

**Comment by SachidanandAlle** [comment]
4.6.0.66 has some issue and conflicts with conda (not with regular python)
so the current solution is
- downgrade opencv-python-headless to previous 4.5.5.64 `pip install opencv-python-headless==4.5.5.64`

**Comment by nvahmadi** [comment]
That was fast, thanks! I can fix that locally - how long will it roughly take until the fixed 0.4.0 image can be pulled from dockerhub?

**Comment by SachidanandAlle** [comment]
Can you try again..
you can pull the latest image again..
`docker pull projectmonai/monailabel:0.4.0` or `latest`

I verified for latest tag.. it should work for 0.4.0 also

**Comment by nvahmadi** [comment]
Works now, many thanks :)
