### ISSUE TITLE
Error while running on Qupath

### ISSUE THREAD

**Issue by shabirmoosa** [Project-MONAI/MONAILabel#846]
Hi Team,

I receive the attached error after installing and using monai label plugin on Qupath. I was running nuclei_deepedit model on a selected rectangle ROI. I could also see the below error in the terminal

    axis = tuple([normalize_axis_index(ax, ndim, argname) for ax in axis])
numpy.AxisError: source: axis -1 is out of bounds for array of dimension 0

Im using the following versions
Ubuntu 20.04
Qupath 0.3.2 (also tested on v0.2.3)
Monailabel plugin v0.3.0

Appreciate your help in this regard

![Screenshot from 2022-06-22 14-23-01](https://user-images.githubusercontent.com/13909220/175018613-f3b078d4-c9dd-411b-b354-61db5e717e8d.png)

**Comment by diazandr3s** [comment]
Hi @shabirmoosa,

Thanks for creating this issue.
Have you started the MONAI Label server? There are two sides of this: the server and the user interface (UI). You've installed the UI but it seems the server isn't up. 
Check [this video](https://drive.google.com/file/d/18I8Xtd4Yp40L5YInLTiIUO445DwJ4hJA/view?usp=sharing) to see how that should work.

Hope that helps.

**Comment by shabirmoosa** [comment]
Thanks Andres for the reply. The server was up and and running. I also reinstalled the github version in a clean environment but unfortunately the same issue persists. Any thoughts on this?

**Comment by diazandr3s** [comment]
Thanks, @shabirmoosa 
It's strange. Could you please share the command you've used to start the server and the full log?

**Comment by SachidanandAlle** [comment]
u can share the server logs.. after you click the inference.. the snapshot has very little detail to understand what operation is done..

**Comment by shabirmoosa** [comment]
Thanks @SachidanandAlle  and @diazandr3s . 
Below is the commmand i use to run the monailabel server
**monailabel start_server --app apps/pathology --studies datasets --conf models all**

Along with the full apps logs, i have also attached the error message i see on the terminal of monailabel server and qupath for more information. Thanks in advance for looking into this.
[error_on_terminal_qupath.txt](https://github.com/Project-MONAI/MONAILabel/files/8964486/error_on_terminal_qupath.txt)
[error_on_terminal_monailabelserver.txt](https://github.com/Project-MONAI/MONAILabel/files/8964487/error_on_terminal_monailabelserver.txt) 
[app.log](https://github.com/Project-MONAI/MONAILabel/files/8964455/app.log)

**Comment by diazandr3s** [comment]
Thanks, @shabirmoosa.
From what I can see, there are no samples in the datasets folder you used to start the server.
My suggestions are the following:

1/ Start the server without specifying the models - it is not needed

`monailabel start_server --app apps/pathology --studies datasets `

2/ Make sure the images you're loading in QuPath are in the folder you used to start the server "datasets".
The reason for this is images are not sent from the QuPath to the server. They should be in the same folder.
In the video I shared before, you can see how I loaded an image exactly from the folder I used to start the server - minute 2:25

3/ Run inference using an ROI as you did before.

Hope that helps

**Comment by shabirmoosa** [comment]
@diazandr3s ..When you mentioned about the images not loading , i looked at the logs and  saw the supported file extensions in the configurations. I noticed that the files i had were in .tiff format. Changed them to .tif and wohooo it works !!!! Thanks for the help

[2022-06-23 14:10:40,014] [1318393] [MainThread] [INFO] (__main__:273) - ENV SETTINGS:: MONAI_LABEL_DATASTORE_FILE_EXT = '["*.nii.gz", "*.nii", "*.nrrd", "*.jpg", "*.png", "*.tif", "*.svs", "*.xml"]'

**Comment by diazandr3s** [comment]
I'm glad to hear this, @shabirmoosa 
Have you tried adding .tiff format [here](https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/config.py#L38)? It should work with that format as well once added.
You may be interested in reading more about the [digital pathology working group](https://github.com/Project-MONAI/MONAI/wiki/Pathology-Working-Group)
[Here](https://github.com/Project-MONAI/MONAI/wiki/IO-Working-Group-Meeting-Notes) we discuss the IO.

BTW, this is the first version of the pathology app. There is still room for improvement. Please don't hesitate sharing your experience
