### ISSUE TITLE
monailabel script is unable to detect python v2 versions

### ISSUE THREAD

**Issue by qing-at-work** [Project-MONAI/MONAILabel#849]
**Describe the bug**
When default python is version 2.x, the monailabel script doesn't correctly detect python v2 versions and fails to launch monailabel using python3.

**To Reproduce**
OS: ubuntu
1. Set default python to python version 2, e.g. `sudo update-alternatives --install /usr/bin/python python /usr/bin/python2.7 3`
2. Verify python version is set to v2, e.g. `python --version`
3. Run monailabel command

**Expected behavior**
monailabel script detects python is of version 2.x, and tries to launch monailabel using `python3`

**Actual behavior**
monailabel script is unable to detect python version 2.x and still uses python 2.x to launch.

**Analysis**
This is because python v2.x outputs version info into STDERR instead of STDOUT due to this [bug](https://bugs.python.org/issue18338), so the following code in the script doesn't set the `version` variable:
```bash
version=$(python --version)
```

**Comment by SachidanandAlle** [comment]
Monailabel only supports 3.6 and above..

https://docs.monai.io/projects/label/en/latest/installation.html#prerequisites
