### ISSUE TITLE
Once Training finishes 'Stop Training' button should not require to be pressed. The signal should be sent automatically

### ISSUE THREAD

**Issue by finalelement** [Project-MONAI/MONAILabel#86]
**Describe the bug**
After annotating a few samples ('N' samples) once the button 'update model' is pressed. It begins to train the model, after the training finishes and the stats are reported. A signal should be sent to the Slicer 3D that training has been stopped. At the moment, the 'Stop Training' button has to be pressed

**To Reproduce**
1. Follow the installation instructions and add the module to Slicer
2. Load the data, annotate a few samples, hit the 'Update Model'
3. Wait for training to finish and the stats to get reported
4. _In slicer 3D now the 'Stop training' button should not need to be pressed manually._

**Expected behavior**
The expectation is that the 'Stop Training' button should not be pressed manually.

**Screenshots**
Here is a screenshot
![image](https://user-images.githubusercontent.com/8859225/119385229-78514480-bc8b-11eb-8dd7-e0e8910ddf16.png)

**Comment by SachidanandAlle** [comment]
Refresh in the clinet is missing

You can check the status manually.. you don't have to press stop..
We can add auto refresh to query status every N seconds in slicer after training is clicked

**Comment by SachidanandAlle** [comment]
Auto refresh is added to query the training status (if running) every 5 seconds..
https://github.com/Project-MONAI/MONAILabel/commit/2bbc35b75ded86ea42303afebb757945d9188a11
