### ISSUE TITLE
Logging error

### ISSUE THREAD

**Issue by JuanMPinera** [Project-MONAI/MONAILabel#862]
I installed the weekly version and started the server, but when I try to connect from Slicer, it gives me the next error:

![image](https://user-images.githubusercontent.com/26545600/177433972-8d3adbc0-0067-4f71-8229-5d7d02e2d44b.png)

How can I solve this?
Thanks

**Comment by SachidanandAlle** [comment]
i see this issue caused by conda env.. we will have a quick fix for this..
