### ISSUE TITLE
Support runtime settings

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#90]
User should be able to provide some runtime settings to change the default behavior.
For example, auto reload datastore, extensions for datastore...

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/pull/89
Few settings related to datastore are added..

Need more??

**Comment by aihsani** [comment]
This looks to to me. Perhaps @diazandr3s as a user may make other suggestions once he find something missing. We can close for now.
