### ISSUE TITLE
Checkpoint loading: to support customized state_dict name key

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAILabel#902]
The current MONAILABEL loads all model checkpoint by the key "model", if any pre-trained model is not saved with name key "model", it will load failed. 

We can add 'model_state_dict' as a parsing parameter for users so that MONAILABEL can load any checkpoint with any state_dict names.

**Comment by SachidanandAlle** [comment]
You can pass that option when in config when you creat the instance for infer task..

https://github.com/Project-MONAI/MONAILabel/blob/main/monailabel/interfaces/tasks/infer.py#L67

And pass additional kwagrs while creating the object.. example..
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/radiology/lib/configs/segmentation.py#L80

**Comment by tangy5** [comment]
Cool. 
Seems it's already flexible when creating the sample apps. 
It would be great if we can add this to the bundle app in [BundleInferTask](https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/monaibundle/lib/infers/bundle.py)


```
        super().__init__(
            path=model_path,
            network=network,
            type=type,
            labels=labels,
            dimension=dimension,
            description=description,
            preload=conf.get("preload", False),
            model_state_dict=model_state_dict
        )
```
