### ISSUE TITLE
Tool Detection Model

### ISSUE THREAD

**Issue by SachidanandAlle** [Project-MONAI/MONAILabel#913]
Integrate Tool Detection Model as part of Endoscopy app and show-case the same in CVAT

**Comment by Nic-Ma** [comment]
What's the "tool detection" model here?
Do you mean the "tool tracking" segmentation model?

Thanks

**Comment by SachidanandAlle** [comment]
You can change the title.. this was created for the DeID classification model

**Comment by SachidanandAlle** [comment]
https://github.com/Project-MONAI/MONAILabel/blob/main/sample-apps/endoscopy/lib/configs/deid.py
Done!
