### ISSUE TITLE
NormalizeLabelsInDatasetd to lost Meta Information 

### ISSUE THREAD

**Issue by tangy5** [Project-MONAI/MONAILabel#921]
**Describe the bug**
During handling a discussion problem with a user, I found the transformation **NormalizeLabelsInDatasetd** in deepedit has some issues to be compatible with MetaTensor. It seems the meta information after **NormalizeLabelsInDatasetd** will be lost. 

Version: latest MONAI and MONAILABEL release.

**To Reproduce**
```
from monai.transforms import (
    EnsureChannelFirstd,
    LoadImaged,
    SaveImaged,
    Compose,
    Orientationd
)
from monai.apps.deepedit.transforms import (
    NormalizeLabelsInDatasetd,
)

_labels = {'cancer': 1, 'transfer': 2, 'background': 0}

train_transforms = Compose(
    [
        LoadImaged(keys=("label"), reader="ITKReader"),
        NormalizeLabelsInDatasetd(keys=("label"), label_names=_labels),
        EnsureChannelFirstd(keys=("label")),
        Orientationd(keys=("label"), axcodes="RAS"),
        #========================================================================
        SaveImaged(keys="label", output_dir = './', mode='bilinear', output_postfix='label2')
    ]
)

image_path = [{'label': '/home/yuchengt/yuchengt/2022/MONAI/monailabel_projectYT/MONAILabel-main/test_data/HNC/labels/original/NPC_AI_Detectionl_01.nii.gz'}]
train_transforms(image_path)
```
**Behavior**

`isinstance(img, MetaTensor)` will be True, but `img.meta` will lost meta information. 

**`KeyError: 'filename_or_obj'`**

The tested data can be downloaded via the link that the user provided:

https://drive.google.com/file/d/1VSHNW1m3mLZDch60S_LdHF62kUdiCai_/view?usp=sharing

**Comment by diazandr3s** [comment]
Thanks for creating this issue, @tangy5 

I guess the problem is because this transform changes the label MetaTensor by a numpy array here: https://github.com/Project-MONAI/MONAI/blob/dev/monai/apps/deepedit/transforms.py#L104

**Comment by tangy5** [comment]
> 

Cool, will we have a plan to check this issue or create a fixing PR?
Thank you!

**Comment by diazandr3s** [comment]
Yes, I'll propose a PR for this later today :)
