### ISSUE TITLE
DICOMWebDatastore  limited to modality "CT"

### ISSUE THREAD

**Issue by jlvahldiek** [Project-MONAI/MONAILabel#945]
The modality that DICOMWebDatastore is searching for is hardcoded and limited to "CT":
https://github.com/Project-MONAI/MONAILabel/blob/48441c3353cd7940a1b9e7e0d5fc06b1b2a9a4c9/monailabel/datastore/dicom.py#L43

It would be very useful for my team to use DICOMWebDatastore with other modalities (MR, CR, etc.). 

What do you think is the best way to make the modality customizable by the user? Maybe it would be also helpful in the future to define some kind of filter list (i.e. modality, date, sex, etc.) that DICOMWebDatastore will use to list images - but this is probably an issue in itself.

**Comment by SachidanandAlle** [comment]
Yes.. this was done long back.. but some improvements in xnat based.. we don't need conversations from dicom to nifti.. dicom data store can be improved..
