### ISSUE TITLE
[scribbles] How to expose parameters from info.yaml for scribbles post processing?

### ISSUE THREAD

**Issue by masadcv** [Project-MONAI/MONAILabel#95]
This is more of a question on what might be the best approach in your view to incorporate parameters from client side into a post processing function.

I am trying to expose parameters for setting up CRF,  as an example let's take the number of iterations CRF is run:
https://github.com/Project-MONAI/MONAILabel/blob/87a3a8845a8f772cd95b5761603c0ed4a81b8469/sample-apps/segmentation_spleen_postproc/lib/transforms.py#L129

I already have relevant entries in info.yaml for my app for this. Not entirely sure how to pass these to inferer function. I need help on how would you approach this?
https://github.com/Project-MONAI/MONAILabel/blob/87a3a8845a8f772cd95b5761603c0ed4a81b8469/sample-apps/segmentation_spleen_postproc/lib/postproc.py#L64

There may be other similar entries for additional scribbles postprocessors. Each one has a different set of options which may need to be exposed in individual apps.

**Comment by SachidanandAlle** [comment]
Info.yaml.. is the easy way to share anything between app and client.. what you put there..  u get it at client end 

Lets discuss this over wed sync up

**Comment by SachidanandAlle** [comment]
I guess you got the idea of adding config params in info.yaml and show them in slicer for client to change.
closign this issue..
