### ISSUE TITLE
MR Modality entire pipeline from Coldstart with no model at the beginning

### ISSUE THREAD

**Issue by finalelement** [Project-MONAI/MONAILabel#98]
We need a pipeline with all pre-processing defined for MR imaging modality with the heart dataset from medical segmentation decathlon.

**Comment by finalelement** [comment]
Created an application with the MONAI Label framework for a MR based Deepgrow. The app does not require pre-trained weights and can do a Cold Start.

The developed has been merged into the MONAI Label toolkit:
[https://github.com/Project-MONAI/MONAILabel/pull/108](url)

Also tested with initialization of CT based Deepgrow Weights. Initial results report that it can work with as minimal as 5 samples.

More testing needs to be done

**Comment by SachidanandAlle** [comment]
can you add the details and close this issue if it's done

**Comment by finalelement** [comment]
In brief, this issue can be alleviated using pre-trained weights on a larger dataset. Refer below for more details. Closing this issue as we will be releasing the pre-trained weights as a choice to the user.

![image](https://user-images.githubusercontent.com/8859225/122854909-07c53400-d2da-11eb-9431-546ae736548e.png)
